// <auto-generated>
// This file was generated by CircularLibraryDependencySourceRewriter.
// Changes to this file will be overwritten.
// </auto-generated>
#nullable enable
using System;
using Compze.Utilities.Misc;

namespace Compze.Utilities.SystemCE.ThreadingCE.ResourceAccess;

//THis file contains the methods that implementations actually have to implement
internal partial interface IMonitorCE
{
   static readonly TimeSpan DefaultTimeout = CompzeEnvironment.IsNCrunch
                                                ? 45.Seconds() //Tests timeout at 60 seconds. We want locks to timeout faster so that the blocking stack traces turn up in the test output so we can diagnose the deadlocks.
                                                : 2.Minutes(); //MsSql default query timeout is 30 seconds. Default .Net transaction timeout is 60. If we reach 2 minutes it is highly likely that we have an in-memory deadlock.

   public static IMonitorCE WithDefaultTimeout() => new MonitorCE(DefaultTimeout, DefaultTimeout);
   public static IMonitorCE WithTimeouts(TimeSpan lockTimeout, TimeSpan? waitTimeout = null) => new MonitorCE(lockTimeout, waitTimeout ?? lockTimeout);

   TimeSpan LockTimeout { get; }
   TimeSpan WaitTimeout { get; }

   IDisposable TakeReadLock(TimeSpan? timeout = null);
   IDisposable TakeUpdateLock(TimeSpan? timeout = null);

   IDisposable TakeReadLockWhen(Func<bool> condition, TimeSpan? waitTimeout = null, TimeSpan? lockTimeout = null);
   IDisposable TakeUpdateLockWhen(Func<bool> condition, TimeSpan? waitTimeout = null, TimeSpan? lockTimeout = null);

   IDisposable? TryTakeReadLockWhen(Func<bool> condition, TimeSpan? waitTimeout = null, TimeSpan? lockTimeout = null);
   IDisposable? TryTakeUpdateLockWhen(Func<bool> condition, TimeSpan? waitTimeout = null, TimeSpan? lockTimeout = null);


   long ContentionCount { get; }

   //review: do we want this exposed?
   void SetTimeToWaitForStackTrace(TimeSpan timeToWaitForStackTrace);
}
