// <auto-generated>
// This file was generated by CircularLibraryDependencySourceRewriter.
// Changes to this file will be overwritten.
// </auto-generated>
using System;
using System.Collections.Generic;
using System.Linq;
using Compze.Utilities.Functional;
using Compze.Utilities.SystemCE.LinqCE;

namespace Compze.Utilities.DependencyInjection.Abstractions;

//todo: rather than passing an untyped IRunMode around and using it to make decisions.
// Subtypes of IComponentRegistrar should be making the decisions, and tests should supply a different IComponentRegistrar than production code.
// The test version of the registrar would know about TestEnv, none of the production code should need any testing references or DbPool references etc.
internal interface IComponentRegistrar
{
   IComponentRegistrar Register(params ComponentRegistration[] registrations);

   IComponentRegistrar Register(params Action<IComponentRegistrar>[] registrationMethods)
      => registrationMethods.ForEach(it => it(this))
                            .then(this);

   IDependencyInjectionContainer Container();

   TTestingRegistrar? TryGetTestingRegistrar<TTestingRegistrar>() where TTestingRegistrar : class;

   void SetContainer(IDependencyInjectionContainer container);
   IComponentRegistrar Clone();
}

internal interface IDependencyInjectionContainer : IDisposable, IAsyncDisposable
{
   IComponentRegistrar Register();
   IDependencyInjectionContainer Register(params ComponentRegistration[] registrations);
   IEnumerable<ComponentRegistration> RegisteredComponents();
   IServiceLocator ServiceLocator { get; }
   bool IsRegistered<TComponent>() where TComponent : class => RegisteredComponents().Any(it => it.ServiceTypes.Contains(typeof(TComponent)));
}

internal interface IServiceLocator : IDisposable, IAsyncDisposable
{
   TComponent Resolve<TComponent>() where TComponent : class;
   TComponent[] ResolveAll<TComponent>() where TComponent : class;
   object Resolve(Type serviceType);
   IDisposable BeginScope();
}

internal enum Lifestyle
{
   Singleton,
   Scoped
}
