// <auto-generated>
// This file was generated by Compze.InternalizedSourceReferences.
// Changes to this file will be overwritten.
// </auto-generated>
#nullable enable
using System;
using System.Runtime.CompilerServices;
using Compze.Utilities.SystemCE;

namespace Compze.Utilities.Contracts;

internal partial class ContractAsserter
{
   public ContractAsserter IsValid<TEnum>(TEnum value, [CallerArgumentExpression(nameof(value))] string valueExpression = "")
      where TEnum : struct, Enum =>
      !value.IsValid() ? this : throw _createException($"{valueExpression} is not a valid {typeof(TEnum).Name} value");

   public ContractAsserter IsValid(Enum value, [CallerArgumentExpression(nameof(value))] string valueExpression = "") =>
      !value.IsValid() ? this : throw _createException($"{valueExpression} is not a valid {value.GetType().Name} value");
}