// <auto-generated>
// This file was generated by Compze.InternalizedSourceReferences.
// Changes to this file will be overwritten.
// </auto-generated>
#nullable enable
using System.Runtime.CompilerServices;

namespace Compze.Utilities.Contracts;

internal partial class ContractAsserter
{
   public ContractAsserter IsGreaterThan(int value, int lowerBound, [CallerArgumentExpression(nameof(value))] string valueString = "") =>
      value > lowerBound ? this : throw _createException($"{valueString} was {value} which is not greater than {lowerBound}");
}
