// <auto-generated>
// This file was generated by CircularLibraryDependencySourceRewriter.
// Changes to this file will be overwritten.
// </auto-generated>
using System;

namespace Compze.Utilities.DependencyInjection;

internal class InstantiationSpec
{
   public object? SingletonInstance { get; }
   public object RunFactoryMethod(IServiceLocatorKernel kern) => FactoryMethod(kern);
   public Func<IServiceLocatorKernel, object> FactoryMethod { get; }
   public Type FactoryMethodReturnType { get; }

   public static InstantiationSpec FromInstance(object instance) => new(instance);

   public static InstantiationSpec FromFactoryMethod(Func<IServiceLocatorKernel, object> factoryMethod, Type factoryMethodReturnType) => new(factoryMethod, factoryMethodReturnType);

   InstantiationSpec(Func<IServiceLocatorKernel, object> factoryMethod, Type factoryMethodReturnType)
   {
      FactoryMethodReturnType = factoryMethodReturnType;

      FactoryMethod = factoryMethod;
   }

   InstantiationSpec(object singletonInstance)
   {
      SingletonInstance = singletonInstance;
      FactoryMethod = _ => singletonInstance;
      FactoryMethodReturnType = singletonInstance.GetType();
   }
}
