// <auto-generated>
// This file was generated by CircularLibraryDependencySourceRewriter.
// Changes to this file will be overwritten.
// </auto-generated>
namespace Compze.Utilities.DependencyInjection;

internal interface IServiceLocatorKernel
{
   TComponent Resolve<TComponent>() where TComponent : class;
}
