using System;

namespace AccountManagement.Domain.Events;

// ReSharper disable All
#pragma warning disable IDE1006,IDE0001,IDE0002,IDE0003,IDE0004,IDE0005,IDE0055,CA1050,CA1707,CA1716

/// <summary>
/// This file is automatically generated. Do not edit manually.
/// Regenerate by running the application when type mappings are missing.
/// </summary>
public sealed class AutoGeneratedCurrentAssemblyTypeMapperForRefactoringSupport
{
      public void MapTypesForCurrentAssembly(Action<Guid, Type> map)
   {
      map(new Guid("8931248d-0e68-456d-ace4-b7533341ca50"), typeof(AccountManagement.Domain.Events.AccountEvent.Created));
      map(new Guid("8c6b6479-45ae-45bc-95e3-a9ba64256171"), typeof(AccountManagement.Domain.Events.AccountEvent.Created[]));
      map(new Guid("2b064bf8-5647-4e64-a8f7-31a99d3f2135"), typeof(AccountManagement.Domain.Events.AccountEvent.Implementation.LoggedIn));
      map(new Guid("ef668791-eb87-4ec0-84f8-d858960c0948"), typeof(AccountManagement.Domain.Events.AccountEvent.Implementation.LoggedIn[]));
      map(new Guid("43f4571d-5685-42ce-ad41-380f6506232e"), typeof(AccountManagement.Domain.Events.AccountEvent.Implementation.LoginFailed));
      map(new Guid("4d59a311-5114-4580-bf36-b91488d89c4f"), typeof(AccountManagement.Domain.Events.AccountEvent.Implementation.LoginFailed[]));
      map(new Guid("81d9b4dd-20d1-4b9d-90c6-d72d0e724c6c"), typeof(AccountManagement.Domain.Events.AccountEvent.Implementation.Root));
      map(new Guid("6c8192d6-11a7-4e7c-960a-890fbbc7b2c4"), typeof(AccountManagement.Domain.Events.AccountEvent.Implementation.Root[]));
      map(new Guid("6f1c6af2-b00b-4d58-9acb-5124da423029"), typeof(AccountManagement.Domain.Events.AccountEvent.Implementation.UserChangedEmail));
      map(new Guid("1e493e44-9492-4f76-acc0-059dd1f8d126"), typeof(AccountManagement.Domain.Events.AccountEvent.Implementation.UserChangedEmail[]));
      map(new Guid("b58ca0a2-2ab1-4012-9a01-a1d3793efb85"), typeof(AccountManagement.Domain.Events.AccountEvent.Implementation.UserChangedPassword));
      map(new Guid("fb678fae-746d-4044-a0d2-68efb30a5336"), typeof(AccountManagement.Domain.Events.AccountEvent.Implementation.UserChangedPassword[]));
      map(new Guid("520153b9-d200-4073-aaed-e94eb8f5e8c6"), typeof(AccountManagement.Domain.Events.AccountEvent.Implementation.UserRegistered));
      map(new Guid("f4becd54-6802-482f-b14c-779538014f00"), typeof(AccountManagement.Domain.Events.AccountEvent.Implementation.UserRegistered[]));
      map(new Guid("ee8aa3b0-0c81-4e37-ab3e-7483de451cbb"), typeof(AccountManagement.Domain.Events.AccountEvent.LoggedIn));
      map(new Guid("e6e55d26-87ca-4929-93f1-b4859ddc3aff"), typeof(AccountManagement.Domain.Events.AccountEvent.LoggedIn[]));
      map(new Guid("a50f9d6c-6101-4810-8897-6764eba53ca3"), typeof(AccountManagement.Domain.Events.AccountEvent.LoginAttempted));
      map(new Guid("690b9336-5ef9-480d-9058-f8557a14e158"), typeof(AccountManagement.Domain.Events.AccountEvent.LoginAttempted[]));
      map(new Guid("ad6151e5-30d7-4017-9e85-0f5f9927959f"), typeof(AccountManagement.Domain.Events.AccountEvent.LoginFailed));
      map(new Guid("d0d1e565-13bf-4762-8e0e-32bbe84916a0"), typeof(AccountManagement.Domain.Events.AccountEvent.LoginFailed[]));
      map(new Guid("928903b1-3091-4e11-8fa5-ee0b72699ad2"), typeof(AccountManagement.Domain.Events.AccountEvent.PropertyUpdated.Email));
      map(new Guid("b8e83dba-ffda-4967-9fb2-683bb9569105"), typeof(AccountManagement.Domain.Events.AccountEvent.PropertyUpdated.Email[]));
      map(new Guid("febc74b3-0b78-4401-a853-7f381fdbfafe"), typeof(AccountManagement.Domain.Events.AccountEvent.PropertyUpdated.Password));
      map(new Guid("739ed578-6bb6-461f-8a3a-4b22c5a690e5"), typeof(AccountManagement.Domain.Events.AccountEvent.PropertyUpdated.Password[]));
      map(new Guid("9cb768af-5405-42a3-85d8-ac099b65067b"), typeof(AccountManagement.Domain.Events.AccountEvent.Root));
      map(new Guid("51ddc4ca-17f0-44b3-8ec2-856d1e37f254"), typeof(AccountManagement.Domain.Events.AccountEvent.Root[]));
      map(new Guid("04508773-15eb-49f6-af24-46602f15cd3b"), typeof(AccountManagement.Domain.Events.AccountEvent.UserChangedEmail));
      map(new Guid("81809b72-7ee4-4e90-bb84-9b0ee2118901"), typeof(AccountManagement.Domain.Events.AccountEvent.UserChangedEmail[]));
      map(new Guid("95e4baa1-8b94-4e61-a99c-e19ab6252813"), typeof(AccountManagement.Domain.Events.AccountEvent.UserChangedPassword));
      map(new Guid("653d0dea-6715-4165-bdad-71e1e647a73d"), typeof(AccountManagement.Domain.Events.AccountEvent.UserChangedPassword[]));
      map(new Guid("87d92dea-1f98-4825-b2ee-0c5bd4a43998"), typeof(AccountManagement.Domain.Events.AccountEvent.UserRegistered));
      map(new Guid("edc72828-cf21-42ad-8ecf-1dff01cd13e8"), typeof(AccountManagement.Domain.Events.AccountEvent.UserRegistered[]));
   }
}