// <auto-generated>
// This file was generated by Compze.InternalizedSourceReferences.
// Changes to this file will be overwritten.
// </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;
using Compze.Utilities.SystemCE.ThreadingCE;
using Compze.Utilities.SystemCE.ThreadingCE.ResourceAccess;

// ReSharper disable StaticMemberInGenericType

namespace Compze.Utilities.DependencyInjection;

internal abstract class TypeIndex<TInheritor> where TInheritor : TypeIndex<TInheritor>
{
   static readonly IMonitorCE MonitorCE = IMonitorCE.WithDefaultTimeout();
   public static int ServiceCount { get; private set; }
   static IReadOnlyDictionary<Type, int> _map = new Dictionary<Type, int>();

   static Type[] _backMap = [];

   public static int For(Type type)
   {
      if(_map.TryGetValue(type, out var value))
         return value;

      using(MonitorCE.TakeUpdateLock())
      {
         if(_map.TryGetValue(type, out var value2))
            return value2;

         OnlyWithinLocksThreadingHelpers.AddToCopyAndReplace(ref _backMap, type);
         OnlyWithinLocksThreadingHelpers.AddToCopyAndReplace(ref _map, type, ServiceCount++);
         return ServiceCount - 1;
      }
   }

   internal static class ForService<TType>
   {
      public static readonly int Index = ServiceTypeIndex.For(typeof(TType));
   }
}