using System;
using Compze.Tests.Common.CQRS.EventRefactoring.Migrations;
using Compze.Tests.Common.CQRS.EventRefactoring.Migrations.Events;
using Compze.Tests.Common.Sql.DocumentDb;
using Compze.Tests.Common.Tessaging.ServiceBusSpecification.Given_a_backend_endpoint_with_a_command_event_and_query_handler;

// ReSharper disable All
namespace Compze.Tests.Common;

#pragma warning disable IDE1006,IDE0001,IDE0002,IDE0003,IDE0004,IDE0005,IDE0055,CA1050,CA1707,CA1716

/// <summary>
/// This file is automatically generated. Compze will automatically figure out most types that need to go in here, but some types you may need to add yourself.
/// Compze will tell you so in an exception thought, and you can just paste it in here.
/// Regenerate by running the application when type mappings are missing.
/// </summary>
public sealed class AutoGeneratedCurrentAssemblyTypeMapperForRefactoringSupport
{
   public void MapTypesForCurrentAssembly(Action<Guid, Type> map)
   {
      map(new Guid("f5b3bcfd-ce1a-4c7c-8a1f-1d734a900e57"), typeof(Compze.Abstractions.PersistentEntity<Person>));
      map(new Guid("9d7f4920-6245-4c43-adc9-9eb424f8d475"), typeof(Compze.Tessaging.Abstractions.MessageTypes.Remotable.AtMostOnce.AtMostOnceCommand<MyCommandResult>));
      map(new Guid("69d464a4-29e1-47f1-b9bf-f38a4e483540"), typeof(Compze.Tessaging.Teventive.Aggregate<TestAggregate,IRootEvent,RootEvent>));
      map(new Guid("ff660a66-685d-4900-8b3e-c3932ac53e8c"), typeof(Compze.Tessaging.Teventive.Aggregate<MyAggregate,MyAggregateEvent.IRoot,MyAggregateEvent.Implementation.Root>));
      map(new Guid("c3239a10-3dea-4032-aa95-bbd6fb5cfe4c"), typeof(E1));
      map(new Guid("bda14c40-8d04-446e-9aa9-653fc089d3ef"), typeof(E1[]));
      map(new Guid("394e4abd-5bd4-4400-8bd1-a522ab74b36a"), typeof(E2));
      map(new Guid("d81a7885-30a4-434c-a956-511e628eb5f8"), typeof(E2[]));
      map(new Guid("e926b06f-e6ad-47f3-a625-91dfae296155"), typeof(E3));
      map(new Guid("a7ba9345-a397-49a2-afa2-d63b4da1cb02"), typeof(E3[]));
      map(new Guid("89a08aa4-8d52-4e2f-9e41-3e921995032d"), typeof(E4));
      map(new Guid("a3ba8c66-f95f-46a5-841e-a0ec611f29db"), typeof(E4[]));
      map(new Guid("b9c69034-c1f3-42a7-a691-78eebbd8503f"), typeof(E5));
      map(new Guid("2f78db7a-2994-4ff5-8e92-ea9ee4b822f3"), typeof(E5[]));
      map(new Guid("d2950bd1-dbc9-490d-9981-2ec1b78f3979"), typeof(E6));
      map(new Guid("431953fc-e72d-4021-8df6-eb749c2ab3d2"), typeof(E6[]));
      map(new Guid("f3db5889-9e33-4c58-8a14-481e02208121"), typeof(E7));
      map(new Guid("a0005d5e-6d84-4588-8402-407b02b5e956"), typeof(E7[]));
      map(new Guid("38f2fbfc-92f6-42f6-8e95-caa2a25c9b85"), typeof(E8));
      map(new Guid("1d84cf5a-e7d7-41c3-9486-f5e9c914b7e2"), typeof(E8[]));
      map(new Guid("b6815d73-9a82-4a9d-8841-7573d512c2d7"), typeof(E9));
      map(new Guid("8ce49ab0-8459-44f3-968b-6a3a49934a16"), typeof(E9[]));
      map(new Guid("8802cc90-67ce-4563-b33a-0a624c7d40a6"), typeof(Ec1));
      map(new Guid("163e1ffd-d423-432b-bd4b-5fd7db8d7093"), typeof(Ec1[]));
      map(new Guid("bab28d46-0417-4a0f-90b2-d3daf8ba6ce6"), typeof(Ec2));
      map(new Guid("7420b97a-8bb0-4184-8e24-69de5c6c4005"), typeof(Ec2[]));
      map(new Guid("b8af990f-ba17-4ddd-9f13-0625ae70a438"), typeof(Ec3));
      map(new Guid("b6b95548-b8d0-46ea-b01e-41a78fe24e6e"), typeof(Ec3[]));
      map(new Guid("b6124c9c-b3d1-4fb8-98bc-689b5cba2c99"), typeof(EcAbstract));
      map(new Guid("cb559d1f-87dd-44c8-882f-e1ae7466b379"), typeof(EcAbstract[]));
      map(new Guid("4110c572-66e3-4ce3-82ed-d4970b0104ab"), typeof(Ef));
      map(new Guid("79262922-6796-46c8-b070-3568514ebbd3"), typeof(Ef[]));
      map(new Guid("2755b715-6f35-41a3-aa13-4391e30210b2"), typeof(IRootEvent));
      map(new Guid("03b1a61e-5b42-441a-af5b-87a735c1727d"), typeof(IRootEvent[]));
      map(new Guid("514523a8-03bb-4276-8f10-0278d088157f"), typeof(RootEvent));
      map(new Guid("c49b26f4-1555-4b77-bfa7-ddd8b6eb79cd"), typeof(RootEvent[]));
      map(new Guid("f22618c0-eed1-462e-986d-d4224a74015d"), typeof(TestAggregate));
      map(new Guid("a223fa40-2f5a-4dbc-8bc1-f49aca10191a"), typeof(TestAggregate[]));
      map(new Guid("2415146e-e3fe-404d-9b66-1be8955c8fec"), typeof(Dog));
      map(new Guid("97d6a70d-b062-4198-9f1d-c9742129bbe4"), typeof(Dog[]));
      map(new Guid("406ff939-e2db-4d74-aa1f-14e84cc083e0"), typeof(Person));
      map(new Guid("db1672aa-7787-4003-a309-e804f6103458"), typeof(Person[]));
      map(new Guid("58e2bf8c-ea62-43b9-b226-934b499c6f15"), typeof(User));
      map(new Guid("8f00e1ea-ab08-4695-a44f-5edf74c9ccb4"), typeof(User[]));
      map(new Guid("c8dac68d-956b-400e-b9b5-999255405fd8"), typeof(IMyExactlyOnceEvent));
      map(new Guid("d058b557-9348-41ed-a48c-7a343530fb11"), typeof(IMyExactlyOnceEvent[]));
      map(new Guid("59185f7f-99c4-4d9d-b185-2856eab8f8ed"), typeof(MyAggregate));
      map(new Guid("b6fdbc43-51b0-41a6-b520-ac03c2d61ce8"), typeof(MyAggregate[]));
      map(new Guid("b17d192a-92e4-4392-851c-1e735a6b7003"), typeof(MyAggregateEvent.Created));
      map(new Guid("2b70d07c-afcc-41a3-8764-068df7f9f5d5"), typeof(MyAggregateEvent.Created[]));
      map(new Guid("54344543-5f34-4eea-a9cd-178ff95f3408"), typeof(MyAggregateEvent.Implementation.Created));
      map(new Guid("447dcf11-b870-40d5-80b4-c1f9fedd2ac0"), typeof(MyAggregateEvent.Implementation.Created[]));
      map(new Guid("96101b44-2bdd-4514-8311-79e085c4c987"), typeof(MyAggregateEvent.Implementation.Root));
      map(new Guid("39707d6d-a423-4de7-883d-343223c05cd0"), typeof(MyAggregateEvent.Implementation.Root[]));
      map(new Guid("193aeefd-4022-46e6-8cd0-6f4ae9ea8bbc"), typeof(MyAggregateEvent.Implementation.Updated));
      map(new Guid("0c9803ec-1cb1-4813-8bb6-9b52cadb28b6"), typeof(MyAggregateEvent.Implementation.Updated[]));
      map(new Guid("919053e8-1ac7-4818-b866-b4b58a6e4908"), typeof(MyAggregateEvent.IRoot));
      map(new Guid("59a65d32-8d62-4bf6-8193-cb85db17bb4d"), typeof(MyAggregateEvent.IRoot[]));
      map(new Guid("3e31f3a8-deec-4519-9df2-e587284761fe"), typeof(MyAggregateEvent.Updated));
      map(new Guid("c8855cd5-3e75-44ae-a9df-9bb2b3263455"), typeof(MyAggregateEvent.Updated[]));
      map(new Guid("8e07e2a9-d639-40a9-b5ec-493a6405d619"), typeof(MyAtMostOnceCommandWithResult));
      map(new Guid("660350d1-f36a-481f-b8fa-762cd5dba92c"), typeof(MyAtMostOnceCommandWithResult[]));
      map(new Guid("e39c0bc8-2ffd-48f8-a98a-8cafa5db1691"), typeof(MyCreateAggregateCommand));
      map(new Guid("04142c17-c7f1-4800-8ec6-da19ec800c14"), typeof(MyCreateAggregateCommand[]));
      map(new Guid("1a0a0918-2674-422e-b371-552cac4307fc"), typeof(MyExactlyOnceCommand));
      map(new Guid("c52c2888-210c-4302-ab7e-6615116a2c0f"), typeof(MyExactlyOnceCommand[]));
      map(new Guid("4628436c-cf4f-4499-9431-183348d3e214"), typeof(MyExactlyOnceEvent));
      map(new Guid("af9bb07a-dde5-4aef-b94f-7dbc5d59e8fd"), typeof(MyExactlyOnceEvent[]));
      map(new Guid("1688aa29-83f1-44b5-b67f-c57aab8f926a"), typeof(MyQuery));
      map(new Guid("20caac22-4212-473a-9717-85dd28ba034f"), typeof(MyQuery[]));
      map(new Guid("9dd2acf3-0fd7-4986-b016-173efd995604"), typeof(MyUpdateAggregateCommand));
      map(new Guid("7f9fd127-8175-473e-a579-f08dceb2917b"), typeof(MyUpdateAggregateCommand[]));
   }
}
