// <auto-generated>
// This file was generated by Compze.InternalizedSourceReferences.
// Changes to this file will be overwritten.
// </auto-generated>
#nullable enable
using System;

namespace Compze.Utilities.SystemCE.ThreadingCE.ResourceAccess;

internal class AwaitingConditionTimeoutException : Exception
{
   public AwaitingConditionTimeoutException(AwaitingConditionTimeoutException parent, string message) : base(message, innerException: parent)
   { }

   public AwaitingConditionTimeoutException() : base("Timed out waiting for condition to become true.") {}
}
