// <auto-generated>
// This file was generated by Compze.InternalizedSourceReferences.
// Changes to this file will be overwritten.
// </auto-generated>
#nullable enable
using Compze.Functional;
using System;

namespace Compze.Utilities.SystemCE.ThreadingCE.ResourceAccess;

internal partial interface IMonitorCE
{
   unit Await(Func<bool> condition, TimeSpan? waitTimeout = null, TimeSpan? lockTimeout = null)
   {
      using var readLock = TakeReadLockWhen(condition, waitTimeout: waitTimeout, lockTimeout: lockTimeout);
      return unit.Value;
   }

   bool TryAwait(Func<bool> condition, TimeSpan? waitTimeout = null, TimeSpan? lockTimeout = null)
   {
      using var readLock = TryTakeReadLockWhen(condition, waitTimeout: waitTimeout, lockTimeout: lockTimeout);
      return readLock != null;
   }
}
