using Compze.Abstractions.Public;
using Compze.Tessaging.Teventive.TeventStore.Public;
using Compze.Tessaging.Teventive.TeventStore.QueryModels;
using Compze.Tessaging.Teventive.TeventStore.QueryModels.Generators.Public;
using Compze.Hosting.Testing;
using Compze.Internals.Testing;
using Compze.Tests.Common;
using Compze.Tests.Common.Wiring;
using Compze.Tessaging.Teventive.TeventStore.QueryModels.Generators;
using Compze.Tessaging.Teventive.TeventStore.Wiring;
using Compze.Tests.Infrastructure;
using Compze.Tests.Infrastructure.XUnit;
using Compze.Tests.Integration.CQRS.QueryModels.AutoGenerated.Domain;
using Compze.Tests.Integration.CQRS.QueryModels.AutoGenerated.Domain.UI.QueryModels;
using Compze.DependencyInjection;
using Compze.DependencyInjection.Abstractions;
using Compze.Internals.SystemCE.TransactionsCE;
using Compze.Must;
using Compze.Teventive.Public.Taggregates.BaseClasses.Public;
using Compze.Teventive.Public.Taggregates.Tevents.Public;
using JetBrains.Annotations;

// ReSharper disable InconsistentNaming

// ReSharper disable ImplicitlyCapturedClosure
#pragma warning disable CA1812 //Uninstantiated class (used via reflection)

namespace Compze.Tests.Integration.CQRS.QueryModels.AutoGenerated
{
   public class QueryModelGeneratingQueryModelReaderTests : UniversalTestBase
   {
      readonly IDependencyInjectionContainer _container;

      public QueryModelGeneratingQueryModelReaderTests()
      {
         _container = TestEnv.DIContainer.CreateContainerForTesting(mapper => mapper.RegisterIntegrationTestTypeMappings(), register =>
         {
            register.TeventStore("nonsense");
            register.Register(
               Scoped.For<IQueryModelReader, IVersioningQueryModelReader>().CreatedBy((AccountQueryModelGenerator queryModelGenerator) => new QueryModelGeneratingQueryModelReader([queryModelGenerator])),
               Scoped.For<AccountQueryModelGenerator>().CreatedBy((ITeventStoreReader teventStoreReader) => new AccountQueryModelGenerator(teventStoreReader))
            );
         });
      }

      protected override async Task DisposeAsyncInternal() => await _container.DisposeAsync();

      [PCT] public void ThrowsExceptionIfInstanceDoesNotExist()
      {
         using var scope = _container.BeginScope();
         var reader = scope.Resolve<IQueryModelReader>();
         reader.Invoking(me => me.Get<MyAccountQueryModel>(new EntityId()))
               .Must().Throw<Exception>();
      }

      [PCT] public void CanFetchQueryModelAfterTaggregateHasBeenCreated()
      {
         using var scope = _container.BeginScope();
         var taggregates = scope.Resolve<ITeventStoreUpdater>();
         var accountId = new TaggregateId();

         var registered = TransactionScopeCe.Execute(() => MyAccount.Register(taggregates, accountId, "email", "password"));

         registered.Email.Must().Be("email");
         registered.Password.Must().Be("password");

         var reader = scope.Resolve<IQueryModelReader>();
         var loadedModel = reader.Get<MyAccountQueryModel>(registered.Id);

         loadedModel.Must().NotBeNull();
         loadedModel.Id.Must().Be(accountId);
         loadedModel.Email.Must().Be(registered.Email);
         loadedModel.Password.Must().Be(registered.Password);
      }

      [PCT] public void ThrowsExceptionWhenTryingToFetchDeletedEntity()
      {
         MyAccount registered;
         {
            using var scope1 = _container.BeginScope();
            var taggregates = scope1.Resolve<ITeventStoreUpdater>();
            var accountId = new TaggregateId();

            registered = TransactionScopeCe.Execute(() => MyAccount.Register(taggregates, accountId, "email", "password"));

            var reader = scope1.Resolve<IQueryModelReader>();
            reader.Get<MyAccountQueryModel>(registered.Id); //Here it exists
         }

         {
            using var scope2 = _container.BeginScope();
            TransactionScopeCe.Execute(() => scope2.Resolve<ITeventStoreUpdater>().Get<MyAccount>(registered.Id).Delete());
         }

         {
            using var scope3 = _container.BeginScope();
            var reader2 = scope3.Resolve<IQueryModelReader>();
            reader2.Invoking(me => me.Get<MyAccountQueryModel>(registered.Id)).Must().Throw<Exception>();
         }
      }

      [PCT] public void ReturnsUpdatedDataAfterTransactionHasCommitted()
      {
         MyAccount registered;
         {
            using var scope1 = _container.BeginScope();
            var accountId = new TaggregateId();

            var taggregates = scope1.Resolve<ITeventStoreUpdater>();
            registered = TransactionScopeCe.Execute(() => MyAccount.Register(taggregates, accountId, "email", "password"));

            scope1.Resolve<IQueryModelReader>()
                  .Get<MyAccountQueryModel>(registered.Id); //Make sure we read it once so caches etc get involved.
         }

         {
            using var scope2 = _container.BeginScope();
            TransactionScopeCe.Execute(() => scope2.Resolve<ITeventStoreUpdater>().Get<MyAccount>(registered.Id).ChangeEmail("newEmail"));
         }

         {
            using var scope3 = _container.BeginScope();
            var loadedModel = scope3.Resolve<IQueryModelReader>()
                                    .Get<MyAccountQueryModel>(registered.Id);

            loadedModel.Must().NotBeNull();
            loadedModel.Email.Must().Be("newEmail");
         }
      }

      [PCT] public void CanReturnPreviousVersionsOfQueryModel()
      {
         MyAccount? registered;

         {
            using var scope1 = _container.BeginScope();
            var accountId = new TaggregateId();

            var taggregates = scope1.Resolve<ITeventStoreUpdater>();
            registered = TransactionScopeCe.Execute(() => MyAccount.Register(taggregates, accountId, "originalEmail", "password"));

            scope1.Resolve<IVersioningQueryModelReader>()
                  .GetVersion<MyAccountQueryModel>(registered.Id, registered.Version); //Make sure we read it once so caches etc get involved.
         }

         {
            using var scope2 = _container.BeginScope();
            TransactionScopeCe.Execute(() =>
            {
               if(!scope2.Resolve<ITeventStoreUpdater>().TryGet(registered.Id, out registered))
               {
                  throw new Exception("huh?");
               }
               registered.ChangeEmail("newEmail1");
               registered.ChangeEmail("newEmail2");
               registered.ChangeEmail("newEmail3");
            });
         }

         {
            using var scope3 = _container.BeginScope();
            var loadedModel = scope3.Resolve<IVersioningQueryModelReader>()
                                    .Get<MyAccountQueryModel>(registered.Id);

            loadedModel.Must().NotBeNull();
            loadedModel.Email.Must().Be("newEmail3");

            scope3.Resolve<IVersioningQueryModelReader>()
                  .GetVersion<MyAccountQueryModel>(registered.Id, registered.Version - 1)
                  .Email.Must().Be("newEmail2");

            scope3.Resolve<IVersioningQueryModelReader>()
                  .GetVersion<MyAccountQueryModel>(registered.Id, registered.Version - 2)
                  .Email.Must().Be("newEmail1");

            scope3.Resolve<IVersioningQueryModelReader>()
                  .GetVersion<MyAccountQueryModel>(registered.Id, registered.Version - 3)
                  .Email.Must().Be("originalEmail");
         }
      }
   }

   namespace Domain
   {
      namespace UI
      {
         namespace QueryModels
         {
            [UsedImplicitly] public class MyAccountQueryModel : ISingleTaggregateQueryModel
            {
               public EntityId<Guid> Id { get; private set; } = new EntityId();
               internal string Email { get; set; } = "";
               internal string Password { get; set; } = "";

               public void SetId(TaggregateId id) => Id = id;
            }

            class AccountQueryModelGenerator : SingleTaggregateQueryModelGenerator<AccountQueryModelGenerator, MyAccountQueryModel, IAccountTevent, ITeventStoreReader>
            {
               public AccountQueryModelGenerator(ITeventStoreReader session) : base(session)
               {
                  RegisterHandlers()
                    .For<IAccountTevent.PropertyUpdated.Email>(e => Model!.Email = e.Email)
                    .For<IAccountTevent.PropertyUpdated.Password>(e => Model!.Password = e.Password);
               }
            }
         }
      }

      class MyAccount : Taggregate<MyAccount, IAccountTevent, AccountTevent, IAccountTevent<IAccountTevent>, AccountTevent<AccountTevent>>
      {
         MyAccount()
         {
            RegisterTeventAppliers()
              .For<IAccountTevent.PropertyUpdated.Email>(e => Email = e.Email)
              .For<IAccountTevent.PropertyUpdated.Password>(e => Password = e.Password)
              .For<IAccountTevent.Deleted>(_ => {});
         }

         public string Email { get; private set; } = "";
         public string Password { get; private set; } = "";

         public void ChangeEmail(string newEmail) => Publish(new AccountTevent.EmailChanged(newEmail));

         public static MyAccount Register(ITeventStoreUpdater taggregates, TaggregateId accountId, string email, string password)
         {
            var registered = new MyAccount();
            registered.Publish(new AccountTevent.AccountRegisteredTevent(accountId, email, password));
            taggregates.Save(registered);
            return registered;
         }

         public void Delete() => Publish(new AccountTevent.Deleted());
      }

      interface IAccountTevent<out T> : ITaggregateIdentifyingTevent<T> where T : IAccountTevent;

      interface IAccountTevent : ITaggregateTevent
      {
         internal interface IAccountRegisteredTevent : ITaggregateCreatedTevent,
                                                       PropertyUpdated.Email,
                                                       PropertyUpdated.Password;

         internal interface IEmailChanged : PropertyUpdated.Email;

         internal interface Deleted : IAccountTevent,
                                      ITaggregateDeletedTevent;

         internal interface PropertyUpdated
         {
            public interface Email : IAccountTevent
            {
               string Email { get; }
            }

            public interface Password : IAccountTevent
            {
               string Password { get; }
            }
         }
      }

      // ReSharper disable once ClassNeverInstantiated.Global
      class AccountTevent<T>(T tevent) : TaggregateIdentifyingTevent<T>(tevent), IAccountTevent<T> where T : IAccountTevent;

      abstract class AccountTevent : TaggregateTevent, IAccountTevent
      {
         AccountTevent() {}
         AccountTevent(TaggregateId taggregateId) : base(taggregateId) {}

         public class AccountRegisteredTevent(TaggregateId accountId, string email, string password) : AccountTevent(accountId), IAccountTevent.IAccountRegisteredTevent
         {
            public string Email { get; private set; } = email;
            public string Password { get; private set; } = password;
         }

         public class EmailChanged(string newEmail) : AccountTevent, IAccountTevent.IEmailChanged
         {
            public string Email { get; private set; } = newEmail;
         }

         public class Deleted : AccountTevent, IAccountTevent.Deleted;
      }
   }
}
