using Compze.Abstractions;
using Compze.DependencyInjection;
using Compze.DependencyInjection.Abstractions;
using Compze.Hosting.Testing;
using Compze.Internals.SystemCE.TransactionsCE;
using Compze.Internals.Testing;
using Compze.Must;
using Compze.Tests.Common.Wiring;
using Compze.Tests.Infrastructure;
using Compze.Tests.Infrastructure.XUnit;
using Compze.Tests.Integration.CQRS.QueryModels.AutoGenerated.Domain;
using Compze.Tests.Integration.CQRS.QueryModels.AutoGenerated.Domain.UI.QueryModels;
using Compze.Teventive.TeventStore.Abstractions;
using Compze.Teventive.TeventStore.Abstractions.QueryModels.Generators;
using Compze.Teventive.TeventStore.QueryModels.Generators;
using Compze.Teventive.TeventStore.Wiring;

// ReSharper disable InconsistentNaming

namespace Compze.Tests.Integration.CQRS.QueryModels.AutoGenerated;

public class When_asked_for_a_query_model_by_key : UniversalTestBase
{
   readonly IDependencyInjectionContainer _container;

   public When_asked_for_a_query_model_by_key()
   {
      _container = TestEnv.DIContainer.CreateContainerForTesting(registrar => registrar.RequireIntegrationTestTypeMappings(), register =>
      {
         register.TeventStore("nonsense");
         register.Register(
            Scoped.For<IQueryModelReader, IVersioningQueryModelReader>().CreatedBy((AccountQueryModelGenerator queryModelGenerator) => new QueryModelGeneratingQueryModelReader([queryModelGenerator])),
            Scoped.For<AccountQueryModelGenerator>().CreatedBy((ITeventStoreReader teventStoreReader) => new AccountQueryModelGenerator(teventStoreReader))
         );
      });
   }

   protected override async Task DisposeAsyncInternal() => await _container.DisposeAsync();

   [PCT] public void TryGet_returns_false_when_no_taggregate_history_backs_the_key()
   {
      using var scope = _container.BeginScope();
      scope.Resolve<IQueryModelReader>().TryGet<MyAccountQueryModel>(new EntityId(), out _).Must().BeFalse();
   }

   [PCT] public void TryGet_returns_true_and_the_generated_model_once_the_account_taggregate_is_registered()
   {
      using var scope = _container.BeginScope();
      var taggregates = scope.Resolve<ITeventStoreUpdater>();
      var registered = TransactionScopeCe.Execute(() => MyAccount.Register(taggregates, new TaggregateId(), "email", "password"));

      scope.Resolve<IQueryModelReader>().TryGet<MyAccountQueryModel>(registered.Id, out var model).Must().BeTrue();
      model!.Email.Must().Be("email");
   }

   [PCT] public void TryGetVersion_returns_false_when_no_taggregate_history_backs_the_key()
   {
      using var scope = _container.BeginScope();
      scope.Resolve<IVersioningQueryModelReader>().TryGetVersion<MyAccountQueryModel>(new EntityId(), 1, out _).Must().BeFalse();
   }

   [PCT] public void TryGetVersion_returns_the_model_as_of_the_requested_taggregate_version()
   {
      MyAccount registered;
      {
         using var registerScope = _container.BeginScope();
         var taggregates = registerScope.Resolve<ITeventStoreUpdater>();
         registered = TransactionScopeCe.Execute(() => MyAccount.Register(taggregates, new TaggregateId(), "originalEmail", "password"));
      }

      {
         using var changeScope = _container.BeginScope();
         TransactionScopeCe.Execute(() => changeScope.Resolve<ITeventStoreUpdater>().Get<MyAccount>(registered.Id).ChangeEmail("newEmail"));
      }

      using var readScope = _container.BeginScope();
      var reader = readScope.Resolve<IVersioningQueryModelReader>();

      reader.TryGetVersion<MyAccountQueryModel>(registered.Id, registered.Version + 1, out var latest).Must().BeTrue();
      latest!.Email.Must().Be("newEmail");

      reader.TryGetVersion<MyAccountQueryModel>(registered.Id, registered.Version, out var original).Must().BeTrue();
      original!.Email.Must().Be("originalEmail");
   }
}
