using Compze.Core.Tessaging.Teventive.Public;
using Compze.Core.Tessaging.Teventive.Public.Taggregates.Tevents.Public;

// ReSharper disable All
namespace Compze.Core;

#pragma warning disable IDE1006,IDE0001,IDE0002,IDE0003,IDE0004,IDE0005,IDE0055,CA1050,CA1707,CA1716

/// <summary>
/// This file is automatically generated. Compze will automatically figure out most types that need to go in here, but some types you may need to add yourself.
/// Compze will tell you so in an exception thought, and you can just paste it in here.
/// Regenerate by running the application when type mappings are missing.
/// </summary>
public sealed class AutoGeneratedCurrentAssemblyTypeMapperForRefactoringSupport
{
   public void MapTypesForCurrentAssembly(Action<string, Type> map)
   {
      map("32bbb393-64ab-42af-8edd-630d73d697a5", typeof(TaggregateTevent));
      map("21d6e19d-bdc6-42e8-ab58-99da2540c3fe", typeof(TaggregateTevent[]));
      map("af07f49c-12c6-4ea9-abf1-45fa2088515b", typeof(ITaggregateCreatedTevent));
      map("8b25fcf2-3287-4a58-a716-1690124f5258", typeof(ITaggregateCreatedTevent[]));
      map("bc662519-21b4-41b8-bce6-3714da82b1cc", typeof(ITaggregateDeletedTevent));
      map("64211019-e834-4a55-9092-a03bb6dde6b0", typeof(ITaggregateDeletedTevent[]));
      map("a1503d7d-51c0-4fff-ad3b-c7090f1e4905", typeof(ITaggregateTevent));
      map("89d2e657-0361-4384-b252-60c1af32da56", typeof(ITaggregateTevent[]));
      map("befc4021-9e9c-4d40-842c-9878ce2c9ee3", typeof(IMutableTaggregateTevent));
      map("d742bc2f-d8d3-4ff2-be80-e178c924ca97", typeof(IMutableTaggregateTevent[]));
   }
}
