using Compze.Core.Tessaging.Teventive.Public;
using Compze.Core.Tessaging.Teventive.Public.Taggregates.Tevents.Public;

// ReSharper disable All
namespace Compze.Core;

#pragma warning disable IDE1006,IDE0001,IDE0002,IDE0003,IDE0004,IDE0005,IDE0055,CA1050,CA1707,CA1716

/// <summary>
/// This file is automatically generated. Compze will automatically figure out most types that need to go in here, but some types you may need to add yourself.
/// Compze will tell you so in an exception thought, and you can just paste it in here.
/// Regenerate by running the application when type mappings are missing.
/// </summary>
public sealed class AutoGeneratedCurrentAssemblyTypeMapperForRefactoringSupport
{
   public void MapTypesForCurrentAssembly(Action<string, Type> map)
   {
      map("32bbb393-64ab-42af-8edd-630d73d697a5", typeof(TaggregateTevent));
      map("af07f49c-12c6-4ea9-abf1-45fa2088515b", typeof(ITaggregateCreatedTevent));
      map("bc662519-21b4-41b8-bce6-3714da82b1cc", typeof(ITaggregateDeletedTevent));
      map("a1503d7d-51c0-4fff-ad3b-c7090f1e4905", typeof(ITaggregateTevent));
      map("befc4021-9e9c-4d40-842c-9878ce2c9ee3", typeof(IMutableTaggregateTevent));

      map("e1f2a3b4-c5d6-4e7f-8091-a2b3c4d5e6f7", typeof(Compze.Core.Tessaging.Teventive.Public.Taggregates.BaseClasses.Public.Taggregate<,,,,>));
      map("f2a3b4c5-d6e7-4f80-91a2-b3c4d5e6f7a8", typeof(Compze.Core.Tessaging.Transport.Internal.EndPointAddress));
   }
}
