using System;

// ReSharper disable All
namespace Compze.Core;

#pragma warning disable IDE1006,IDE0001,IDE0002,IDE0003,IDE0004,IDE0005,IDE0055,CA1050,CA1707,CA1716

/// <summary>
/// This file is automatically generated. Compze will automatically figure out most types that need to go in here, but some types you may need to add yourself.
/// Compze will tell you so in an exception thought, and you can just paste it in here.
/// Regenerate by running the application when type mappings are missing.
/// </summary>
public sealed class AutoGeneratedCurrentAssemblyTypeMapperForRefactoringSupport
{
   public void MapTypesForCurrentAssembly(Action<string, Type> map)
   {
      map("befc4021-9e9c-4d40-842c-9878ce2c9ee3", typeof(Compze.Core.Tessaging.Teventive.Public.IMutableTaggregateTevent));
      map("c267e6f6-1972-4b4d-8c72-519c2ab96a97", typeof(Compze.Core.Tessaging.Teventive.Public.ITaggregate`1));
      map("1fe1eb57-c6b4-498a-b179-ab15c05f88f4", typeof(Compze.Core.Tessaging.Teventive.Public.Taggregates.BaseClasses.Public.Taggregate`5));
      map("8bd3e0ff-e8e9-4a74-8f2f-c012e43f9c37", typeof(Compze.Core.Tessaging.Teventive.Public.Taggregates.BaseClasses.Public.TaggregateIdentifyingTevent`1));
      map("af07f49c-12c6-4ea9-abf1-45fa2088515b", typeof(Compze.Core.Tessaging.Teventive.Public.Taggregates.Tevents.Public.ITaggregateCreatedTevent));
      map("bc662519-21b4-41b8-bce6-3714da82b1cc", typeof(Compze.Core.Tessaging.Teventive.Public.Taggregates.Tevents.Public.ITaggregateDeletedTevent));
      map("a7adf038-88fa-4faf-94f6-e998c31c8af9", typeof(Compze.Core.Tessaging.Teventive.Public.Taggregates.Tevents.Public.ITaggregateIdentifyingTevent`1));
      map("a1503d7d-51c0-4fff-ad3b-c7090f1e4905", typeof(Compze.Core.Tessaging.Teventive.Public.Taggregates.Tevents.Public.ITaggregateTevent));
      map("32bbb393-64ab-42af-8edd-630d73d697a5", typeof(Compze.Core.Tessaging.Teventive.Public.Taggregates.Tevents.Public.TaggregateTevent));
   }
}
