using System;

namespace Compze.Tests.Unit.Internals;

// ReSharper disable All
#pragma warning disable IDE1006,IDE0001,IDE0002,IDE0003,IDE0004,IDE0005,IDE0055,CA1050,CA1707,CA1716

/// <summary>
/// This file is automatically generated. Do not edit manually.
/// Regenerate by running the application when type mappings are missing.
/// </summary>
public sealed class AutoGeneratedCurrentAssemblyTypeMapperForRefactoringSupport
{
      public void MapTypesForCurrentAssembly(Action<Guid, Type> map)
   {
      map(new Guid("f6af666b-ebf1-449b-9487-9cae1d4f6907"), typeof(Compze.Tests.Unit.Internals.Serialization.NewtonSoftEventStoreEventSerializerTests.TestEvent));
      map(new Guid("0758dd54-af1b-421d-92b7-75ce9517484f"), typeof(Compze.Tests.Unit.Internals.Serialization.NewtonSoftEventStoreEventSerializerTests.TestEvent[]));
      map(new Guid("08640e0c-699b-4b1e-82e4-5d06bd10e5db"), typeof(Compze.Tests.Unit.Internals.Tessaging.MessageTypeInspector_throws_MessageTypeDesignViolationException_if_.Inspecting_type_for_sending_and_.AtMostOnceCommandSettingMessageIdInDefaultConstructor));
      map(new Guid("f4f1c148-389e-488f-88bc-ec6bf4f89e3b"), typeof(Compze.Tests.Unit.Internals.Tessaging.MessageTypeInspector_throws_MessageTypeDesignViolationException_if_.Inspecting_type_for_sending_and_.AtMostOnceCommandSettingMessageIdInDefaultConstructor[]));
   }
}
