using System;
using System.Collections.Generic;
using System.Linq;
using System.Reflection;
using Compze.Utilities.SystemCE;
using Newtonsoft.Json;
using Newtonsoft.Json.Serialization;

namespace Compze.Utilities.Testing.Fluent.Serialization;

abstract class MemberFilteringContractResolver : DefaultContractResolver
{
   protected override JsonProperty CreateProperty(MemberInfo member, MemberSerialization memberSerialization)
   {
      var property = base.CreateProperty(member, memberSerialization);
      property.Readable = true;
      property.Writable = true;
      return property;
   }

   internal IList<JsonProperty> CreatePropertiesInternal(Type type, MemberSerialization memberSerialization)
      => CreateProperties(type, memberSerialization);

   protected override IList<JsonProperty> CreateProperties(Type type, MemberSerialization memberSerialization)
   {
      var allProperties = type.GetProperties(BindingFlags.Public | BindingFlags.NonPublic | BindingFlags.Instance)
                              .Where(ShouldInclude)
                              .GroupBy(p => p.Name)
                              .Select(g => g.First()); // Take the most derived property when there are multiple with same name

      var allFields = type.GetFields(BindingFlags.Public | BindingFlags.NonPublic | BindingFlags.Instance)
                          .Where(ShouldInclude)
                          .Where(f => !IsAutoGeneratedBackingField(f));

      return allProperties.Cast<MemberInfo>()
                          .Concat(allFields)
                          .Select(m => CreateProperty(m, memberSerialization))
                          .OrderBy(p => p.PropertyName) // Ensure deterministic order
                          .ToList();
   }

   static bool IsAutoGeneratedBackingField(FieldInfo field) =>
      field.Name.StartsWith('<') && field.Name.ContainsOrdinal(">k__BackingField");

   protected abstract bool ShouldInclude(PropertyInfo property);
   protected abstract bool ShouldInclude(FieldInfo field);
}
