using System.Text.RegularExpressions;

namespace Compze.InternalizedSourceReferences;

public static partial class SourceRewriter
{
   public const string AutoGeneratedHeader =
      """
      // <auto-generated>
      // This file was generated by Compze.InternalizedSourceReferences.
      // Changes to this file will be overwritten.
      // </auto-generated>
      #nullable enable

      """;

   static readonly Regex PublicTypeDeclarationPattern = PublicTypeDeclarationRegex();

   public static string MakeTypesInternal(string source)
   {
      var rewritten = PublicTypeDeclarationPattern.Replace(source, match =>
      {
         var whitespace = match.Groups[1].Value;
         var modifiers = match.Groups[2].Value;
         var typeKeyword = match.Groups[3].Value;
         return $"internal{whitespace}{modifiers}{typeKeyword}";
      });

      return AutoGeneratedHeader + rewritten;
   }

   static readonly string[] ExcludedDirectories = ["bin", "obj", "InternalizedSource"];

   public static void RewriteDirectory(string inputDirectory, string outputDirectory) =>
      RewriteDirectories([inputDirectory], outputDirectory);

   public static void RewriteDirectories(string[] inputDirectories, string outputDirectory)
   {
      var writtenFiles = new HashSet<string>(StringComparer.OrdinalIgnoreCase);

      foreach(var inputDirectory in inputDirectories)
      {
         foreach(var inputFile in Directory.EnumerateFiles(inputDirectory, "*.cs", SearchOption.AllDirectories))
         {
            var relativePath = Path.GetRelativePath(inputDirectory, inputFile);

            if(IsInExcludedDirectory(relativePath))
               continue;

            var outputFile = Path.Combine(outputDirectory, relativePath);
            writtenFiles.Add(outputFile);

            Directory.CreateDirectory(Path.GetDirectoryName(outputFile)!);

            var source = File.ReadAllText(inputFile);
            var rewritten = MakeTypesInternal(source);

            if(File.Exists(outputFile) && File.ReadAllText(outputFile) == rewritten)
               continue;

            File.WriteAllText(outputFile, rewritten);
         }
      }

      // Remove stale output files that no longer have a corresponding input
      if(Directory.Exists(outputDirectory))
      {
         foreach(var existingFile in Directory.EnumerateFiles(outputDirectory, "*.cs", SearchOption.AllDirectories))
         {
            if(!writtenFiles.Contains(existingFile))
               File.Delete(existingFile);
         }
      }
   }

   [GeneratedRegex(
      @"public(\s+)((?:(?:static|abstract|sealed|partial|unsafe|readonly|ref|file|new)\s+)*)(\bclass\b|\binterface\b|\bstruct\b|\benum\b|\brecord\b|\bdelegate\b)",
      RegexOptions.Compiled)]
   private static partial Regex PublicTypeDeclarationRegex();

   static bool IsInExcludedDirectory(string relativePath)
   {
      var firstSegment = relativePath.Split(Path.DirectorySeparatorChar, Path.AltDirectorySeparatorChar)[0];
      return ExcludedDirectories.Contains(firstSegment, StringComparer.OrdinalIgnoreCase);
   }
}
