using System;
using Compze.Abstractions.Tessaging.Public;
using Compze.Abstractions.Tessaging.Teventive.EventStore.Public;
using Compze.Abstractions.Tessaging.Teventive.Public;

// ReSharper disable All
namespace Compze.Abstractions;

#pragma warning disable IDE1006,IDE0001,IDE0002,IDE0003,IDE0004,IDE0005,IDE0055,CA1050,CA1707,CA1716

/// <summary>
/// This file is automatically generated. Compze will automatically figure out most types that need to go in here, but some types you may need to add yourself.
/// Compze will tell you so in an exception thought, and you can just paste it in here.
/// Regenerate by running the application when type mappings are missing.
/// </summary>
public sealed class AutoGeneratedCurrentAssemblyTypeMapperForRefactoringSupport
{
   public void MapTypesForCurrentAssembly(Action<Guid, Type> map)
   {
      map(new Guid("0d68a831-87c0-4d05-8e52-bf063d51b56d"), typeof(IExactlyOnceTevent));
      map(new Guid("f0bf0312-1300-4ba9-8f0d-eaf460b52337"), typeof(IExactlyOnceTevent[]));
      map(new Guid("887aad71-52f3-46f8-a26a-e2886941758d"), typeof(IRemotableTevent));
      map(new Guid("c55a6157-dcc8-4928-a48c-28b2c6f8bd49"), typeof(IRemotableTevent[]));
      map(new Guid("f1581159-4ff1-4df5-b10b-0680552111b1"), typeof(TessageTypes.Remotable.AtMostOnce.AtMostOnceHypermediaTommand));
      map(new Guid("ea3be0f8-dbae-4353-87cf-6b4f0294fb5f"), typeof(TessageTypes.Remotable.AtMostOnce.AtMostOnceHypermediaTommand[]));
      map(new Guid("fcf83cc4-de51-4b17-ab44-741c2d34feb2"), typeof(TessageTypes.Remotable.ExactlyOnce.Tommand));
      map(new Guid("308ca648-8424-4c81-adf1-ad90123c9240"), typeof(TessageTypes.Remotable.ExactlyOnce.Tommand[]));
      map(new Guid("32bbb393-64ab-42af-8edd-630d73d697a5"), typeof(AggregateTevent));
      map(new Guid("21d6e19d-bdc6-42e8-ab58-99da2540c3fe"), typeof(AggregateTevent[]));
      map(new Guid("af07f49c-12c6-4ea9-abf1-45fa2088515b"), typeof(IAggregateCreatedTevent));
      map(new Guid("8b25fcf2-3287-4a58-a716-1690124f5258"), typeof(IAggregateCreatedTevent[]));
      map(new Guid("bc662519-21b4-41b8-bce6-3714da82b1cc"), typeof(IAggregateDeletedTevent));
      map(new Guid("64211019-e834-4a55-9092-a03bb6dde6b0"), typeof(IAggregateDeletedTevent[]));
      map(new Guid("a1503d7d-51c0-4fff-ad3b-c7090f1e4905"), typeof(IAggregateTevent));
      map(new Guid("89d2e657-0361-4384-b252-60c1af32da56"), typeof(IAggregateTevent[]));
      map(new Guid("befc4021-9e9c-4d40-842c-9878ce2c9ee3"), typeof(IMutableAggregateTevent));
      map(new Guid("d742bc2f-d8d3-4ff2-be80-e178c924ca97"), typeof(IMutableAggregateTevent[]));

   }
}
