using System;
using System.Threading.Tasks;
using Compze.Abstractions.Internal.Refactoring.Naming;
using Compze.Abstractions.Internal.Time;
using Compze.Tessaging.Hosting.Testing.DependencyInjection;
using Compze.Tessaging.Teventive;
using Compze.Tessaging.Teventive.Abstractions;
using Compze.Tessaging.Teventive.EventStore.Abstractions;
using Compze.Tessaging.Teventive.EventStore.DependencyInjection;
using Compze.Tessaging.Teventive.EventStore.Query.Models.Generators;
using Compze.Testing;
using Compze.Tests.Integration.CQRS.Query.Models.AutoGenerated.Domain;
using Compze.Tests.Integration.CQRS.Query.Models.AutoGenerated.Domain.UI.QueryModels;
using Compze.Utilities.DependencyInjection;
using Compze.Utilities.DependencyInjection.Abstractions;
using Compze.Utilities.SystemCE.TransactionsCE;
using FluentAssertions;
using JetBrains.Annotations;
using NUnit.Framework;

// ReSharper disable ImplicitlyCapturedClosure

namespace Compze.Tests.Integration.CQRS.Query.Models.AutoGenerated
{
   public class QueryModelGeneratingQueryModelReaderTests(string pluggableComponentsCombination) : DuplicateByPluggableComponentTest(pluggableComponentsCombination)
   {
      IServiceLocator _serviceLocator;

      [SetUp] public void CreateContainer()
      {
         _serviceLocator = TestingContainerFactory.CreateServiceLocatorForTesting(register =>
         {
            register.EventStore("nonsense");
            register.Register(
               Scoped.For<IQueryModelReader, IVersioningQueryModelReader>().CreatedBy((AccountQueryModelGenerator queryModelGenerator) => new QueryModelGeneratingQueryModelReader([queryModelGenerator])),
               Scoped.For<AccountQueryModelGenerator>().CreatedBy((IEventStoreReader eventStoreReader) => new AccountQueryModelGenerator(eventStoreReader))
            );
         });
      }

      [TearDown] public async Task TearDownTask() => await _serviceLocator.DisposeAsync();

      [Test] public void ThrowsExceptionIfInstanceDoesNotExist()
      {
         using(_serviceLocator.BeginScope())
         {
            var reader = _serviceLocator.Resolve<IQueryModelReader>();
            reader.Invoking(me => me.Get<MyAccountQueryModel>(Guid.NewGuid()))
                  .Should().Throw<Exception>();
         }
      }

      [Test] public void CanFetchQueryModelAfterAggregateHasBeenCreated()
      {
         using(_serviceLocator.BeginScope())
         {
            var aggregates = _serviceLocator.Resolve<IEventStoreUpdater>();
            var accountId = Guid.Parse("00000000-0000-0000-0000-000000000001");

            var registered = TransactionScopeCe.Execute(() => MyAccount.Register(aggregates, accountId, "email", "password"));

            registered.Email.Should().Be("email");
            registered.Password.Should().Be("password");

            var reader = _serviceLocator.Resolve<IQueryModelReader>();
            var loadedModel = reader.Get<MyAccountQueryModel>(registered.Id);

            loadedModel.Should().NotBe(null);
            loadedModel.Id.Should().Be(accountId);
            loadedModel.Email.Should().Be(registered.Email);
            loadedModel.Password.Should().Be(registered.Password);
         }
      }

      [Test] public void ThrowsExceptionWhenTryingToFetchDeletedEntity()
      {
         MyAccount registered;
         using(_serviceLocator.BeginScope())
         {
            var aggregates = _serviceLocator.Resolve<IEventStoreUpdater>();
            var accountId = Guid.Parse("00000000-0000-0000-0000-000000000001");

            registered = TransactionScopeCe.Execute(() => MyAccount.Register(aggregates, accountId, "email", "password"));

            var reader = _serviceLocator.Resolve<IQueryModelReader>();
            reader.Get<MyAccountQueryModel>(registered.Id); //Here it exists
         }

         using(_serviceLocator.BeginScope())
         {
            TransactionScopeCe.Execute(() => _serviceLocator.Resolve<IEventStoreUpdater>().Get<MyAccount>(registered.Id).Delete());
         }

         using(_serviceLocator.BeginScope())
         {
            var reader2 = _serviceLocator.Resolve<IQueryModelReader>();
            reader2.Invoking(me => me.Get<MyAccountQueryModel>(registered.Id)).Should().Throw<Exception>();
         }
      }

      [Test] public void ReturnsUpdatedDataAfterTransactionHasCommitted()
      {
         MyAccount registered;
         using(_serviceLocator.BeginScope())
         {
            var accountId = Guid.Parse("00000000-0000-0000-0000-000000000001");

            var aggregates = _serviceLocator.Resolve<IEventStoreUpdater>();
            registered = TransactionScopeCe.Execute(() => MyAccount.Register(aggregates, accountId, "email", "password"));

            _serviceLocator.Resolve<IQueryModelReader>()
                           .Get<MyAccountQueryModel>(registered.Id); //Make sure we read it once so caches etc get involved.
         }

         using(_serviceLocator.BeginScope())
         {
            TransactionScopeCe.Execute(() => _serviceLocator.Resolve<IEventStoreUpdater>().Get<MyAccount>(registered.Id).ChangeEmail("newEmail"));
         }

         using(_serviceLocator.BeginScope())
         {
            var loadedModel = _serviceLocator.Resolve<IQueryModelReader>()
                                             .Get<MyAccountQueryModel>(registered.Id);

            loadedModel.Should().NotBe(null);
            loadedModel.Email.Should().Be("newEmail");
         }
      }

      [Test] public void CanReturnPreviousVersionsOfQueryModel()
      {
         MyAccount registered;

         using(_serviceLocator.BeginScope())
         {
            var accountId = Guid.Parse("00000000-0000-0000-0000-000000000001");

            var aggregates = _serviceLocator.Resolve<IEventStoreUpdater>();
            registered = TransactionScopeCe.Execute(() => MyAccount.Register(aggregates, accountId, "originalEmail", "password"));

            _serviceLocator.Resolve<IVersioningQueryModelReader>()
                           .GetVersion<MyAccountQueryModel>(registered.Id, registered.Version); //Make sure we read it once so caches etc get involved.
         }

         using(_serviceLocator.BeginScope())
         {
            TransactionScopeCe.Execute(() =>
            {
               registered = _serviceLocator.Resolve<IEventStoreUpdater>().Get<MyAccount>(registered.Id);
               registered.ChangeEmail("newEmail1");
               registered.ChangeEmail("newEmail2");
               registered.ChangeEmail("newEmail3");
            });
         }

         using(_serviceLocator.BeginScope())
         {
            var loadedModel = _serviceLocator.Resolve<IVersioningQueryModelReader>()
                                             .Get<MyAccountQueryModel>(registered.Id);

            loadedModel.Should().NotBe(null);
            loadedModel.Email.Should().Be("newEmail3");

            _serviceLocator.Resolve<IVersioningQueryModelReader>()
                           .GetVersion<MyAccountQueryModel>(registered.Id, registered.Version - 1)
                           .Email.Should().Be("newEmail2");

            _serviceLocator.Resolve<IVersioningQueryModelReader>()
                           .GetVersion<MyAccountQueryModel>(registered.Id, registered.Version - 2)
                           .Email.Should().Be("newEmail1");

            _serviceLocator.Resolve<IVersioningQueryModelReader>()
                           .GetVersion<MyAccountQueryModel>(registered.Id, registered.Version - 3)
                           .Email.Should().Be("originalEmail");
         }
      }
   }

   namespace Domain
   {
      namespace UI
      {
         namespace QueryModels
         {
            [UsedImplicitly] public class MyAccountQueryModel : ISingleAggregateQueryModel
            {
               public Guid Id { get; private set; }
               internal string Email { get; set; } = "";
               internal string Password { get; set; } = "";

               public void SetId(Guid id) => Id = id;
            }

            public class AccountQueryModelGenerator : SingleAggregateQueryModelGenerator<AccountQueryModelGenerator, MyAccountQueryModel, AccountEvents.IAccountEvent, IEventStoreReader>
            {
               public AccountQueryModelGenerator(IEventStoreReader session) : base(session)
               {
                  RegisterHandlers()
                    .For<AccountEvents.PropertyUpdated.IEmail>(e => Model!.Email = e.Email)
                    .For<AccountEvents.PropertyUpdated.IPassword>(e => Model!.Password = e.Password);
               }
            }
         }
      }

      class MyAccount : Aggregate<MyAccount, AccountEvents.IAccountEvent, AccountEvents.AccountEvent>
      {
         MyAccount() : base(new DateTimeNowTimeSource())
         {
            RegisterEventAppliers()
              .For<AccountEvents.PropertyUpdated.IEmail>(e => Email = e.Email)
              .For<AccountEvents.PropertyUpdated.IPassword>(e => Password = e.Password)
              .For<AccountEvents.IAccountDeletedEvent>(_ => {});
         }

         public string Email { get; private set; } = "";
         public string Password { get; private set; } = "";

         public void ChangeEmail(string newEmail) => Publish(new AccountEvents.Implementation.EmailChangedEvent(newEmail));

         public static MyAccount Register(IEventStoreUpdater aggregates, Guid accountId, string email, string password)
         {
            var registered = new MyAccount();
            registered.Publish(new AccountEvents.Implementation.AccountRegisteredEvent(accountId, email, password));
            aggregates.Save(registered);
            return registered;
         }

         public void Delete() => Publish(new AccountEvents.Implementation.AccountDeletedEvent());
      }

      public static class AccountEvents
      {
         public interface IAccountEvent : IAggregateEvent;

         internal abstract class AccountEvent : AggregateEvent, IAccountEvent
         {
            protected AccountEvent() {}
            protected AccountEvent(Guid aggregateId) : base(aggregateId) {}
         }

         internal interface IAccountRegisteredEvent : IAggregateCreatedEvent,
                                                      PropertyUpdated.IEmail,
                                                      PropertyUpdated.IPassword;

         internal interface IEmailChangedEvent : PropertyUpdated.IEmail;

         internal interface IAccountDeletedEvent : IAccountEvent,
                                                   IAggregateDeletedEvent;

         internal static class PropertyUpdated
         {
            public interface IEmail : IAccountEvent
            {
               string Email { get; }
            }

            public interface IPassword : IAccountEvent
            {
               string Password { get; }
            }
         }

         internal static class Implementation
         {
            public class AccountRegisteredEvent(Guid accountId, string email, string password) : AccountEvent(accountId), IAccountRegisteredEvent
            {
               public string Email { get; private set; } = email;
               public string Password { get; private set; } = password;
            }

            public class EmailChangedEvent(string newEmail) : AccountEvent, IEmailChangedEvent
            {
               public string Email { get; private set; } = newEmail;
            }

            public class AccountDeletedEvent : AccountEvent, IAccountDeletedEvent;
         }
      }
   }
}
