

// ReSharper disable All
namespace AccountManagement.Domain.Tevents;

#pragma warning disable IDE1006,IDE0001,IDE0002,IDE0003,IDE0004,IDE0005,IDE0055,CA1050,CA1707,CA1716

/// <summary>
/// This file is automatically generated. Compze will automatically figure out most types that need to go in here, but some types you may need to add yourself.
/// Compze will tell you so in an exception thought, and you can just paste it in here.
/// Regenerate by running the application when type mappings are missing.
/// </summary>
public sealed class AutoGeneratedCurrentAssemblyTypeMapperForRefactoringSupport
{
   public void MapTypesForCurrentAssembly(Action<string, Type> map)
   {
      map("ae1684ff-a150-4840-ac08-1b9d21806da6", typeof(AccountManagement.Domain.Tevents.IAccountTevent.Created));
      map("0d3c30ec-5bec-46a3-9a6e-929cfef5f0e4", typeof(AccountManagement.Domain.Tevents.IAccountTevent.Created[]));
      map("37079b83-103e-4832-a718-3ad4c71700a7", typeof(AccountManagement.Domain.Tevents.AccountTevent.LoggedIn));
      map("ea23145d-1353-4991-ab21-3e58adf5254a", typeof(AccountManagement.Domain.Tevents.AccountTevent.LoggedIn[]));
      map("57fbdbc8-e0c8-4161-a67d-b086d69b1b16", typeof(AccountManagement.Domain.Tevents.AccountTevent.LoginFailed));
      map("2fdfb500-7191-44a9-8042-36a192cdb4fd", typeof(AccountManagement.Domain.Tevents.AccountTevent.LoginFailed[]));
      map("1299958f-bb1c-423b-9e44-be1ca8638cf9", typeof(AccountManagement.Domain.Tevents.AccountTevent));
      map("24c7c89e-c3ef-4c64-9753-eda985652c1c", typeof(AccountManagement.Domain.Tevents.AccountTevent[]));
      map("61556a08-356c-4fa7-a63c-91e667ea65c9", typeof(AccountManagement.Domain.Tevents.AccountTevent.UserChangedEmail));
      map("5ed3e211-053f-4139-bd76-a0b9cc148fa9", typeof(AccountManagement.Domain.Tevents.AccountTevent.UserChangedEmail[]));
      map("19998285-432f-4296-93e8-7a8d0f6814bd", typeof(AccountManagement.Domain.Tevents.AccountTevent.UserChangedPassword));
      map("899588d6-7b9f-466a-8536-6173372564de", typeof(AccountManagement.Domain.Tevents.AccountTevent.UserChangedPassword[]));
      map("80d90851-4ae5-4818-9d62-dc255fb5bcd3", typeof(AccountManagement.Domain.Tevents.AccountTevent.UserRegistered));
      map("29ef2e91-8c23-47dc-a17d-ca243d451dbc", typeof(AccountManagement.Domain.Tevents.AccountTevent.UserRegistered[]));
      map("a43f6c96-a985-4060-8b22-f6f9bcac0755", typeof(AccountManagement.Domain.Tevents.IAccountTevent.LoggedIn));
      map("f641a8ff-f12d-43eb-ab07-6882268670a3", typeof(AccountManagement.Domain.Tevents.IAccountTevent.LoggedIn[]));
      map("665023a5-515d-4edf-9cb6-5288baf29db2", typeof(AccountManagement.Domain.Tevents.IAccountTevent.LoginAttempted));
      map("bc47e8b0-e9ba-48ef-b3c7-9e0ab7b9e8d3", typeof(AccountManagement.Domain.Tevents.IAccountTevent.LoginAttempted[]));
      map("5dbee37a-a4f9-43da-8229-baf5ecc93cf1", typeof(AccountManagement.Domain.Tevents.IAccountTevent.LoginFailed));
      map("bcffe10d-979f-4df8-be09-25465ea39e02", typeof(AccountManagement.Domain.Tevents.IAccountTevent.LoginFailed[]));
      map("33933b47-b98e-4c8a-98ae-2ecf88d962f5", typeof(AccountManagement.Domain.Tevents.IAccountTevent.PropertyUpdated.Email));
      map("e9022e2e-14c9-4929-bbc4-9227611a6c1b", typeof(AccountManagement.Domain.Tevents.IAccountTevent.PropertyUpdated.Email[]));
      map("a533f2ff-155f-4d53-a755-eb2ac81c61e8", typeof(AccountManagement.Domain.Tevents.IAccountTevent.PropertyUpdated.Password));
      map("7dfc1261-201e-42ea-9e6b-fc39d36869e5", typeof(AccountManagement.Domain.Tevents.IAccountTevent.PropertyUpdated.Password[]));
      map("8aea46ad-968d-4e38-8c2d-3736de0c70b3", typeof(AccountManagement.Domain.Tevents.IAccountTevent));
      map("da622df1-bd7d-4ad3-9f4f-6c0c1f83b0f6", typeof(AccountManagement.Domain.Tevents.IAccountTevent[]));
      map("aeaf8613-14af-4c5b-acad-0d07570b1677", typeof(AccountManagement.Domain.Tevents.IAccountTevent.UserChangedEmail));
      map("ebe6f437-eadf-41e0-843a-09fc81e28fc0", typeof(AccountManagement.Domain.Tevents.IAccountTevent.UserChangedEmail[]));
      map("648b86c0-49d5-4987-b7a8-6581f9aedc4d", typeof(AccountManagement.Domain.Tevents.IAccountTevent.UserChangedPassword));
      map("c817c045-80be-458a-b2d8-a2384968e338", typeof(AccountManagement.Domain.Tevents.IAccountTevent.UserChangedPassword[]));
      map("ca41c0b1-56f7-4a21-914c-af0729de29ba", typeof(AccountManagement.Domain.Tevents.IAccountTevent.UserRegistered));
      map("ad38a3e6-e31d-4a45-903c-2e3e7006d673", typeof(AccountManagement.Domain.Tevents.IAccountTevent.UserRegistered[]));
   }
}
