// <auto-generated>
// This file was generated by Compze.InternalizedSourceReferences.
// Changes to this file will be overwritten.
// </auto-generated>
#nullable enable
using System;

namespace Compze.Utilities.SystemCE.ThreadingCE.Testing;

internal class Disposable(Action action) : IDisposable
{
   readonly Action _action = action;
   public void Dispose() => _action();
}
