// <auto-generated>
// This file was generated by Compze.InternalizedSourceReferences.
// Changes to this file will be overwritten.
// </auto-generated>
#nullable enable
using System.Threading.Tasks;
using Compze.Functional;

namespace Compze.Utilities.SystemCE.ThreadingCE.TasksCE;

internal static class TaskUnit
{
   public static async Task<unit> AsUnit(this Task task)
   {
      await task.caf();
      return unit.Value;
   }
}
