// <auto-generated>
// This file was generated by CircularLibraryDependencySourceRewriter.
// Changes to this file will be overwritten.
// </auto-generated>
using System;
using System.Collections.Generic;
using Compze.Utilities.Functional;
using JetBrains.Annotations;
using static Compze.Utilities.Contracts.Assert;

namespace Compze.Utilities.SystemCE.LinqCE;

/// <summary/>
internal static partial class EnumerableCE
{
   /// <summary>
   /// Executes <paramref name="action"/> for each element in the sequence <paramref name="source"/>.
   /// </summary>
   public static unit ForEach<TSource, TReturn>(this IEnumerable<TSource> source, Func<TSource, TReturn> action) => unit.From(() =>
   {
      Argument.NotNull(source).NotNull(action);
      foreach(var item in source)
      {
         action(item);
      }
   });

   /// <summary>
   /// Executes <paramref name="action"/> for each element in the sequence <paramref name="source"/>.
   /// </summary>
   public static unit ForEach<T>(this IEnumerable<T> source, [InstantHandle] Action<T> action) => unit.From(() =>
   {
      Argument.NotNull(source).NotNull(action);

      foreach(var item in source)
      {
         action(item);
      }
   });

   /// <summary>
   /// Executes <paramref name="action"/> for each element in the sequence <paramref name="source"/>.
   /// </summary>
   public static unit ForEach<T>(this IEnumerable<T> source, Action<T, int> action) => unit.From(() =>
   {
      Argument.NotNull(source).NotNull(action);

      var index = 0;
      foreach(var item in source)
      {
         action(item, index++);
      }
   });
}
