using System;

// ReSharper disable All
namespace Compze.Abstractions;

#pragma warning disable IDE1006,IDE0001,IDE0002,IDE0003,IDE0004,IDE0005,IDE0055,CA1050,CA1707,CA1716

/// <summary>
/// This file is automatically generated. Compze will automatically figure out most types that need to go in here, but some types you may need to add yourself.
/// Compze will tell you so in an exception thought, and you can just paste it in here.
/// Regenerate by running the application when type mappings are missing.
/// </summary>
public sealed class AutoGeneratedCurrentAssemblyTypeMapperForRefactoringSupport
{
   public void MapTypesForCurrentAssembly(Action<string, Type> map)
   {
      map("97a8baea-ec1c-459a-a4e0-250da40fbd71", typeof(Compze.Abstractions.Tessaging.Public.IExactlyOnceTevent));
      map("969bc873-83d3-41a8-835d-e89bf2dde930", typeof(Compze.Abstractions.Tessaging.Public.IExactlyOnceTevent[]));
      map("6f44e1fc-dd81-4332-90ca-c693669b2d46", typeof(Compze.Abstractions.Tessaging.Public.IRemotableTevent));
      map("0656810d-5632-400a-bc17-9186b07ee26a", typeof(Compze.Abstractions.Tessaging.Public.IRemotableTevent[]));
      map("408808b7-93ef-4106-b724-27f6665f9e97", typeof(Compze.Abstractions.Tessaging.Public.TessageTypes.Remotable.AtMostOnce.AtMostOnceTypermediaTommand));
      map("5156231a-7731-4391-8e44-93ac3cfe40c8", typeof(Compze.Abstractions.Tessaging.Public.TessageTypes.Remotable.AtMostOnce.AtMostOnceTypermediaTommand[]));
      map("46668db1-1442-4f65-97f8-6267ceb5a038", typeof(Compze.Abstractions.Tessaging.Public.TessageTypes.Remotable.ExactlyOnce.Tommand));
      map("a7fce62b-aab8-49a6-b447-5432372beda8", typeof(Compze.Abstractions.Tessaging.Public.TessageTypes.Remotable.ExactlyOnce.Tommand[]));
   }
}
