using System;

// ReSharper disable All
namespace Compze.Abstractions;

#pragma warning disable IDE1006,IDE0001,IDE0002,IDE0003,IDE0004,IDE0005,IDE0055,CA1050,CA1707,CA1716

/// <summary>
/// This file is automatically generated. Compze will automatically figure out most types that need to go in here, but some types you may need to add yourself.
/// Compze will tell you so in an exception thought, and you can just paste it in here.
/// Regenerate by running the application when type mappings are missing.
/// </summary>
public sealed class AutoGeneratedCurrentAssemblyTypeMapperForRefactoringSupport
{
   public void MapTypesForCurrentAssembly(Action<string, Type> map)
   {
      map("0d68a831-87c0-4d05-8e52-bf063d51b56d", typeof(Compze.Abstractions.Tessaging.Public.IExactlyOnceTevent));
      map("f0bf0312-1300-4ba9-8f0d-eaf460b52337", typeof(Compze.Abstractions.Tessaging.Public.IExactlyOnceTevent[]));
      map("887aad71-52f3-46f8-a26a-e2886941758d", typeof(Compze.Abstractions.Tessaging.Public.IRemotableTevent));
      map("c55a6157-dcc8-4928-a48c-28b2c6f8bd49", typeof(Compze.Abstractions.Tessaging.Public.IRemotableTevent[]));
      map("f1581159-4ff1-4df5-b10b-0680552111b1", typeof(Compze.Abstractions.Tessaging.Public.TessageTypes.Remotable.AtMostOnce.AtMostOnceTypermediaTommand));
      map("ea3be0f8-dbae-4353-87cf-6b4f0294fb5f", typeof(Compze.Abstractions.Tessaging.Public.TessageTypes.Remotable.AtMostOnce.AtMostOnceTypermediaTommand[]));
      map("fcf83cc4-de51-4b17-ab44-741c2d34feb2", typeof(Compze.Abstractions.Tessaging.Public.TessageTypes.Remotable.ExactlyOnce.Tommand));
      map("308ca648-8424-4c81-adf1-ad90123c9240", typeof(Compze.Abstractions.Tessaging.Public.TessageTypes.Remotable.ExactlyOnce.Tommand[]));

      map("be0a1c56-f37a-4e37-bafe-8d4c1cc0a417", typeof(System.Collections.Generic.List<Compze.Abstractions.Public.EntityId>));
      map("a1d63763-f934-493b-ae92-aeb2f15368b7", typeof(Compze.Abstractions.Public.TentityId));
      map("5d87bfa3-5f88-4d3b-8971-c994757286ce", typeof(Compze.Abstractions.Public.TaggregateId));
      map("0469d68b-776e-4844-8766-1cec0a563e9c", typeof(Compze.Abstractions.Public.TessageId));
   }
}
