

// ReSharper disable All
namespace Compze.Abstractions;

#pragma warning disable IDE1006,IDE0001,IDE0002,IDE0003,IDE0004,IDE0005,IDE0055,CA1050,CA1707,CA1716

/// <summary>
/// This file is automatically generated. Compze will automatically figure out most types that need to go in here, but some types you may need to add yourself.
/// Compze will tell you so in an exception thought, and you can just paste it in here.
/// Regenerate by running the application when type mappings are missing.
/// </summary>
public sealed class AutoGeneratedCurrentAssemblyTypeMapperForRefactoringSupport
{
   public void MapTypesForCurrentAssembly(Action<string, Type> map)
   {
      map("0d68a831-87c0-4d05-8e52-bf063d51b56d", typeof(Compze.Abstractions.Tessaging.Public.IExactlyOnceTevent));
      map("887aad71-52f3-46f8-a26a-e2886941758d", typeof(Compze.Abstractions.Tessaging.Public.IRemotableTevent));
      map("f1581159-4ff1-4df5-b10b-0680552111b1", typeof(Compze.Abstractions.Tessaging.Public.TessageTypes.Remotable.AtMostOnce.AtMostOnceTypermediaTommand));
      map("fcf83cc4-de51-4b17-ab44-741c2d34feb2", typeof(Compze.Abstractions.Tessaging.Public.TessageTypes.Remotable.ExactlyOnce.Tommand));

      map("a1d63763-f934-493b-ae92-aeb2f15368b7", typeof(Compze.Abstractions.Public.TentityId));
      map("5d87bfa3-5f88-4d3b-8971-c994757286ce", typeof(Compze.Abstractions.Public.TaggregateId));
      map("0469d68b-776e-4844-8766-1cec0a563e9c", typeof(Compze.Abstractions.Public.TessageId));

      // Compze open generic definitions that appear in closed generics
      map("e0f1a2b3-c4d5-4e6f-7a8b-9c0d1e2f3a4b", typeof(Compze.Abstractions.Tessaging.Public.TessageTypes.Remotable.NonTransactional.Tueries.TaggregateLink<>));
      map("f1a2b3c4-d5e6-4f7a-8b9c-0d1e2f3a4b5c", typeof(Compze.Abstractions.Tessaging.Public.TessageTypes.Remotable.AtMostOnce.AtMostOnceTypermediaTommand<>));

      // BCL open generic definitions — mapped here so end-user code doesn't need to deal with them.
      // These GUIDs must NEVER change — persisted composite TypeIds depend on them.
      map("a1b2c3d4-e5f6-4a7b-8c9d-0e1f2a3b4c5d", typeof(System.Collections.Generic.List<>));
      map("b2c3d4e5-f6a7-4b8c-9d0e-1f2a3b4c5d6e", typeof(System.Collections.Generic.HashSet<>));
      map("c3d4e5f6-a7b8-4c9d-0e1f-2a3b4c5d6e7f", typeof(System.Collections.Generic.Dictionary<,>));
      map("d4e5f6a7-b8c9-4d0e-1f2a-3b4c5d6e7f80", typeof(System.Collections.Generic.SortedSet<>));
      map("e5f6a7b8-c9d0-4e1f-2a3b-4c5d6e7f8091", typeof(System.Collections.Generic.Queue<>));
      map("f6a7b8c9-d0e1-4f2a-3b4c-5d6e7f8091a2", typeof(System.Collections.Generic.Stack<>));
      map("a7b8c9d0-e1f2-4a3b-4c5d-6e7f8091a2b3", typeof(System.Collections.Generic.LinkedList<>));
      map("b8c9d0e1-f2a3-4b4c-5d6e-7f8091a2b3c4", typeof(System.Collections.Generic.SortedList<,>));
      map("c9d0e1f2-a3b4-4c5d-6e7f-8091a2b3c4d5", typeof(System.Collections.Generic.SortedDictionary<,>));
      map("d0e1f2a3-b4c5-4d6e-7f80-91a2b3c4d5e6", typeof(System.Collections.Generic.KeyValuePair<,>));
   }
}
