// <auto-generated>
// This file was generated by Compze.InternalizedSourceReferences.
// Changes to this file will be overwritten.
// </auto-generated>
#nullable enable
namespace Compze.Utilities.DependencyInjection;

// ReSharper disable once ClassNeverInstantiated.Global Because static classes cannot be used as type arguments.
internal class ServiceTypeIndex : TypeIndex<ServiceTypeIndex>;