// <auto-generated>
// This file was generated by Compze.InternalizedSourceReferences.
// Changes to this file will be overwritten.
// </auto-generated>
#nullable enable
namespace Compze.Utilities.DependencyInjection;

internal interface IServiceLocatorKernel
{
   TComponent Resolve<TComponent>() where TComponent : class;
}
