using System;

namespace AccountManagement.API;

// ReSharper disable All
#pragma warning disable IDE1006,IDE0001,IDE0002,IDE0003,IDE0004,IDE0005,IDE0055,CA1050,CA1707,CA1716

/// <summary>
/// This file is automatically generated. Do not edit manually.
/// Regenerate by running the application when type mappings are missing.
/// </summary>
public sealed class AutoGeneratedCurrentAssemblyTypeMapperForRefactoringSupport
{
   public void MapTypesForCurrentAssembly(Action<Guid, Type> map)
   {
      map(new Guid("8bfa1e6d-3fdd-491d-a6b9-1e7fc9bed767"), typeof(AccountManagement.API.AccountResource));
      map(new Guid("264cc4f3-23e4-429e-a748-ca477bf1475a"), typeof(AccountManagement.API.AccountResource.Command.ChangeEmail));
      map(new Guid("12652e76-fdfb-4ea0-98ee-d4e215e8bc67"), typeof(AccountManagement.API.AccountResource.Command.ChangeEmail[]));
      map(new Guid("3e9358f0-86e5-47b9-bb13-1e65f2b405dc"), typeof(AccountManagement.API.AccountResource.Command.ChangePassword));
      map(new Guid("2a8ac460-54ea-4895-9ac3-7d2e3995c0c6"), typeof(AccountManagement.API.AccountResource.Command.ChangePassword[]));
      map(new Guid("e864922c-7fd4-46ed-b12b-fa933d41f4a1"), typeof(AccountManagement.API.AccountResource.Command.LogIn));
      map(new Guid("89aec03f-27b3-4f13-ba62-0ec6245de25d"), typeof(AccountManagement.API.AccountResource.Command.LogIn[]));
      map(new Guid("d6993e5d-2908-401a-8219-005f3aeb5e96"), typeof(AccountManagement.API.AccountResource.Command.Register));
      map(new Guid("06c9ea06-3884-4844-8162-6feb2d1821a4"), typeof(AccountManagement.API.AccountResource.Command.Register[]));
      map(new Guid("37e87352-7b75-4bc1-b72c-a7cd23d3dad7"), typeof(AccountManagement.API.AccountResource[]));
      map(new Guid("7d7baef4-72e4-4e85-be53-8aa1f9708ea3"), typeof(Compze.Abstractions.PersistentEntity<AccountManagement.API.AccountResource>));
      map(new Guid("2d604b94-905d-4eea-a5ba-05b9c5eec663"), typeof(Compze.Tessaging.Abstractions.MessageTypes.Remotable.AtMostOnce.AtMostOnceCommand<AccountManagement.API.AccountResource.Command.LogIn.LoginAttemptResult>));
      map(new Guid("483af638-ef19-4493-9445-529e80620298"), typeof(Compze.Tessaging.Abstractions.MessageTypes.Remotable.AtMostOnce.AtMostOnceCommand<AccountManagement.API.AccountResource.Command.Register.RegistrationAttemptResult>));
      map(new Guid("8b152cf2-157f-4f61-9535-ea88312c1237"), typeof(Compze.Tessaging.Abstractions.MessageTypes.Remotable.NonTransactional.Queries.EntityLink<AccountManagement.API.AccountResource>));
      map(new Guid("8a48562d-c176-49a0-a513-88c76442a0be"), typeof(Compze.Tessaging.Abstractions.MessageTypes.Remotable.NonTransactional.Queries.NewableResultLink<AccountManagement.API.StartResource>));
   }
}