using System;
using Compze.Abstractions.Internal.Refactoring.Naming;

namespace AccountManagement.API;

// ReSharper disable All
#pragma warning disable IDE1006,IDE0001,IDE0002,IDE0003,IDE0004,IDE0005,IDE0055,CA1050,CA1707,CA1716

/// <summary>
/// This file is automatically generated. Do not edit manually.
/// Regenerate by running the application when type mappings are missing.
/// </summary>
public sealed class AutoGeneratedCurrentAssemblyTypeMapperForRefactoringSupport : IMapCurrentAssemblyTypesForRefactoringSupport
{
   public void MapTypesForCurrentAssembly(ITypeMappingRegistrar registrar)
   {
      registrar
        .Map<AccountManagement.API.AccountResource>("8bfa1e6d-3fdd-491d-a6b9-1e7fc9bed767")
        .Map<AccountManagement.API.AccountResource.Command.ChangeEmail>("264cc4f3-23e4-429e-a748-ca477bf1475a")
        .Map<AccountManagement.API.AccountResource.Command.ChangePassword>("3e9358f0-86e5-47b9-bb13-1e65f2b405dc")
        .Map<AccountManagement.API.AccountResource.Command.LogIn>("e864922c-7fd4-46ed-b12b-fa933d41f4a1")
        .Map<AccountManagement.API.AccountResource.Command.Register>("d6993e5d-2908-401a-8219-005f3aeb5e96")
        .Map<Compze.Abstractions.PersistentEntity<AccountManagement.API.AccountResource>>("39186e56-d20d-455c-990a-6292b2bdd1e2")
        .Map<Compze.Tessaging.Abstractions.MessageTypes.Remotable.AtMostOnce.AtMostOnceCommand<AccountManagement.API.AccountResource.Command.LogIn.LoginAttemptResult>>("d388f55d-b43f-4217-83af-6d2902ca892f")
        .Map<Compze.Tessaging.Abstractions.MessageTypes.Remotable.AtMostOnce.AtMostOnceCommand<AccountManagement.API.AccountResource.Command.Register.RegistrationAttemptResult>>("6826f3ed-c874-451f-b8d3-7826c5123b43")
        .Map<Compze.Tessaging.Abstractions.MessageTypes.Remotable.NonTransactional.Queries.EntityLink<AccountManagement.API.AccountResource>>("62f07526-d4b6-4e7e-bf62-3bc7a985bf03")
        .Map<Compze.Tessaging.Abstractions.MessageTypes.Remotable.NonTransactional.Queries.NewableResultLink<AccountManagement.API.StartResource>>("19e04bc6-fdf9-483e-b3f9-343cc2652465")
        ;
   }
}
