// <auto-generated>
// This file was generated by Compze.InternalizedSourceReferences.
// Changes to this file will be overwritten.
// </auto-generated>
#nullable enable
using System;
using System.Threading.Tasks;
using Compze.Utilities.SystemCE.ThreadingCE.TasksCE;

// ReSharper disable InconsistentNaming

namespace Compze.Utilities.Functional;

/// <summary>
/// Enables chaining method calls in a fluent functional programming style rather than having to use separate lines and temporary variables.
/// Think of these as "missing operators" for .NET types rather than traditional extension methods.
/// 
/// NAMING CONVENTION: All methods use lowercase naming breaking .NET conventions for two critical reasons:
/// 
/// 1. VISUAL DISTINCTION: Instantly recognizable as language-like features,
/// 
/// 2. COLLISION AVOIDANCE: Since these are extensions on ALL types,
///    avoiding name conflicts with existing methods is vital.
///    Lowercase naming is the most effective strategy we found.
/// </summary>
internal static class Pipe
{
   ///<summary>passes <paramref name="it"/> to <paramref name="func"/> and returns the result. It is the pipe forward operator that is missing in C#. If you start using it, soon ._( will become the missing operator in your mind.</summary>
   public static TResult _<TThis, TResult>(this TThis it, Func<TThis, TResult> func) => func(it);

   ///<summary>Passes <paramref name="it"/> to <paramref name="tap"/> and returns <paramref name="it"/></summary>
   public static T tap<T>(this T it, Action<T> tap)
   {
      tap(it);
      return it;
   }

   ///<summary>Mutates <paramref name="it"/> using <paramref name="mutate"/> and returns <paramref name="it"/></summary>
   public static T mutate<T>(this T it, Action<T> mutate) => it.tap(mutate);

   ///<summary> Returns <paramref name="value"/>, ignoring the previous value.  Useful for chaining calls where a constant value is needed.</summary>
   public static TResult then<TValue, TResult>(this TValue _, TResult value) => value;

   ///<summary>Invokes <paramref name="func"/>, ignoring the previous value. Useful for chaining calls where the previous result is irrelevant.</summary>
   public static TResult then<TValue, TResult>(this TValue _, Func<TResult> func) => func();

   ///<summary> Executes <paramref name="action"/>, ignoring the previous value, and returns a <see cref="unit"/>.  Useful for chaining statements that return void.</summary>
   public static unit then<TValue>(this TValue _, Action action) => Functional.unit.From(action);

   ///<summary>Throws Exception if <paramref name="predicate"/> returns false when applied to <paramref name="it"/> otherwise returns <paramref name="it"/></summary>
   public static T assert<T>(this T it, Predicate<T> predicate, Func<T, string> tessageFactory) =>
      it.assert(predicate, () => new Exception(tessageFactory(it)));

   ///<summary>Throws <paramref name="exceptionFactory"/>() if <paramref name="predicate"/> returns false when applied to <paramref name="it"/> otherwise returns <paramref name="it"/></summary>
   public static T assert<T>(this T it, Predicate<T> predicate, Func<Exception> exceptionFactory)
   {
      if(!predicate(it))
         throw exceptionFactory();
      return it;
   }

   ///<summary>Mutates <paramref name="it"/> using <paramref name="mutate"/> and returns <paramref name="it"/></summary>
   public static async Task<T> mutateAsync<T>(this T it, Func<T, Task> mutate)
   {
      await mutate(it).caf();
      return it;
   }
}
