using System;
using Compze.Abstractions.Internal.Refactoring.Naming;

namespace Compze.Tessaging.Teventive.EventStore.Abstractions;

// ReSharper disable All
#pragma warning disable IDE1006,IDE0001,IDE0002,IDE0003,IDE0004,IDE0005,IDE0055,CA1050,CA1707,CA1716

/// <summary>
/// This file is automatically generated. Do not edit manually.
/// Regenerate by running the application when type mappings are missing.
/// </summary>
public sealed class AutoGeneratedCurrentAssemblyTypeMapperForRefactoringSupport : IMapCurrentAssemblyTypesForRefactoringSupport
{
   public void MapTypesForCurrentAssembly(ITypeMappingRegistrar registrar)
   {
      registrar
        .Map<Compze.Tessaging.Teventive.EventStore.Abstractions.AggregateEvent>("b5497a3e-5876-4fc0-86ef-3d0529b03cfc")
        .Map<Compze.Tessaging.Teventive.EventStore.Abstractions.AggregateEvent[]>("fac31dd4-45b1-48f2-9391-a5196963aa3d")
        .Map<Compze.Tessaging.Teventive.EventStore.Abstractions.IAggregateCreatedEvent>("27746483-3192-4ffb-8a4f-919ce6df1b1a")
        .Map<Compze.Tessaging.Teventive.EventStore.Abstractions.IAggregateCreatedEvent[]>("4b38ee9b-1863-455a-9c57-f071867758c4")
        .Map<Compze.Tessaging.Teventive.EventStore.Abstractions.IAggregateDeletedEvent>("4d3db2dd-ef96-4d5e-9a2d-9d4d4c68284e")
        .Map<Compze.Tessaging.Teventive.EventStore.Abstractions.IAggregateDeletedEvent[]>("e5c1019f-cced-49bf-aa6e-746fb12c31c5")
        .Map<Compze.Tessaging.Teventive.EventStore.Abstractions.IAggregateEvent>("ec80856b-977a-4d3f-9a07-755a824069b8")
        .Map<Compze.Tessaging.Teventive.EventStore.Abstractions.IAggregateEvent[]>("9099916f-a417-4cf6-baea-bfedaec2b338")
        .Map<Compze.Tessaging.Teventive.EventStore.Abstractions.IMutableAggregateEvent>("0e92381b-1b25-445a-a634-3b35075b7dfe")
        .Map<Compze.Tessaging.Teventive.EventStore.Abstractions.IMutableAggregateEvent[]>("ee66eee0-d65e-4fcd-ac7b-7d9abf714d7d")
         ;
   }
}
