// <auto-generated>
// This file was generated by Compze.InternalizedSourceReferences.
// Changes to this file will be overwritten.
// </auto-generated>
#nullable enable
using System;
using Compze.Functional;

namespace Compze.Utilities.Logging;

internal interface ILogger
{
   ILogger WithLogLevel(LogLevel level);
   unit Error(Exception exception, string? message = null);
   unit Warning(string message);
   unit Warning(Exception exception, string message);
   unit Info(string message);
   unit Debug(string message);

   unit NCrunch(string message) => Warning($"NCR:{message}");
}
