// <auto-generated>
// This file was generated by Compze.InternalizedSourceReferences.
// Changes to this file will be overwritten.
// </auto-generated>
#nullable enable
using System;
using System.Threading.Tasks;
using Compze.Functional;

namespace Compze.Utilities.SystemCE.ActionFuncHarmonization;

internal static class Func
{
   public static Func<unit> From(Action action) => action.AsFunc();
   public static Func<TParam, unit> From<TParam>(Action<TParam> action) => action.AsFunc();
   public static Func<TParam, TParam2, unit> From<TParam, TParam2>(Action<TParam,TParam2> action) => action.AsFunc();


   public static Func<Task<unit>> From(Func<Task> action) => action.AsFunc();
   public static Func<TParam, Task<unit>> From<TParam>(Func<TParam, Task> action) => action.AsFunc();
   public static Func<TParam, TParam2, Task<unit>> From<TParam, TParam2>(Func<TParam,TParam2, Task> action) => action.AsFunc();
}