using System;
using Compze.Abstractions.Internal.Refactoring.Naming;

namespace Compze.Tests.Integration;

// ReSharper disable All
#pragma warning disable IDE1006,IDE0001,IDE0002,IDE0003,IDE0004,IDE0005,IDE0055,CA1050,CA1707,CA1716

/// <summary>
/// This file is automatically generated. Do not edit manually.
/// Regenerate by running the application when type mappings are missing.
/// </summary>
public sealed class AutoGeneratedCurrentAssemblyTypeMapperForRefactoringSupport : IMapCurrentAssemblyTypesForRefactoringSupport
{
   public void MapTypesForCurrentAssembly(ITypeMappingRegistrar registrar)
   {
      registrar
        .Map<Compze.Tessaging.Abstractions.MessageTypes.Remotable.AtMostOnce.AtMostOnceCommand<Compze.Tests.Integration.Tessaging.ServiceBusSpecification.Given_a_backend_endpoint_with_a_command_event_and_query_handler.Experiment_with_unifying_events_and_commands_test.RegisterUserResult>>("f6d67dfa-089f-40e3-bc7e-376309250ff4")
        .Map<Compze.Tessaging.Abstractions.MessageTypes.Remotable.AtMostOnce.AtMostOnceCommand<Compze.Tests.Integration.Tessaging.ServiceBusSpecification.Navigator_specification.UserRegisteredConfirmationResource>>("8c82ce56-9fa1-4241-b237-905bb3692b99")
        .Map<Compze.Tessaging.Teventive.Aggregate<Compze.Tests.Integration.CQRS.Query.Models.AutoGenerated.Domain.MyAccount,Compze.Tests.Integration.CQRS.Query.Models.AutoGenerated.Domain.AccountEvents.IAccountEvent,Compze.Tests.Integration.CQRS.Query.Models.AutoGenerated.Domain.AccountEvents.AccountEvent>>("9bb5b321-2d0d-4f21-86a0-a4f2f74e3f29")
        .Map<Compze.Tessaging.Teventive.Aggregate<Compze.Tests.Integration.CQRS.User,Compze.Tests.Integration.CQRS.IUserEvent,Compze.Tests.Integration.CQRS.UserEvent>>("5ddf54cd-4371-4fb6-8970-fcb31d6205ec")
        .Map<Compze.Tessaging.Teventive.Aggregate<Compze.Tests.Integration.Tessaging.ServiceBusSpecification.Given_a_backend_endpoint_with_a_command_event_and_query_handler.Experiment_with_unifying_events_and_commands_test.UserAggregate,Compze.Tests.Integration.Tessaging.ServiceBusSpecification.Given_a_backend_endpoint_with_a_command_event_and_query_handler.Experiment_with_unifying_events_and_commands_test.UserEvent.IRoot,Compze.Tests.Integration.Tessaging.ServiceBusSpecification.Given_a_backend_endpoint_with_a_command_event_and_query_handler.Experiment_with_unifying_events_and_commands_test.UserEvent.Implementation.Root>>("075cabf1-34b3-431d-a052-9e484778729e")
        .Map<Compze.Tessaging.Teventive.Aggregate<Compze.Tests.Integration.Tessaging.ServiceBusSpecification.Given_a_backend_endpoint_with_a_command_event_and_query_handler.Experiment_with_unifying_events_and_commands_test.UserRegistrarAggregate,Compze.Tests.Integration.Tessaging.ServiceBusSpecification.Given_a_backend_endpoint_with_a_command_event_and_query_handler.Experiment_with_unifying_events_and_commands_test.UserRegistrarEvent.IRoot,Compze.Tests.Integration.Tessaging.ServiceBusSpecification.Given_a_backend_endpoint_with_a_command_event_and_query_handler.Experiment_with_unifying_events_and_commands_test.UserRegistrarEvent.Implementation.Root>>("e36a8619-43b7-4f77-b24f-b314786b75b9")
        .Map<Compze.Tests.Integration.CQRS.IMigratedAfterUserChangedEmailEvent>("57318ec3-fe6b-4fcf-8d9b-3136c847ff3e")
        .Map<Compze.Tests.Integration.CQRS.IMigratedBeforeUserRegisteredEvent>("6d7ca6e5-2e82-4620-8fab-27b3e6a6a858")
        .Map<Compze.Tests.Integration.CQRS.IMigratedReplaceUserChangedPasswordEvent>("f20b6ca2-06cd-4000-b206-9a09da28601e")
        .Map<Compze.Tests.Integration.CQRS.ISomeEvent>("7a63c891-dffc-4339-bca9-9fcb73078092")
        .Map<Compze.Tests.Integration.CQRS.IUserChangedEmail>("8e4bc5ee-5f12-48e0-9405-81da5db39d8c")
        .Map<Compze.Tests.Integration.CQRS.IUserChangedPassword>("872b6e56-4bea-4191-a665-b97e5b4f57f3")
        .Map<Compze.Tests.Integration.CQRS.IUserEvent>("7a61757a-d3e7-4978-b4e5-7600dd26306d")
        .Map<Compze.Tests.Integration.CQRS.IUserRegistered>("3cbb8f2a-63d2-4954-82d4-135654f3f772")
        .Map<Compze.Tests.Integration.CQRS.MigratedAfterUserChangedEmailEvent>("a6d682a8-9067-492e-9aab-3b185a4aeb92")
        .Map<Compze.Tests.Integration.CQRS.MigratedBeforeUserRegisteredEvent>("00011fad-5abc-40da-b3a9-0417a535133b")
        .Map<Compze.Tests.Integration.CQRS.MigratedReplaceUserChangedPasswordEvent>("d39d4f18-1123-4930-9774-426ec6875632")
        .Map<Compze.Tests.Integration.CQRS.Query.Models.AutoGenerated.Domain.AccountEvents.AccountEvent>("33961aff-eb53-4d6b-88af-5975ddee2eab")
        .Map<Compze.Tests.Integration.CQRS.Query.Models.AutoGenerated.Domain.AccountEvents.IAccountDeletedEvent>("df9183ff-a8a1-4d04-aa72-2aba428cef37")
        .Map<Compze.Tests.Integration.CQRS.Query.Models.AutoGenerated.Domain.AccountEvents.IAccountEvent>("bc72fe66-ea8c-41f1-bbf1-a3fad66feab7")
        .Map<Compze.Tests.Integration.CQRS.Query.Models.AutoGenerated.Domain.AccountEvents.IAccountRegisteredEvent>("2d284994-c227-4120-b39c-eb32ce9c0ef3")
        .Map<Compze.Tests.Integration.CQRS.Query.Models.AutoGenerated.Domain.AccountEvents.IEmailChangedEvent>("0648ee04-7001-4ffa-b1b8-834a68dce81a")
        .Map<Compze.Tests.Integration.CQRS.Query.Models.AutoGenerated.Domain.AccountEvents.Implementation.AccountDeletedEvent>("2808668e-d390-4b31-acb3-36c6a2960b6e")
        .Map<Compze.Tests.Integration.CQRS.Query.Models.AutoGenerated.Domain.AccountEvents.Implementation.AccountRegisteredEvent>("323b9240-820f-4571-81e2-99ec4082ef5b")
        .Map<Compze.Tests.Integration.CQRS.Query.Models.AutoGenerated.Domain.AccountEvents.Implementation.EmailChangedEvent>("4533f77a-ab61-43e9-bc88-ffab04b584b1")
        .Map<Compze.Tests.Integration.CQRS.Query.Models.AutoGenerated.Domain.AccountEvents.PropertyUpdated.IEmail>("03302155-da31-4eb8-a380-640cff9cfa95")
        .Map<Compze.Tests.Integration.CQRS.Query.Models.AutoGenerated.Domain.AccountEvents.PropertyUpdated.IPassword>("533e595b-df1a-4a19-af03-e9074786d0af")
        .Map<Compze.Tests.Integration.CQRS.Query.Models.AutoGenerated.Domain.MyAccount>("6feda3ff-96e1-4edf-a8b0-8b33eb923834")
        .Map<Compze.Tests.Integration.CQRS.Query.Models.AutoGenerated.Domain.UI.QueryModels.MyAccountQueryModel>("922ad449-3609-4e4e-a203-1066a85b6595")
        .Map<Compze.Tests.Integration.CQRS.SomeEvent>("c6400398-04a7-4d5b-a13b-61906f2f0cc8")
        .Map<Compze.Tests.Integration.CQRS.User>("7b93ea04-304c-4b3f-8ec1-82b744fc2108")
        .Map<Compze.Tests.Integration.CQRS.UserChangedEmail>("86290f9d-98ea-4187-a28a-30cf0693ad34")
        .Map<Compze.Tests.Integration.CQRS.UserChangedPassword>("47de038d-4439-4284-808a-9adfc8ab1195")
        .Map<Compze.Tests.Integration.CQRS.UserEvent>("7a17bb59-6879-4411-be4f-3b756544731a")
        .Map<Compze.Tests.Integration.CQRS.UserRegistered>("50ef8427-3a5e-4d05-8599-23f9e7907f09")
        .Map<Compze.Tests.Integration.Tessaging.ServiceBusSpecification.Given_a_backend_endpoint_with_a_command_event_and_query_handler.Experiment_with_unifying_events_and_commands_test.GetUserQuery>("af555894-7aa6-48df-9609-c170a9d54348")
        .Map<Compze.Tests.Integration.Tessaging.ServiceBusSpecification.Given_a_backend_endpoint_with_a_command_event_and_query_handler.Experiment_with_unifying_events_and_commands_test.UserAggregate>("d1b77be0-49f0-47aa-962b-9f6f11f70510")
        .Map<Compze.Tests.Integration.Tessaging.ServiceBusSpecification.Given_a_backend_endpoint_with_a_command_event_and_query_handler.Experiment_with_unifying_events_and_commands_test.UserEvent.Implementation.Root>("27ed9c9b-33c7-4cc7-b150-3ff570d95ae5")
        .Map<Compze.Tests.Integration.Tessaging.ServiceBusSpecification.Given_a_backend_endpoint_with_a_command_event_and_query_handler.Experiment_with_unifying_events_and_commands_test.UserEvent.Implementation.UserRegisteredEvent>("9866dd0f-71e1-4669-ab7c-00fd61934ec1")
        .Map<Compze.Tests.Integration.Tessaging.ServiceBusSpecification.Given_a_backend_endpoint_with_a_command_event_and_query_handler.Experiment_with_unifying_events_and_commands_test.UserEvent.IRoot>("aac7ca88-2f10-4c71-8377-95c2957aee33")
        .Map<Compze.Tests.Integration.Tessaging.ServiceBusSpecification.Given_a_backend_endpoint_with_a_command_event_and_query_handler.Experiment_with_unifying_events_and_commands_test.UserEvent.IUserRegistered>("1441afca-ed6e-421f-9e30-82453164bf2d")
        .Map<Compze.Tests.Integration.Tessaging.ServiceBusSpecification.Given_a_backend_endpoint_with_a_command_event_and_query_handler.Experiment_with_unifying_events_and_commands_test.UserRegistrarAggregate>("507ac014-bb51-45d6-a0d3-834b28a91618")
        .Map<Compze.Tests.Integration.Tessaging.ServiceBusSpecification.Given_a_backend_endpoint_with_a_command_event_and_query_handler.Experiment_with_unifying_events_and_commands_test.UserRegistrarCommand.RegisterUserCommand>("9dfd474b-bb5c-4f49-8eb3-038cd34c55d2")
        .Map<Compze.Tests.Integration.Tessaging.ServiceBusSpecification.Given_a_backend_endpoint_with_a_command_event_and_query_handler.Experiment_with_unifying_events_and_commands_test.UserRegistrarEvent.Implementation.Created>("acae1233-d105-442c-8b5b-9f333a0c6777")
        .Map<Compze.Tests.Integration.Tessaging.ServiceBusSpecification.Given_a_backend_endpoint_with_a_command_event_and_query_handler.Experiment_with_unifying_events_and_commands_test.UserRegistrarEvent.Implementation.Root>("72ab3268-991a-4786-8a05-3b37dfbff49d")
        .Map<Compze.Tests.Integration.Tessaging.ServiceBusSpecification.Given_a_backend_endpoint_with_a_command_event_and_query_handler.Experiment_with_unifying_events_and_commands_test.UserRegistrarEvent.IRoot>("dea42637-517a-414b-a139-04d77696c83e")
        .Map<Compze.Tests.Integration.Tessaging.ServiceBusSpecification.Navigator_specification.GetUserQuery>("59cdf894-46cc-4a34-91e2-6b9f08101887")
        .Map<Compze.Tests.Integration.Tessaging.ServiceBusSpecification.Navigator_specification.RegisterUserCommand>("199c215f-47cb-495e-99d7-06305c4a9e1d")
        .Map<Compze.Tests.Integration.Tessaging.ServiceBusSpecification.Navigator_specification.UserApiStartPageQuery>("6ee0be84-7645-4fd2-9323-006b8c4185c7")
        .Map<Compze.Tests.Integration.Tessaging.ServiceBusSpecification.When_scheduling_commands_to_be_sent_in_the_future.ScheduledCommand>("41d7e106-fbe4-4b82-88b7-a7f8624f0145")
        ;
   }
}