using System;
using Compze.Tests.Common.Sql.DocumentDb;

// ReSharper disable All
namespace Compze.Tests.Integration;

#pragma warning disable IDE1006,IDE0001,IDE0002,IDE0003,IDE0004,IDE0005,IDE0055,CA1050,CA1707,CA1716

/// <summary>
/// This file is automatically generated. Compze will automatically figure out most types that need to go in here, but some types you may need to add yourself.
/// Compze will tell you so in an exception thought, and you can just paste it in here.
/// Regenerate by running the application when type mappings are missing.
/// </summary>
public sealed class AutoGeneratedCurrentAssemblyTypeMapperForRefactoringSupport
{
   public void MapTypesForCurrentAssembly(Action<Guid, Type> map)
   {
      map(new Guid("c6307e34-0601-40f6-ac51-98b09b194ea1"), typeof(Compze.Tessaging.Teventive.Aggregate<Compze.Tests.Integration.CQRS.User, Compze.Tests.Integration.CQRS.IUserEvent, Compze.Tests.Integration.CQRS.UserEvent>));
      map(new Guid("d61343f6-aaf6-4be2-968d-655266831967"), typeof(Compze.Tests.Integration.CQRS.IMigratedAfterUserChangedEmailEvent));
      map(new Guid("8301ba00-13dc-4f2b-b093-8f978df01d4d"), typeof(Compze.Tests.Integration.CQRS.IMigratedAfterUserChangedEmailEvent[]));
      map(new Guid("d724aa33-3072-459f-8aaf-0dc0ee78080e"), typeof(Compze.Tests.Integration.CQRS.IMigratedBeforeUserRegisteredEvent));
      map(new Guid("a0db9f0f-2784-41b3-be1c-f8ffd401137e"), typeof(Compze.Tests.Integration.CQRS.IMigratedBeforeUserRegisteredEvent[]));
      map(new Guid("e1509c09-2a2a-40e1-a50d-b70903ba1a69"), typeof(Compze.Tests.Integration.CQRS.IMigratedReplaceUserChangedPasswordEvent));
      map(new Guid("58667133-c786-40b6-be22-7b02815f7dba"), typeof(Compze.Tests.Integration.CQRS.IMigratedReplaceUserChangedPasswordEvent[]));
      map(new Guid("73b71ba5-e643-4754-92b7-f8183a8a2d49"), typeof(Compze.Tests.Integration.CQRS.IUserChangedEmail));
      map(new Guid("52a976cb-e995-4670-af3d-69a6f943560a"), typeof(Compze.Tests.Integration.CQRS.IUserChangedEmail[]));
      map(new Guid("ee2c3cd9-ad76-4413-802c-bca9fc0e3ae4"), typeof(Compze.Tests.Integration.CQRS.IUserChangedPassword));
      map(new Guid("885e0096-a8c0-4c74-8dca-064923979dc9"), typeof(Compze.Tests.Integration.CQRS.IUserChangedPassword[]));
      map(new Guid("c4cdc095-7e37-4df5-adaa-a5482f3a1092"), typeof(Compze.Tests.Integration.CQRS.IUserEvent));
      map(new Guid("224f6190-430d-4e19-916e-e422fd3d00a6"), typeof(Compze.Tests.Integration.CQRS.IUserEvent[]));
      map(new Guid("f7c61ab8-9a58-41b3-b6f4-0d6be4bf536f"), typeof(Compze.Tests.Integration.CQRS.IUserRegistered));
      map(new Guid("2cdeaa88-921b-4b49-a1e0-5d986fcac283"), typeof(Compze.Tests.Integration.CQRS.IUserRegistered[]));
      map(new Guid("b32167fc-4392-4ca1-8906-0899c1d64bbc"), typeof(Compze.Tests.Integration.CQRS.MigratedAfterUserChangedEmailEvent));
      map(new Guid("dff35132-b601-455c-bf4c-12920dc18ca9"), typeof(Compze.Tests.Integration.CQRS.MigratedAfterUserChangedEmailEvent[]));
      map(new Guid("fb5ace59-f201-4f83-b431-03a8d83b7abc"), typeof(Compze.Tests.Integration.CQRS.MigratedBeforeUserRegisteredEvent));
      map(new Guid("51425c4e-af1d-44a1-9512-157ccff95864"), typeof(Compze.Tests.Integration.CQRS.MigratedBeforeUserRegisteredEvent[]));
      map(new Guid("8a4ab62b-4552-46bf-bffd-ff1dee6d8287"), typeof(Compze.Tests.Integration.CQRS.MigratedReplaceUserChangedPasswordEvent));
      map(new Guid("0cfdf0bd-e0b6-44e1-a9fa-c96356ad62bc"), typeof(Compze.Tests.Integration.CQRS.MigratedReplaceUserChangedPasswordEvent[]));
      map(new Guid("2af06a80-af9b-47ef-88ac-e1535640936f"), typeof(Compze.Tests.Integration.CQRS.User));
      map(new Guid("8d284efa-daa6-4b69-8589-92823de72706"), typeof(Compze.Tests.Integration.CQRS.User[]));
      map(new Guid("5eaccdbf-af71-4e62-9d39-7f611232c731"), typeof(Compze.Tests.Integration.CQRS.UserChangedEmail));
      map(new Guid("fba4c80d-6a32-477c-a834-4db024a0abe1"), typeof(Compze.Tests.Integration.CQRS.UserChangedEmail[]));
      map(new Guid("ea13f473-6f67-4d8c-981f-fe0a69f96964"), typeof(Compze.Tests.Integration.CQRS.UserChangedPassword));
      map(new Guid("953d19e7-c4d4-4cc7-9f47-cf3472e7af4a"), typeof(Compze.Tests.Integration.CQRS.UserChangedPassword[]));
      map(new Guid("7a2943d2-6162-4b84-9d00-6933d21167b2"), typeof(Compze.Tests.Integration.CQRS.UserEvent));
      map(new Guid("488b7672-cc5f-47b7-a346-ab0ebe717e42"), typeof(Compze.Tests.Integration.CQRS.UserEvent[]));
      map(new Guid("f099b9ef-5561-472b-b7d6-4f29aed9a9c0"), typeof(Compze.Tests.Integration.CQRS.UserRegistered));
      map(new Guid("09320967-0e73-4e05-8854-6089c9cbf809"), typeof(Compze.Tests.Integration.CQRS.UserRegistered[]));
      map(new Guid("13ac8eae-a95d-4297-96dd-3c6d699f9651"), typeof(System.Collections.Generic.HashSet<User>));
      map(new Guid("268f8c42-cd51-4cb9-aa28-9a5f579ff1f0"), typeof(Email));
   }
}
