using System;
using Compze.Core.Tessaging.Public;
using Compze.Core.Tessaging.Teventive.Public.Taggregates.BaseClasses.Public;
using Compze.Tests.Integration.CQRS.QueryModels.AutoGenerated.Domain;
using Compze.Tests.Integration.CQRS.QueryModels.AutoGenerated.Domain.UI.QueryModels;
using Compze.Tests.Integration.Tessaging.ServiceBusSpecification;
using Compze.Tests.Integration.Tessaging.ServiceBusSpecification.Given_a_backend_endpoint_with_a_tommand_tevent_and_tuery_handler;

// ReSharper disable All
namespace Compze.Tests.Integration;

#pragma warning disable IDE1006,IDE0001,IDE0002,IDE0003,IDE0004,IDE0005,IDE0055,CA1050,CA1707,CA1716

/// <summary>
/// This file is automatically generated. Compze will automatically figure out most types that need to go in here, but some types you may need to add yourself.
/// Compze will tell you so in an exception thought, and you can just paste it in here.
/// Regenerate by running the application when type mappings are missing.
/// </summary>
public sealed class AutoGeneratedCurrentAssemblyTypeMapperForRefactoringSupport
{
   public void MapTypesForCurrentAssembly(Action<string, Type> map)
   {
      map("3bc347af-6174-41fb-b690-197d26a636b1", typeof(TessageTypes.Remotable.AtMostOnce.AtMostOnceTypermediaTommand<Navigator_specification.UserRegisteredConfirmationResource>));
      map("d6ca0443-eaca-42bd-9418-1b67567d3523", typeof(Taggregate<Compze.Tests.Integration.CQRS.User, Compze.Tests.Integration.CQRS.IUserTevent, Compze.Tests.Integration.CQRS.UserTevent>));
      map("99302c63-3bfc-4e81-a678-16e73ff982c5", typeof(Compze.Tests.Integration.CQRS.IMigratedAfterUserChangedEmailTevent));
      map("b4764b35-b1cf-4af5-a0df-0d7704c6a2d0", typeof(Compze.Tests.Integration.CQRS.IMigratedAfterUserChangedEmailTevent[]));
      map("3cd859f1-a710-46a6-b3e2-e6b251db6467", typeof(Compze.Tests.Integration.CQRS.IMigratedBeforeUserRegisteredTevent));
      map("b0ef6740-8c7c-48ff-961b-32eac4e2dbea", typeof(Compze.Tests.Integration.CQRS.IMigratedBeforeUserRegisteredTevent[]));
      map("e2a8b2fb-c6b1-455b-a79b-e94b80b44604", typeof(Compze.Tests.Integration.CQRS.IMigratedReplaceUserChangedPasswordTevent));
      map("f456950d-0a4f-4b6c-8576-1b6031a7d699", typeof(Compze.Tests.Integration.CQRS.IMigratedReplaceUserChangedPasswordTevent[]));
      map("30e74877-d75a-430c-b466-a50f0dd928b3", typeof(Compze.Tests.Integration.CQRS.ISomeTevent));
      map("741882b8-0c02-431c-aeec-ded1b4c70be1", typeof(Compze.Tests.Integration.CQRS.ISomeTevent[]));
      map("3996caab-5f71-4dd5-878f-83a0100f354e", typeof(Compze.Tests.Integration.CQRS.IUserChangedEmail));
      map("7bc33845-eb79-4284-b689-d8b773279220", typeof(Compze.Tests.Integration.CQRS.IUserChangedEmail[]));
      map("190ee130-3c7c-4369-af3c-3a5d96ec2e2b", typeof(Compze.Tests.Integration.CQRS.IUserChangedPassword));
      map("65921ab7-93c2-46ac-9307-9d35672e0572", typeof(Compze.Tests.Integration.CQRS.IUserChangedPassword[]));
      map("2e2ec47b-e609-4f62-8ba6-1d322936e2c8", typeof(Compze.Tests.Integration.CQRS.IUserTevent));
      map("f46fecb0-f15a-4321-a10c-c3a2a4c57a0e", typeof(Compze.Tests.Integration.CQRS.IUserTevent[]));
      map("156f8363-0bd9-4553-b4b9-33a7c2825d02", typeof(Compze.Tests.Integration.CQRS.IUserRegistered));
      map("9424332f-fec3-47ca-8c63-e6988df1ff57", typeof(Compze.Tests.Integration.CQRS.IUserRegistered[]));
      map("b88c60c5-1142-4e6d-aca5-abb80f13496d", typeof(Compze.Tests.Integration.CQRS.MigratedAfterUserChangedEmailTevent));
      map("f0829bf7-8030-4bbc-9ca7-7067f5c21d3b", typeof(Compze.Tests.Integration.CQRS.MigratedAfterUserChangedEmailTevent[]));
      map("4909cca8-2391-4541-8bb3-5b73e5d8fa3c", typeof(Compze.Tests.Integration.CQRS.MigratedBeforeUserRegisteredTevent));
      map("288dfb26-a905-4bf1-a4c6-53677a28c8b6", typeof(Compze.Tests.Integration.CQRS.MigratedBeforeUserRegisteredTevent[]));
      map("17b3dd26-0633-4525-824c-4f695435975a", typeof(Compze.Tests.Integration.CQRS.MigratedReplaceUserChangedPasswordTevent));
      map("b60a7d8f-7687-4229-9234-a88feebc4afa", typeof(Compze.Tests.Integration.CQRS.MigratedReplaceUserChangedPasswordTevent[]));
      map("b5f31ed2-fdc1-4342-927c-60cb524b462b", typeof(Compze.Tests.Integration.CQRS.SomeTevent));
      map("d7df1606-c2b8-4a1a-9960-964a7ef5a318", typeof(Compze.Tests.Integration.CQRS.SomeTevent[]));
      map("b07901c6-2b5d-4348-8894-4603773ce698", typeof(Compze.Tests.Integration.CQRS.User));
      map("18b8b63e-e671-4714-a177-6788717f13e2", typeof(Compze.Tests.Integration.CQRS.User[]));
      map("00ef87d3-3a51-431d-9e63-ca230725e241", typeof(Compze.Tests.Integration.CQRS.UserChangedEmail));
      map("1c233992-67d5-4e36-becc-a16c3bc9ae56", typeof(Compze.Tests.Integration.CQRS.UserChangedEmail[]));
      map("ca16af4b-f792-434d-87ec-9e879b6ac079", typeof(Compze.Tests.Integration.CQRS.UserChangedPassword));
      map("89500ca1-8f0f-433b-94ec-2526f3549ca2", typeof(Compze.Tests.Integration.CQRS.UserChangedPassword[]));
      map("1db99ec2-c861-4fb9-b40e-aba68d827a39", typeof(Compze.Tests.Integration.CQRS.UserTevent));
      map("7698b652-bdbd-46f4-a2c4-9b32092760ef", typeof(Compze.Tests.Integration.CQRS.UserTevent[]));
      map("2cd960ed-51aa-4a15-a620-685dad7b0566", typeof(Compze.Tests.Integration.CQRS.UserRegistered));
      map("e023d973-79ea-4614-a38d-e69e5695da51", typeof(Compze.Tests.Integration.CQRS.UserRegistered[]));
      map("5e14f677-4653-490c-af17-1dd0ab3bc817", typeof(System.Collections.Generic.HashSet<Compze.Tests.Common.Sql.DocumentDb.User>));
      map("5a734c6c-5c48-41fc-aa88-69929014c9d2", typeof(Compze.Tests.Common.Sql.DocumentDb.Email));
      map("dec2aa55-eb86-4b37-ac6a-e7cd4987ff4b", typeof(Navigator_specification.GetUserTuery));
      map("f205e0f1-b267-47e4-af0e-c72fa7b20f8b", typeof(Navigator_specification.GetUserTuery[]));
      map("0a6eb5a4-13b9-419c-a145-d6cd3df5c420", typeof(Navigator_specification.RegisterUserTypermediaTommand));
      map("d7704cf4-9ed0-4210-90cb-233279a4ebe5", typeof(Navigator_specification.RegisterUserTypermediaTommand[]));
      map("c270b8eb-b4e1-4bd8-b0de-dae0e2eb14ce", typeof(Navigator_specification.UserApiStartPageTuery));
      map("5505d1c1-bd1a-42d6-9291-e2cf6adcb5fe", typeof(Navigator_specification.UserApiStartPageTuery[]));
      map("108a37b8-953d-4cd2-af25-b7c853056e8b", typeof(When_scheduling_tommands_to_be_sent_in_the_future.ScheduledTommand));
      map("14d419b6-e350-4c22-9df8-0fffc48ea15c", typeof(When_scheduling_tommands_to_be_sent_in_the_future.ScheduledTommand[]));
      map("c99427b6-af20-4cac-8170-927f22f8850b", typeof(Experiment_with_unifying_tevents_and_tommands_test.GetUserTuery));
      map("74774350-bc4e-410b-80bd-e0d7538aecec", typeof(Experiment_with_unifying_tevents_and_tommands_test.GetUserTuery[]));
      map("c2ce6605-fbf7-499d-ae26-e3451cb1be0b", typeof(Experiment_with_unifying_tevents_and_tommands_test.UserTaggregate));
      map("b685ab40-f44e-47e1-a5a7-962dbab56ee3", typeof(Experiment_with_unifying_tevents_and_tommands_test.UserTaggregate[]));
      map("ac02b095-ede5-4092-8ff1-62b2f42ebfc3", typeof(Experiment_with_unifying_tevents_and_tommands_test.UserTevent));
      map("55660e79-c6ed-4f7b-8290-db95dc962db6", typeof(Experiment_with_unifying_tevents_and_tommands_test.UserTevent[]));
      map("8db983bd-7921-4211-8541-a3cafc828e3e", typeof(Experiment_with_unifying_tevents_and_tommands_test.UserTevent.UserRegisteredTevent));
      map("4338cecf-d92d-4903-ac2e-884a1bdc64a5", typeof(Experiment_with_unifying_tevents_and_tommands_test.UserTevent.UserRegisteredTevent[]));
      map("683a13a6-7d2b-40b9-b1ce-c45c7cafc960", typeof(Experiment_with_unifying_tevents_and_tommands_test.IUserTevent));
      map("c0143112-33a7-4a5d-8533-619e5bf729a3", typeof(Experiment_with_unifying_tevents_and_tommands_test.IUserTevent[]));
      map("e5a8d8da-5c2c-4ba0-ac28-cb7e1b02134f", typeof(Experiment_with_unifying_tevents_and_tommands_test.IUserTevent.UserRegistered));
      map("370361c3-fa3c-4f1a-8137-eb9d434029b0", typeof(Experiment_with_unifying_tevents_and_tommands_test.IUserTevent.UserRegistered[]));
      map("91ea880a-606b-43aa-b586-f56038262578", typeof(Experiment_with_unifying_tevents_and_tommands_test.UserRegistrarTaggregate));
      map("25c87d54-badb-4678-88d8-9393f06fc762", typeof(Experiment_with_unifying_tevents_and_tommands_test.UserRegistrarTaggregate[]));
      map("3893e38f-eea6-412d-bde0-0b2e7c10f5e2", typeof(Experiment_with_unifying_tevents_and_tommands_test.UserRegistrarTommand.RegisterUserTypermediaTommand));
      map("4f74e8bb-94d2-420c-a871-d0f6375920e5", typeof(Experiment_with_unifying_tevents_and_tommands_test.UserRegistrarTommand.RegisterUserTypermediaTommand[]));
      map("eebf0412-f759-49d1-bd7e-cc764dffae99", typeof(Experiment_with_unifying_tevents_and_tommands_test.UserRegistrarTevent.Created));
      map("b33f5975-2ffc-4383-8c09-36a7175cd0a9", typeof(Experiment_with_unifying_tevents_and_tommands_test.UserRegistrarTevent.Created[]));
      map("e106e812-9ab4-4256-aad5-1f9ef8602a94", typeof(Experiment_with_unifying_tevents_and_tommands_test.UserRegistrarTevent));
      map("83224da8-0420-4855-8036-f8543ffeefa3", typeof(Experiment_with_unifying_tevents_and_tommands_test.UserRegistrarTevent[]));
      map("84e7eb50-da79-44a4-aab8-ac8332874732", typeof(Experiment_with_unifying_tevents_and_tommands_test.IUserRegistrarTevent));
      map("3814bc1c-c4b6-4e54-9861-11a992ec4fde", typeof(Experiment_with_unifying_tevents_and_tommands_test.IUserRegistrarTevent[]));
      map("ff5ab473-2ec6-4e4f-a5f7-acf07eee2e91", typeof(TessageTypes.Remotable.AtMostOnce.AtMostOnceTypermediaTommand<Experiment_with_unifying_tevents_and_tommands_test.RegisterUserResult>));
      map("5332e68a-ea2a-4a48-b044-0f6e03ddd113", typeof(IAccountTevent));
      map("67ce90bd-2cbe-411a-bac7-eb197e4b163f", typeof(IAccountTevent[]));
      map("86ed29e7-f686-4537-aa82-87c7a0101043", typeof(IAccountTevent.Deleted));
      map("29ede577-e099-4a7c-9f15-96a63fc7c613", typeof(IAccountTevent.Deleted[]));
      map("5c729264-90f2-44f3-87fd-087d112b0e75", typeof(IAccountTevent.IAccountRegisteredTevent));
      map("9ebcb3f4-2be2-4236-962b-e7ca18f04cdd", typeof(IAccountTevent.IAccountRegisteredTevent[]));
      map("224b5fe4-4c91-4c7a-9765-ceee9514a8d2", typeof(IAccountTevent.IEmailChanged));
      map("37a3fb22-4300-4a3d-bc72-42f2c7c4cf55", typeof(IAccountTevent.IEmailChanged[]));
      map("ecb9b22e-814e-4432-af83-42db5943f146", typeof(AccountTevent.Deleted));
      map("a346db46-842c-4b0b-93ba-906c4ca80a07", typeof(AccountTevent.Deleted[]));
      map("960522ba-08a4-45d1-9df0-f37fc35c3100", typeof(AccountTevent.AccountRegisteredTevent));
      map("3339b25e-9db7-4028-bd62-b6a39aba59d6", typeof(AccountTevent.AccountRegisteredTevent[]));
      map("b2b9587a-9efa-42b7-8242-4099439599a8", typeof(AccountTevent.EmailChanged));
      map("519ab475-4734-4ace-882d-8404a462ffec", typeof(AccountTevent.EmailChanged[]));
      map("c301b17e-3fc6-43f5-ac77-2b78c90fb3be", typeof(IAccountTevent.PropertyUpdated.Email));
      map("166686f1-b276-4f87-b0c6-799b5f2cc008", typeof(IAccountTevent.PropertyUpdated.Email[]));
      map("3c567c7c-db63-4834-9623-5c846138e1d3", typeof(IAccountTevent.PropertyUpdated.Password));
      map("2485e9b7-d09e-410c-90a7-ba5ed86da19c", typeof(IAccountTevent.PropertyUpdated.Password[]));
      map("3d805028-547b-4c63-bbab-1c9b7a2f69b0", typeof(Compze.Tests.Integration.CQRS.QueryModels.AutoGenerated.Domain.AccountTevent));
      map("e687cbda-629a-4b9b-a5ec-1a3964ee6e59", typeof(MyAccount));
      map("be184a8e-45a7-4af3-97af-f3c71ad649a4", typeof(MyAccount[]));
      map("9ca59132-20b5-4f68-bfa0-ba79c993f873", typeof(MyAccountQueryModel));
      map("288adbac-d8a9-43b6-828e-089e56f5ee2b", typeof(MyAccountQueryModel[]));
   }
}
