using Newtonsoft.Json;
using Newtonsoft.Json.Serialization;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Reflection;
using Compze.Utilities.SystemCE;

#pragma warning disable CA2326 // TypeNameHandling is safe for testing serialization
#pragma warning disable CA2327

namespace Compze.Tests.Infrastructure.Fluent.Serialization;

static class TestingJsonSettings
{
   internal static readonly JsonSerializerSettings AllMembers = CreateSettings(new AllMembersContractResolver());
   internal static readonly JsonSerializerSettings InternalAndPublicMembers = CreateSettings(new InternalMembersContractResolver());
   internal static readonly JsonSerializerSettings PublicMembers = CreateSettings(new PublicMembersContractResolver());

   internal static JsonSerializerSettings CreateSettingsWithExclusions(JsonSerializerSettings baseSettings, IReadOnlySet<MemberInfo> excludedMembers)
   {
      var baseResolver = baseSettings.ContractResolver as MemberFilteringContractResolver 
                         ?? throw new ArgumentException("Base settings must have a MemberFilteringContractResolver", nameof(baseSettings));
      var excludingResolver = new ExcludingMembersContractResolver(baseResolver, excludedMembers);
      
      var settings = new JsonSerializerSettings
      {
         TypeNameHandling = baseSettings.TypeNameHandling,
         TypeNameAssemblyFormatHandling = baseSettings.TypeNameAssemblyFormatHandling,
         Formatting = baseSettings.Formatting,
         ContractResolver = excludingResolver,
         ReferenceLoopHandling = baseSettings.ReferenceLoopHandling,
         MaxDepth = baseSettings.MaxDepth
      };
      
      return settings;
   }

   static JsonSerializerSettings CreateSettings(IContractResolver resolver) =>
      new()
      {
         TypeNameHandling = TypeNameHandling.All,
         TypeNameAssemblyFormatHandling = TypeNameAssemblyFormatHandling.Simple,
         Formatting = Formatting.Indented,
         ContractResolver = resolver,
         ReferenceLoopHandling = ReferenceLoopHandling.Ignore,
         MaxDepth = 32
      };
}

abstract class MemberFilteringContractResolver : DefaultContractResolver
{
   protected override JsonProperty CreateProperty(MemberInfo member, MemberSerialization memberSerialization)
   {
      var property = base.CreateProperty(member, memberSerialization);
      property.Readable = true;
      property.Writable = true;
      return property;
   }

   internal IList<JsonProperty> CreatePropertiesInternal(Type type, MemberSerialization memberSerialization) 
      => CreateProperties(type, memberSerialization);

   protected override IList<JsonProperty> CreateProperties(Type type, MemberSerialization memberSerialization)
   {
      var allProperties = type.GetProperties(BindingFlags.Public | BindingFlags.NonPublic | BindingFlags.Instance)
                              .Where(ShouldIncludeProperty);

      var allFields = type.GetFields(BindingFlags.Public | BindingFlags.NonPublic | BindingFlags.Instance)
                          .Where(ShouldIncludeField)
                          .Where(f => !IsAutoGeneratedBackingField(f));

      return allProperties.Cast<MemberInfo>()
                          .Concat(allFields)
                          .Select(m => CreateProperty(m, memberSerialization))
                          .ToList();
   }

   static bool IsAutoGeneratedBackingField(FieldInfo field) => 
      field.Name.StartsWith('<') && field.Name.Contains(">k__BackingField", StringComparison.Ordinal);

   protected abstract bool ShouldIncludeProperty(PropertyInfo property);
   protected abstract bool ShouldIncludeField(FieldInfo field);
}

class AllMembersContractResolver : MemberFilteringContractResolver
{
   protected override bool ShouldIncludeProperty(PropertyInfo property) => true;
   protected override bool ShouldIncludeField(FieldInfo field) => true;
}

class InternalMembersContractResolver : MemberFilteringContractResolver
{
   protected override bool ShouldIncludeProperty(PropertyInfo property) =>
      property.GetMethod is { IsAssembly: true } or { IsFamilyOrAssembly: true } or { IsFamily: true };

   protected override bool ShouldIncludeField(FieldInfo field) =>
      field.IsAssembly || field.IsFamilyOrAssembly || field.IsFamily;
}

class PublicMembersContractResolver : MemberFilteringContractResolver
{
   protected override bool ShouldIncludeProperty(PropertyInfo property) => property.GetMethod?.IsPublic ?? false;
   protected override bool ShouldIncludeField(FieldInfo field) => field.IsPublic;
}

class ExcludingMembersContractResolver : DefaultContractResolver
{
   readonly MemberFilteringContractResolver _baseResolver;
   readonly IReadOnlySet<MemberInfo> _excludedMembers;

   public ExcludingMembersContractResolver(MemberFilteringContractResolver baseResolver, IReadOnlySet<MemberInfo> excludedMembers)
   {
      _baseResolver = baseResolver;
      _excludedMembers = excludedMembers;
   }

   protected override IList<JsonProperty> CreateProperties(Type type, MemberSerialization memberSerialization)
   {
      var properties = _baseResolver.CreatePropertiesInternal(type, memberSerialization);
      return properties.Where(p => !ShouldExclude(type, p.PropertyName)).ToList();
   }

   bool ShouldExclude(Type objectType, string? propertyName)
   {
      if (string.IsNullOrEmpty(propertyName))
         return false;

      foreach (var excludedMember in _excludedMembers)
      {
         if (propertyName == excludedMember.Name && excludedMember.DeclaringType.NotNull().IsAssignableFrom(objectType))
            return true;
      }

      return false;
   }
}
