using Compze.Tests.Performance.Internals.Serialization;

// ReSharper disable All
namespace Compze.Tests.Performance.Internals;

#pragma warning disable IDE1006,IDE0001,IDE0002,IDE0003,IDE0004,IDE0005,IDE0055,CA1050,CA1707,CA1716

/// <summary>
/// This file is automatically generated. Compze will automatically figure out most types that need to go in here, but some types you may need to add yourself.
/// Compze will tell you so in an exception thought, and you can just paste it in here.
/// Regenerate by running the application when type mappings are missing.
/// </summary>
public sealed class AutoGeneratedCurrentAssemblyTypeMapperForRefactoringSupport
{
   public void MapTypesForCurrentAssembly(Action<string, Type> map)
   {
      map("7b513dd1-e697-4544-83c3-06c17819eaeb", typeof(TestTevent));
      map("1061c1d5-f5cd-4885-88ad-1fd48d405ff0", typeof(Compze.Tests.Performance.Internals.Tessaging.Hypermedia.PerformanceTestBase.MyRemoteTuery));
   }
}
