using System;
using Compze.Tests.Integration.XUnit.Tessaging.ServiceBusSpecification;
using Compze.Tests.Integration.XUnit.Tessaging.ServiceBusSpecification.Given_a_backend_endpoint_with_a_command_event_and_query_handler;

// ReSharper disable All
namespace Compze.Tests.Integration.XUnit;

#pragma warning disable IDE1006,IDE0001,IDE0002,IDE0003,IDE0004,IDE0005,IDE0055,CA1050,CA1707,CA1716

/// <summary>
/// This file is automatically generated. Compze will automatically figure out most types that need to go in here, but some types you may need to add yourself.
/// Compze will tell you so in an exception thought, and you can just paste it in here.
/// Regenerate by running the application when type mappings are missing.
/// </summary>
public sealed class AutoGeneratedCurrentAssemblyTypeMapperForRefactoringSupport
{
   public void MapTypesForCurrentAssembly(Action<Guid, Type> map)
   {
      map(new Guid("3bc347af-6174-41fb-b690-197d26a636b1"), typeof(Compze.Tessaging.Abstractions.MessageTypes.Remotable.AtMostOnce.AtMostOnceCommand<Navigator_specification.UserRegisteredConfirmationResource>));
      map(new Guid("d6ca0443-eaca-42bd-9418-1b67567d3523"), typeof(Compze.Tessaging.Teventive.Aggregate<Compze.Tests.Integration.XUnit.CQRS.User, Compze.Tests.Integration.XUnit.CQRS.IUserEvent, Compze.Tests.Integration.XUnit.CQRS.UserEvent>));
      map(new Guid("99302c63-3bfc-4e81-a678-16e73ff982c5"), typeof(Compze.Tests.Integration.XUnit.CQRS.IMigratedAfterUserChangedEmailEvent));
      map(new Guid("b4764b35-b1cf-4af5-a0df-0d7704c6a2d0"), typeof(Compze.Tests.Integration.XUnit.CQRS.IMigratedAfterUserChangedEmailEvent[]));
      map(new Guid("3cd859f1-a710-46a6-b3e2-e6b251db6467"), typeof(Compze.Tests.Integration.XUnit.CQRS.IMigratedBeforeUserRegisteredEvent));
      map(new Guid("b0ef6740-8c7c-48ff-961b-32eac4e2dbea"), typeof(Compze.Tests.Integration.XUnit.CQRS.IMigratedBeforeUserRegisteredEvent[]));
      map(new Guid("e2a8b2fb-c6b1-455b-a79b-e94b80b44604"), typeof(Compze.Tests.Integration.XUnit.CQRS.IMigratedReplaceUserChangedPasswordEvent));
      map(new Guid("f456950d-0a4f-4b6c-8576-1b6031a7d699"), typeof(Compze.Tests.Integration.XUnit.CQRS.IMigratedReplaceUserChangedPasswordEvent[]));
      map(new Guid("30e74877-d75a-430c-b466-a50f0dd928b3"), typeof(Compze.Tests.Integration.XUnit.CQRS.ISomeEvent));
      map(new Guid("741882b8-0c02-431c-aeec-ded1b4c70be1"), typeof(Compze.Tests.Integration.XUnit.CQRS.ISomeEvent[]));
      map(new Guid("3996caab-5f71-4dd5-878f-83a0100f354e"), typeof(Compze.Tests.Integration.XUnit.CQRS.IUserChangedEmail));
      map(new Guid("7bc33845-eb79-4284-b689-d8b773279220"), typeof(Compze.Tests.Integration.XUnit.CQRS.IUserChangedEmail[]));
      map(new Guid("190ee130-3c7c-4369-af3c-3a5d96ec2e2b"), typeof(Compze.Tests.Integration.XUnit.CQRS.IUserChangedPassword));
      map(new Guid("65921ab7-93c2-46ac-9307-9d35672e0572"), typeof(Compze.Tests.Integration.XUnit.CQRS.IUserChangedPassword[]));
      map(new Guid("2e2ec47b-e609-4f62-8ba6-1d322936e2c8"), typeof(Compze.Tests.Integration.XUnit.CQRS.IUserEvent));
      map(new Guid("f46fecb0-f15a-4321-a10c-c3a2a4c57a0e"), typeof(Compze.Tests.Integration.XUnit.CQRS.IUserEvent[]));
      map(new Guid("156f8363-0bd9-4553-b4b9-33a7c2825d02"), typeof(Compze.Tests.Integration.XUnit.CQRS.IUserRegistered));
      map(new Guid("9424332f-fec3-47ca-8c63-e6988df1ff57"), typeof(Compze.Tests.Integration.XUnit.CQRS.IUserRegistered[]));
      map(new Guid("b88c60c5-1142-4e6d-aca5-abb80f13496d"), typeof(Compze.Tests.Integration.XUnit.CQRS.MigratedAfterUserChangedEmailEvent));
      map(new Guid("f0829bf7-8030-4bbc-9ca7-7067f5c21d3b"), typeof(Compze.Tests.Integration.XUnit.CQRS.MigratedAfterUserChangedEmailEvent[]));
      map(new Guid("4909cca8-2391-4541-8bb3-5b73e5d8fa3c"), typeof(Compze.Tests.Integration.XUnit.CQRS.MigratedBeforeUserRegisteredEvent));
      map(new Guid("288dfb26-a905-4bf1-a4c6-53677a28c8b6"), typeof(Compze.Tests.Integration.XUnit.CQRS.MigratedBeforeUserRegisteredEvent[]));
      map(new Guid("17b3dd26-0633-4525-824c-4f695435975a"), typeof(Compze.Tests.Integration.XUnit.CQRS.MigratedReplaceUserChangedPasswordEvent));
      map(new Guid("b60a7d8f-7687-4229-9234-a88feebc4afa"), typeof(Compze.Tests.Integration.XUnit.CQRS.MigratedReplaceUserChangedPasswordEvent[]));
      map(new Guid("b5f31ed2-fdc1-4342-927c-60cb524b462b"), typeof(Compze.Tests.Integration.XUnit.CQRS.SomeEvent));
      map(new Guid("d7df1606-c2b8-4a1a-9960-964a7ef5a318"), typeof(Compze.Tests.Integration.XUnit.CQRS.SomeEvent[]));
      map(new Guid("b07901c6-2b5d-4348-8894-4603773ce698"), typeof(Compze.Tests.Integration.XUnit.CQRS.User));
      map(new Guid("18b8b63e-e671-4714-a177-6788717f13e2"), typeof(Compze.Tests.Integration.XUnit.CQRS.User[]));
      map(new Guid("00ef87d3-3a51-431d-9e63-ca230725e241"), typeof(Compze.Tests.Integration.XUnit.CQRS.UserChangedEmail));
      map(new Guid("1c233992-67d5-4e36-becc-a16c3bc9ae56"), typeof(Compze.Tests.Integration.XUnit.CQRS.UserChangedEmail[]));
      map(new Guid("ca16af4b-f792-434d-87ec-9e879b6ac079"), typeof(Compze.Tests.Integration.XUnit.CQRS.UserChangedPassword));
      map(new Guid("89500ca1-8f0f-433b-94ec-2526f3549ca2"), typeof(Compze.Tests.Integration.XUnit.CQRS.UserChangedPassword[]));
      map(new Guid("1db99ec2-c861-4fb9-b40e-aba68d827a39"), typeof(Compze.Tests.Integration.XUnit.CQRS.UserEvent));
      map(new Guid("7698b652-bdbd-46f4-a2c4-9b32092760ef"), typeof(Compze.Tests.Integration.XUnit.CQRS.UserEvent[]));
      map(new Guid("2cd960ed-51aa-4a15-a620-685dad7b0566"), typeof(Compze.Tests.Integration.XUnit.CQRS.UserRegistered));
      map(new Guid("e023d973-79ea-4614-a38d-e69e5695da51"), typeof(Compze.Tests.Integration.XUnit.CQRS.UserRegistered[]));
      map(new Guid("5e14f677-4653-490c-af17-1dd0ab3bc817"), typeof(System.Collections.Generic.HashSet<Compze.Tests.Common.Sql.DocumentDb.User>));
      map(new Guid("5a734c6c-5c48-41fc-aa88-69929014c9d2"), typeof(Compze.Tests.Common.Sql.DocumentDb.Email));
      map(new Guid("dec2aa55-eb86-4b37-ac6a-e7cd4987ff4b"), typeof(Navigator_specification.GetUserQuery));
      map(new Guid("f205e0f1-b267-47e4-af0e-c72fa7b20f8b"), typeof(Navigator_specification.GetUserQuery[]));
      map(new Guid("0a6eb5a4-13b9-419c-a145-d6cd3df5c420"), typeof(Navigator_specification.RegisterUserCommand));
      map(new Guid("d7704cf4-9ed0-4210-90cb-233279a4ebe5"), typeof(Navigator_specification.RegisterUserCommand[]));
      map(new Guid("c270b8eb-b4e1-4bd8-b0de-dae0e2eb14ce"), typeof(Navigator_specification.UserApiStartPageQuery));
      map(new Guid("5505d1c1-bd1a-42d6-9291-e2cf6adcb5fe"), typeof(Navigator_specification.UserApiStartPageQuery[]));
      map(new Guid("108a37b8-953d-4cd2-af25-b7c853056e8b"), typeof(When_scheduling_commands_to_be_sent_in_the_future.ScheduledCommand));
      map(new Guid("14d419b6-e350-4c22-9df8-0fffc48ea15c"), typeof(When_scheduling_commands_to_be_sent_in_the_future.ScheduledCommand[]));
      map(new Guid("c99427b6-af20-4cac-8170-927f22f8850b"), typeof(Experiment_with_unifying_events_and_commands_test.GetUserQuery));
      map(new Guid("74774350-bc4e-410b-80bd-e0d7538aecec"), typeof(Experiment_with_unifying_events_and_commands_test.GetUserQuery[]));
      map(new Guid("c2ce6605-fbf7-499d-ae26-e3451cb1be0b"), typeof(Experiment_with_unifying_events_and_commands_test.UserAggregate));
      map(new Guid("b685ab40-f44e-47e1-a5a7-962dbab56ee3"), typeof(Experiment_with_unifying_events_and_commands_test.UserAggregate[]));
      map(new Guid("ac02b095-ede5-4092-8ff1-62b2f42ebfc3"), typeof(Experiment_with_unifying_events_and_commands_test.UserEvent.Implementation.Root));
      map(new Guid("55660e79-c6ed-4f7b-8290-db95dc962db6"), typeof(Experiment_with_unifying_events_and_commands_test.UserEvent.Implementation.Root[]));
      map(new Guid("8db983bd-7921-4211-8541-a3cafc828e3e"), typeof(Experiment_with_unifying_events_and_commands_test.UserEvent.Implementation.UserRegisteredEvent));
      map(new Guid("4338cecf-d92d-4903-ac2e-884a1bdc64a5"), typeof(Experiment_with_unifying_events_and_commands_test.UserEvent.Implementation.UserRegisteredEvent[]));
      map(new Guid("683a13a6-7d2b-40b9-b1ce-c45c7cafc960"), typeof(Experiment_with_unifying_events_and_commands_test.UserEvent.IRoot));
      map(new Guid("c0143112-33a7-4a5d-8533-619e5bf729a3"), typeof(Experiment_with_unifying_events_and_commands_test.UserEvent.IRoot[]));
      map(new Guid("e5a8d8da-5c2c-4ba0-ac28-cb7e1b02134f"), typeof(Experiment_with_unifying_events_and_commands_test.UserEvent.IUserRegistered));
      map(new Guid("370361c3-fa3c-4f1a-8137-eb9d434029b0"), typeof(Experiment_with_unifying_events_and_commands_test.UserEvent.IUserRegistered[]));
      map(new Guid("91ea880a-606b-43aa-b586-f56038262578"), typeof(Experiment_with_unifying_events_and_commands_test.UserRegistrarAggregate));
      map(new Guid("25c87d54-badb-4678-88d8-9393f06fc762"), typeof(Experiment_with_unifying_events_and_commands_test.UserRegistrarAggregate[]));
      map(new Guid("3893e38f-eea6-412d-bde0-0b2e7c10f5e2"), typeof(Experiment_with_unifying_events_and_commands_test.UserRegistrarCommand.RegisterUserCommand));
      map(new Guid("4f74e8bb-94d2-420c-a871-d0f6375920e5"), typeof(Experiment_with_unifying_events_and_commands_test.UserRegistrarCommand.RegisterUserCommand[]));
      map(new Guid("eebf0412-f759-49d1-bd7e-cc764dffae99"), typeof(Experiment_with_unifying_events_and_commands_test.UserRegistrarEvent.Implementation.Created));
      map(new Guid("b33f5975-2ffc-4383-8c09-36a7175cd0a9"), typeof(Experiment_with_unifying_events_and_commands_test.UserRegistrarEvent.Implementation.Created[]));
      map(new Guid("e106e812-9ab4-4256-aad5-1f9ef8602a94"), typeof(Experiment_with_unifying_events_and_commands_test.UserRegistrarEvent.Implementation.Root));
      map(new Guid("83224da8-0420-4855-8036-f8543ffeefa3"), typeof(Experiment_with_unifying_events_and_commands_test.UserRegistrarEvent.Implementation.Root[]));
      map(new Guid("84e7eb50-da79-44a4-aab8-ac8332874732"), typeof(Experiment_with_unifying_events_and_commands_test.UserRegistrarEvent.IRoot));
      map(new Guid("3814bc1c-c4b6-4e54-9861-11a992ec4fde"), typeof(Experiment_with_unifying_events_and_commands_test.UserRegistrarEvent.IRoot[]));
      map(new Guid("ff5ab473-2ec6-4e4f-a5f7-acf07eee2e91"), typeof(Compze.Tessaging.Abstractions.MessageTypes.Remotable.AtMostOnce.AtMostOnceCommand<Experiment_with_unifying_events_and_commands_test.RegisterUserResult>));
      map(new Guid("8ee4d565-feda-42a2-9c3b-2482c0bc8753"),
          typeof(Compze.Tessaging.Teventive.Aggregate<Experiment_with_unifying_events_and_commands_test.UserAggregate, Experiment_with_unifying_events_and_commands_test.UserEvent.IRoot,
             Experiment_with_unifying_events_and_commands_test.UserEvent.Implementation.Root>));
      map(new Guid("533f98bd-d263-461a-b21c-6773bd2d5474"),
          typeof(Compze.Tessaging.Teventive.Aggregate<Experiment_with_unifying_events_and_commands_test.UserRegistrarAggregate, Experiment_with_unifying_events_and_commands_test.UserRegistrarEvent.IRoot,
             Experiment_with_unifying_events_and_commands_test.UserRegistrarEvent.Implementation.Root>));
   }
}
