

// ReSharper disable All
namespace Compze.Tests.Common;

#pragma warning disable IDE1006,IDE0001,IDE0002,IDE0003,IDE0004,IDE0005,IDE0055,CA1050,CA1707,CA1716

/// <summary>
/// This file is automatically generated. Compze will automatically figure out most types that need to go in here, but some types you may need to add yourself.
/// Compze will tell you so in an exception thought, and you can just paste it in here.
/// Regenerate by running the application when type mappings are missing.
/// </summary>
public sealed class AutoGeneratedCurrentAssemblyTypeMapperForRefactoringSupport
{
   public void MapTypesForCurrentAssembly(Action<string, Type> map)
   {
      map("f5b3bcfd-ce1a-4c7c-8a1f-1d734a900e57", typeof(Compze.Core.Public.Entity<Compze.Tests.Common.Sql.DocumentDb.Person>));
      map("9d7f4920-6245-4c43-adc9-9eb424f8d475", typeof(Compze.Core.Tessaging.Public.TessageTypes.Remotable.AtMostOnce.AtMostOnceTypermediaTommand<Compze.Tests.Common.Tessaging.ServiceBusSpecification.Given_a_backend_endpoint_with_a_tommand_tevent_and_tuery_handler.MyTommandResult>));
      map("fae483ab-99c2-4c4f-9724-a7ca85b6afe1", typeof(Compze.Core.Tessaging.Teventive.Public.Taggregates.BaseClasses.Public.Taggregate<Compze.Tests.Common.CQRS.TeventRefactoring.Migrations.TestTaggregate,Compze.Tests.Common.CQRS.TeventRefactoring.Migrations.ITestTaggregateTevent,Compze.Tests.Common.CQRS.TeventRefactoring.Migrations.TestTaggregateTevent,Compze.Tests.Common.CQRS.TeventRefactoring.Migrations.ITestTaggregateTevent<Compze.Tests.Common.CQRS.TeventRefactoring.Migrations.ITestTaggregateTevent>,Compze.Tests.Common.CQRS.TeventRefactoring.Migrations.TestTaggregateTevent<Compze.Tests.Common.CQRS.TeventRefactoring.Migrations.TestTaggregateTevent>>));
      map("6b324c16-fb4e-440b-90a2-de0a385853d5", typeof(Compze.Core.Tessaging.Teventive.Public.Taggregates.BaseClasses.Public.Taggregate<Compze.Tests.Common.Tessaging.ServiceBusSpecification.Given_a_backend_endpoint_with_a_tommand_tevent_and_tuery_handler.MyTaggregate,Compze.Tests.Common.Tessaging.ServiceBusSpecification.Given_a_backend_endpoint_with_a_tommand_tevent_and_tuery_handler.IMyTaggregateTevent,Compze.Tests.Common.Tessaging.ServiceBusSpecification.Given_a_backend_endpoint_with_a_tommand_tevent_and_tuery_handler.MyTaggregateTevent,Compze.Tests.Common.Tessaging.ServiceBusSpecification.Given_a_backend_endpoint_with_a_tommand_tevent_and_tuery_handler.IMyTaggregateTevent<Compze.Tests.Common.Tessaging.ServiceBusSpecification.Given_a_backend_endpoint_with_a_tommand_tevent_and_tuery_handler.IMyTaggregateTevent>,Compze.Tests.Common.Tessaging.ServiceBusSpecification.Given_a_backend_endpoint_with_a_tommand_tevent_and_tuery_handler.MyTaggregateTevent<Compze.Tests.Common.Tessaging.ServiceBusSpecification.Given_a_backend_endpoint_with_a_tommand_tevent_and_tuery_handler.MyTaggregateTevent>>));
      map("11e69911-38c6-4dd9-9798-0ac8014e52fe", typeof(Compze.Tests.Common.CQRS.TeventRefactoring.Migrations.ITestTaggregateTevent));
      map("6177beb2-46dc-42f8-8471-c807c501a898", typeof(Compze.Tests.Common.CQRS.TeventRefactoring.Migrations.ITestTaggregateTevent[]));
      map("dc649f16-a821-4e5d-84f4-dd212374b7ef", typeof(Compze.Tests.Common.CQRS.TeventRefactoring.Migrations.ITestTaggregateTevent<Compze.Tests.Common.CQRS.TeventRefactoring.Migrations.ITestTaggregateTevent>));
      map("858998a5-20d9-474a-9ec9-595d60cf2a3f", typeof(Compze.Tests.Common.CQRS.TeventRefactoring.Migrations.TestTaggregate));
      map("c7a4a719-29fb-4a55-916d-ad062ab7daa7", typeof(Compze.Tests.Common.CQRS.TeventRefactoring.Migrations.TestTaggregate[]));
      map("e97aa97c-3761-404f-a8b4-6689e22c9aa3", typeof(Compze.Tests.Common.CQRS.TeventRefactoring.Migrations.TestTaggregateTevent));
      map("c8b7a806-47b9-4c2d-828a-2de99823dc8a", typeof(Compze.Tests.Common.CQRS.TeventRefactoring.Migrations.TestTaggregateTevent[]));
      map("46e6ddac-dc76-4d91-81b2-ca22222d1345", typeof(Compze.Tests.Common.CQRS.TeventRefactoring.Migrations.TestTaggregateTevent<Compze.Tests.Common.CQRS.TeventRefactoring.Migrations.TestTaggregateTevent>));
      map("e5e9e630-3b2c-4323-9bf2-a4d2270157aa", typeof(Compze.Tests.Common.CQRS.TeventRefactoring.Migrations.Tevents.E1));
      map("45685cc5-b07a-4dd7-a991-a39fa1a740b4", typeof(Compze.Tests.Common.CQRS.TeventRefactoring.Migrations.Tevents.E1[]));
      map("32eb31d6-e61a-41ae-8f4c-4ca275c056a6", typeof(Compze.Tests.Common.CQRS.TeventRefactoring.Migrations.Tevents.E2));
      map("072071a9-5ead-4a3b-9d52-4a8a1c0b0904", typeof(Compze.Tests.Common.CQRS.TeventRefactoring.Migrations.Tevents.E2[]));
      map("fd649708-a138-4d22-abb2-15c3c38e1af4", typeof(Compze.Tests.Common.CQRS.TeventRefactoring.Migrations.Tevents.E3));
      map("38311926-1425-4d17-a8ef-7ad7e8255a5d", typeof(Compze.Tests.Common.CQRS.TeventRefactoring.Migrations.Tevents.E3[]));
      map("bf452ac4-a6ec-417b-adb7-b6760aca1f91", typeof(Compze.Tests.Common.CQRS.TeventRefactoring.Migrations.Tevents.E4));
      map("36772eb8-3cd5-47b5-911b-2bc1c936f594", typeof(Compze.Tests.Common.CQRS.TeventRefactoring.Migrations.Tevents.E4[]));
      map("d95c69d5-ca1a-47ba-920c-fbdc3ee673bf", typeof(Compze.Tests.Common.CQRS.TeventRefactoring.Migrations.Tevents.E5));
      map("a91e6ada-ca3c-497c-b9d4-12ea5d49c997", typeof(Compze.Tests.Common.CQRS.TeventRefactoring.Migrations.Tevents.E5[]));
      map("862f902c-5e2c-4fa7-bba3-1b5853e6dbf9", typeof(Compze.Tests.Common.CQRS.TeventRefactoring.Migrations.Tevents.E6));
      map("055ef321-8d56-4cc9-af2f-043a044a3bcb", typeof(Compze.Tests.Common.CQRS.TeventRefactoring.Migrations.Tevents.E6[]));
      map("f6ea065a-8ea5-4ef4-8d27-cf8b427d5be7", typeof(Compze.Tests.Common.CQRS.TeventRefactoring.Migrations.Tevents.E7));
      map("2e4933af-7f66-43e1-a4ce-a796b61341a8", typeof(Compze.Tests.Common.CQRS.TeventRefactoring.Migrations.Tevents.E7[]));
      map("4df3c2de-a77f-4e3e-9c33-7bc213213bf4", typeof(Compze.Tests.Common.CQRS.TeventRefactoring.Migrations.Tevents.E8));
      map("17aca09e-245c-477c-b2a6-14042e61fcd4", typeof(Compze.Tests.Common.CQRS.TeventRefactoring.Migrations.Tevents.E8[]));
      map("5467fe0f-0c6f-4ca6-b0f7-3e5a154704d4", typeof(Compze.Tests.Common.CQRS.TeventRefactoring.Migrations.Tevents.E9));
      map("e78b0c0f-b6d9-42ad-8218-1d709a1788aa", typeof(Compze.Tests.Common.CQRS.TeventRefactoring.Migrations.Tevents.E9[]));
      map("2d1f06a3-2a0b-42c3-8105-226bfd8f1bd8", typeof(Compze.Tests.Common.CQRS.TeventRefactoring.Migrations.Tevents.Ec1));
      map("200120a5-5000-467b-81e1-a831b30f3fbd", typeof(Compze.Tests.Common.CQRS.TeventRefactoring.Migrations.Tevents.Ec1[]));
      map("a87101d3-38a0-4c2d-b50d-e28adf9f4ddd", typeof(Compze.Tests.Common.CQRS.TeventRefactoring.Migrations.Tevents.Ec2));
      map("f4787ddc-72cb-4c70-a696-d066aee4ad58", typeof(Compze.Tests.Common.CQRS.TeventRefactoring.Migrations.Tevents.Ec2[]));
      map("361c1132-caa7-4261-909c-d16a02dfb153", typeof(Compze.Tests.Common.CQRS.TeventRefactoring.Migrations.Tevents.Ec3));
      map("4abfd3f4-2712-416e-9b8c-7fb42f88d1a8", typeof(Compze.Tests.Common.CQRS.TeventRefactoring.Migrations.Tevents.Ec3[]));
      map("41ac6559-69b3-4868-abf3-64b2c2f14151", typeof(Compze.Tests.Common.CQRS.TeventRefactoring.Migrations.Tevents.EcAbstract));
      map("ae20d773-0f1f-4ebc-8232-7221b3543351", typeof(Compze.Tests.Common.CQRS.TeventRefactoring.Migrations.Tevents.EcAbstract[]));
      map("437c3500-ece7-46bf-bc58-3b3fcd8cac1b", typeof(Compze.Tests.Common.CQRS.TeventRefactoring.Migrations.Tevents.Ef));
      map("e6f3d0b1-f5f6-4769-96af-210ec1a4a6b3", typeof(Compze.Tests.Common.CQRS.TeventRefactoring.Migrations.Tevents.Ef[]));
      map("9cdd62b2-e7e6-4443-a5ce-900a610ef8e3", typeof(Compze.Tests.Common.Sql.DocumentDb.Dog));
      map("3bba41f2-b668-4691-b0f5-3126a47bced9", typeof(Compze.Tests.Common.Sql.DocumentDb.Dog[]));
      map("95204c89-46f6-4dac-af3e-957fb547cc3a", typeof(Compze.Tests.Common.Sql.DocumentDb.Person));
      map("268c56ec-ad91-47ed-8f2d-4beb4aa34487", typeof(Compze.Tests.Common.Sql.DocumentDb.Person[]));
      map("d40010d2-912a-4496-b7c8-2b1cec7297d2", typeof(Compze.Tests.Common.Sql.DocumentDb.User));
      map("0c6f5239-d50b-47d7-96fb-ebc53157c32c", typeof(Compze.Tests.Common.Sql.DocumentDb.User[]));
      map("91db1fa3-d379-4485-9904-0e8a7a21566f", typeof(Compze.Tests.Common.Tessaging.ServiceBusSpecification.Given_a_backend_endpoint_with_a_tommand_tevent_and_tuery_handler.IMyExactlyOnceTevent));
      map("536d732c-0268-4db0-a376-c52cb1efb271", typeof(Compze.Tests.Common.Tessaging.ServiceBusSpecification.Given_a_backend_endpoint_with_a_tommand_tevent_and_tuery_handler.IMyExactlyOnceTevent[]));
      map("919c31dd-596e-4b80-a5fd-13af2319ee16", typeof(Compze.Tests.Common.Tessaging.ServiceBusSpecification.Given_a_backend_endpoint_with_a_tommand_tevent_and_tuery_handler.IMyTaggregateTevent));
      map("7b4dbf40-39c6-4403-b622-482e98c73601", typeof(Compze.Tests.Common.Tessaging.ServiceBusSpecification.Given_a_backend_endpoint_with_a_tommand_tevent_and_tuery_handler.IMyTaggregateTevent.Created));
      map("439e0daa-9ff4-4b88-8e4d-a348c76281eb", typeof(Compze.Tests.Common.Tessaging.ServiceBusSpecification.Given_a_backend_endpoint_with_a_tommand_tevent_and_tuery_handler.IMyTaggregateTevent.Created[]));
      map("2a04991f-0cd9-4bc8-b9a4-30ed5e8f66e4", typeof(Compze.Tests.Common.Tessaging.ServiceBusSpecification.Given_a_backend_endpoint_with_a_tommand_tevent_and_tuery_handler.IMyTaggregateTevent.Updated));
      map("3f195c3d-76a6-4195-bf75-a0045e97873c", typeof(Compze.Tests.Common.Tessaging.ServiceBusSpecification.Given_a_backend_endpoint_with_a_tommand_tevent_and_tuery_handler.IMyTaggregateTevent.Updated[]));
      map("48bbc054-47f4-4208-a69b-4f78ec960e24", typeof(Compze.Tests.Common.Tessaging.ServiceBusSpecification.Given_a_backend_endpoint_with_a_tommand_tevent_and_tuery_handler.IMyTaggregateTevent[]));
      map("ea7dd678-a5fd-4d1f-a9bc-845716c68c5f", typeof(Compze.Tests.Common.Tessaging.ServiceBusSpecification.Given_a_backend_endpoint_with_a_tommand_tevent_and_tuery_handler.IMyTaggregateTevent<Compze.Tests.Common.Tessaging.ServiceBusSpecification.Given_a_backend_endpoint_with_a_tommand_tevent_and_tuery_handler.IMyTaggregateTevent>));
      map("ff9beeb1-9ede-43a5-9f7e-64ac0dccaf16", typeof(Compze.Tests.Common.Tessaging.ServiceBusSpecification.Given_a_backend_endpoint_with_a_tommand_tevent_and_tuery_handler.MyAtMostOnceTypermediaTommandWithResult));
      map("ced019c6-cc3d-4a5d-97eb-1ce656a191fa", typeof(Compze.Tests.Common.Tessaging.ServiceBusSpecification.Given_a_backend_endpoint_with_a_tommand_tevent_and_tuery_handler.MyAtMostOnceTypermediaTommandWithResult[]));
      map("cb7ce885-5300-4e63-8b72-c86ab6b61655", typeof(Compze.Tests.Common.Tessaging.ServiceBusSpecification.Given_a_backend_endpoint_with_a_tommand_tevent_and_tuery_handler.MyCreateTaggregateTommand));
      map("c0e789d4-cca5-4082-9d1e-b90beadeb2f5", typeof(Compze.Tests.Common.Tessaging.ServiceBusSpecification.Given_a_backend_endpoint_with_a_tommand_tevent_and_tuery_handler.MyCreateTaggregateTommand[]));
      map("4f37723d-f981-4aff-9a8c-e0c3ee53b568", typeof(Compze.Tests.Common.Tessaging.ServiceBusSpecification.Given_a_backend_endpoint_with_a_tommand_tevent_and_tuery_handler.MyExactlyOnceTevent));
      map("108b89dd-4740-4497-9b34-2e844ed28788", typeof(Compze.Tests.Common.Tessaging.ServiceBusSpecification.Given_a_backend_endpoint_with_a_tommand_tevent_and_tuery_handler.MyExactlyOnceTevent[]));
      map("c0233a55-955f-4ec9-b0dc-376f1c8b1f9a", typeof(Compze.Tests.Common.Tessaging.ServiceBusSpecification.Given_a_backend_endpoint_with_a_tommand_tevent_and_tuery_handler.MyExactlyOnceTommand));
      map("dc62d57b-564c-44f3-8f64-ed48faa5572b", typeof(Compze.Tests.Common.Tessaging.ServiceBusSpecification.Given_a_backend_endpoint_with_a_tommand_tevent_and_tuery_handler.MyExactlyOnceTommand[]));
      map("9a19bd04-7d1e-4846-a4a3-909b889a3d44", typeof(Compze.Tests.Common.Tessaging.ServiceBusSpecification.Given_a_backend_endpoint_with_a_tommand_tevent_and_tuery_handler.MyTaggregate));
      map("20067d51-11a0-424f-b917-9765a2fc8128", typeof(Compze.Tests.Common.Tessaging.ServiceBusSpecification.Given_a_backend_endpoint_with_a_tommand_tevent_and_tuery_handler.MyTaggregate[]));
      map("39c8432a-4481-4552-9d91-d28810e64155", typeof(Compze.Tests.Common.Tessaging.ServiceBusSpecification.Given_a_backend_endpoint_with_a_tommand_tevent_and_tuery_handler.MyTaggregateTevent));
      map("69068b48-4efd-4e3f-9f84-17c3f7881ef0", typeof(Compze.Tests.Common.Tessaging.ServiceBusSpecification.Given_a_backend_endpoint_with_a_tommand_tevent_and_tuery_handler.MyTaggregateTevent.Created));
      map("87d70e93-ae40-4a27-b04a-1170c3461a02", typeof(Compze.Tests.Common.Tessaging.ServiceBusSpecification.Given_a_backend_endpoint_with_a_tommand_tevent_and_tuery_handler.MyTaggregateTevent.Created[]));
      map("139c9a83-92ce-4f52-9a09-02f579a9e61b", typeof(Compze.Tests.Common.Tessaging.ServiceBusSpecification.Given_a_backend_endpoint_with_a_tommand_tevent_and_tuery_handler.MyTaggregateTevent.Updated));
      map("fa89ea69-31af-4261-bb5a-2332f3d6800a", typeof(Compze.Tests.Common.Tessaging.ServiceBusSpecification.Given_a_backend_endpoint_with_a_tommand_tevent_and_tuery_handler.MyTaggregateTevent.Updated[]));
      map("2cdd1aa1-1e42-4077-b928-f94faa93eca1", typeof(Compze.Tests.Common.Tessaging.ServiceBusSpecification.Given_a_backend_endpoint_with_a_tommand_tevent_and_tuery_handler.MyTaggregateTevent[]));
      map("adeeb4ca-bec2-4a40-afc8-570172de7c1b", typeof(Compze.Tests.Common.Tessaging.ServiceBusSpecification.Given_a_backend_endpoint_with_a_tommand_tevent_and_tuery_handler.MyTaggregateTevent<Compze.Tests.Common.Tessaging.ServiceBusSpecification.Given_a_backend_endpoint_with_a_tommand_tevent_and_tuery_handler.MyTaggregateTevent>));
      map("c4f84bc9-82e2-4ba5-8840-585ede693d69", typeof(Compze.Tests.Common.Tessaging.ServiceBusSpecification.Given_a_backend_endpoint_with_a_tommand_tevent_and_tuery_handler.MyTuery));
      map("12cdd50b-d4f3-47f2-b844-a769790986d3", typeof(Compze.Tests.Common.Tessaging.ServiceBusSpecification.Given_a_backend_endpoint_with_a_tommand_tevent_and_tuery_handler.MyTuery[]));
      map("5f82364d-820a-4bba-9dca-470c75e73ea4", typeof(Compze.Tests.Common.Tessaging.ServiceBusSpecification.Given_a_backend_endpoint_with_a_tommand_tevent_and_tuery_handler.MyUpdateTaggregateTommand));
      map("ed238cf1-dd4a-4e18-a99e-8ab4cf6e4d74", typeof(Compze.Tests.Common.Tessaging.ServiceBusSpecification.Given_a_backend_endpoint_with_a_tommand_tevent_and_tuery_handler.MyUpdateTaggregateTommand[]));
   }
}
