using System;

// ReSharper disable All
namespace Compze.Tests.Common;

#pragma warning disable IDE1006,IDE0001,IDE0002,IDE0003,IDE0004,IDE0005,IDE0055,CA1050,CA1707,CA1716

/// <summary>
/// This file is automatically generated. Compze will automatically figure out most types that need to go in here, but some types you may need to add yourself.
/// Compze will tell you so in an exception thought, and you can just paste it in here.
/// Regenerate by running the application when type mappings are missing.
/// </summary>
public sealed class AutoGeneratedCurrentAssemblyTypeMapperForRefactoringSupport
{
   public void MapTypesForCurrentAssembly(Action<string, Type> map)
   {
      map("5cf33bc0-3a2c-4116-b5fb-1ec6f52cd6c0", typeof(Compze.Abstractions.Public.Entity<Compze.Tests.Common.Sql.DocumentDb.Person>));
      map("743aa72b-906c-4fb8-a313-75490c57a142", typeof(Compze.Abstractions.Tessaging.Public.TessageTypes.Remotable.AtMostOnce.AtMostOnceTypermediaTommand<Compze.Tests.Common.Tessaging.ServiceBusSpecification.Given_a_backend_endpoint_with_a_tommand_tevent_and_tuery_handler.MyTommandResult>));
      map("3f13b8e4-514a-4c22-bfb4-992ab6489f44", typeof(Compze.Core.Tessaging.Teventive.Public.Taggregates.BaseClasses.Public.Taggregate<Compze.Tests.Common.CQRS.TeventRefactoring.Migrations.TestTaggregate,Compze.Tests.Common.CQRS.TeventRefactoring.Migrations.ITestTaggregateTevent,Compze.Tests.Common.CQRS.TeventRefactoring.Migrations.TestTaggregateTevent,Compze.Tests.Common.CQRS.TeventRefactoring.Migrations.ITestTaggregateTevent<Compze.Tests.Common.CQRS.TeventRefactoring.Migrations.ITestTaggregateTevent>,Compze.Tests.Common.CQRS.TeventRefactoring.Migrations.TestTaggregateTevent<Compze.Tests.Common.CQRS.TeventRefactoring.Migrations.TestTaggregateTevent>>));
      map("3a74c21e-34b2-429c-bce9-059b966d72e2", typeof(Compze.Core.Tessaging.Teventive.Public.Taggregates.BaseClasses.Public.Taggregate<Compze.Tests.Common.Tessaging.ServiceBusSpecification.Given_a_backend_endpoint_with_a_tommand_tevent_and_tuery_handler.MyTaggregate,Compze.Tests.Common.Tessaging.ServiceBusSpecification.Given_a_backend_endpoint_with_a_tommand_tevent_and_tuery_handler.IMyTaggregateTevent,Compze.Tests.Common.Tessaging.ServiceBusSpecification.Given_a_backend_endpoint_with_a_tommand_tevent_and_tuery_handler.MyTaggregateTevent,Compze.Tests.Common.Tessaging.ServiceBusSpecification.Given_a_backend_endpoint_with_a_tommand_tevent_and_tuery_handler.IMyTaggregateTevent<Compze.Tests.Common.Tessaging.ServiceBusSpecification.Given_a_backend_endpoint_with_a_tommand_tevent_and_tuery_handler.IMyTaggregateTevent>,Compze.Tests.Common.Tessaging.ServiceBusSpecification.Given_a_backend_endpoint_with_a_tommand_tevent_and_tuery_handler.MyTaggregateTevent<Compze.Tests.Common.Tessaging.ServiceBusSpecification.Given_a_backend_endpoint_with_a_tommand_tevent_and_tuery_handler.MyTaggregateTevent>>));
      map("11e69911-38c6-4dd9-9798-0ac8014e52fe", typeof(Compze.Tests.Common.CQRS.TeventRefactoring.Migrations.ITestTaggregateTevent));
      map("3e992f61-f4ca-43cc-b244-d139e2dc239b", typeof(Compze.Tests.Common.CQRS.TeventRefactoring.Migrations.ITestTaggregateTevent[]));
      map("51ca3728-35be-4eff-bada-a7be4a91bfd3", typeof(Compze.Tests.Common.CQRS.TeventRefactoring.Migrations.ITestTaggregateTevent<Compze.Tests.Common.CQRS.TeventRefactoring.Migrations.ITestTaggregateTevent>));
      map("858998a5-20d9-474a-9ec9-595d60cf2a3f", typeof(Compze.Tests.Common.CQRS.TeventRefactoring.Migrations.TestTaggregate));
      map("cb5a62fb-2455-46c6-b8e5-8c9558d7bc70", typeof(Compze.Tests.Common.CQRS.TeventRefactoring.Migrations.TestTaggregate[]));
      map("e97aa97c-3761-404f-a8b4-6689e22c9aa3", typeof(Compze.Tests.Common.CQRS.TeventRefactoring.Migrations.TestTaggregateTevent));
      map("f7db4426-9aa7-4716-aef4-fd5a137238fa", typeof(Compze.Tests.Common.CQRS.TeventRefactoring.Migrations.TestTaggregateTevent[]));
      map("fab6e642-ccaf-4762-b917-9e51baf6bab0", typeof(Compze.Tests.Common.CQRS.TeventRefactoring.Migrations.TestTaggregateTevent<Compze.Tests.Common.CQRS.TeventRefactoring.Migrations.TestTaggregateTevent>));
      map("e5e9e630-3b2c-4323-9bf2-a4d2270157aa", typeof(Compze.Tests.Common.CQRS.TeventRefactoring.Migrations.Tevents.E1));
      map("5d8d5de2-b7a1-4d7f-bbf9-b1a685fe47af", typeof(Compze.Tests.Common.CQRS.TeventRefactoring.Migrations.Tevents.E1[]));
      map("32eb31d6-e61a-41ae-8f4c-4ca275c056a6", typeof(Compze.Tests.Common.CQRS.TeventRefactoring.Migrations.Tevents.E2));
      map("92d13b92-0418-4f24-b976-c3f0e6fc62a4", typeof(Compze.Tests.Common.CQRS.TeventRefactoring.Migrations.Tevents.E2[]));
      map("fd649708-a138-4d22-abb2-15c3c38e1af4", typeof(Compze.Tests.Common.CQRS.TeventRefactoring.Migrations.Tevents.E3));
      map("4b7816fc-63df-494e-97c1-e476574103cb", typeof(Compze.Tests.Common.CQRS.TeventRefactoring.Migrations.Tevents.E3[]));
      map("bf452ac4-a6ec-417b-adb7-b6760aca1f91", typeof(Compze.Tests.Common.CQRS.TeventRefactoring.Migrations.Tevents.E4));
      map("3d740bcb-11a2-46e0-84df-ad4d3ae9e86d", typeof(Compze.Tests.Common.CQRS.TeventRefactoring.Migrations.Tevents.E4[]));
      map("d95c69d5-ca1a-47ba-920c-fbdc3ee673bf", typeof(Compze.Tests.Common.CQRS.TeventRefactoring.Migrations.Tevents.E5));
      map("adae4680-49cb-45c3-83ae-2594352514fb", typeof(Compze.Tests.Common.CQRS.TeventRefactoring.Migrations.Tevents.E5[]));
      map("862f902c-5e2c-4fa7-bba3-1b5853e6dbf9", typeof(Compze.Tests.Common.CQRS.TeventRefactoring.Migrations.Tevents.E6));
      map("f537cae2-0fce-40af-b10c-76f046614e61", typeof(Compze.Tests.Common.CQRS.TeventRefactoring.Migrations.Tevents.E6[]));
      map("f6ea065a-8ea5-4ef4-8d27-cf8b427d5be7", typeof(Compze.Tests.Common.CQRS.TeventRefactoring.Migrations.Tevents.E7));
      map("08e33434-f5fe-4037-858b-c0e65978c588", typeof(Compze.Tests.Common.CQRS.TeventRefactoring.Migrations.Tevents.E7[]));
      map("4df3c2de-a77f-4e3e-9c33-7bc213213bf4", typeof(Compze.Tests.Common.CQRS.TeventRefactoring.Migrations.Tevents.E8));
      map("0b84282a-d435-453d-8ceb-3cd16c79f869", typeof(Compze.Tests.Common.CQRS.TeventRefactoring.Migrations.Tevents.E8[]));
      map("5467fe0f-0c6f-4ca6-b0f7-3e5a154704d4", typeof(Compze.Tests.Common.CQRS.TeventRefactoring.Migrations.Tevents.E9));
      map("86eecb5a-0077-4582-98f6-b1a3ddef56b8", typeof(Compze.Tests.Common.CQRS.TeventRefactoring.Migrations.Tevents.E9[]));
      map("2d1f06a3-2a0b-42c3-8105-226bfd8f1bd8", typeof(Compze.Tests.Common.CQRS.TeventRefactoring.Migrations.Tevents.Ec1));
      map("75024986-b23b-458d-bea7-dbc66cf6a23d", typeof(Compze.Tests.Common.CQRS.TeventRefactoring.Migrations.Tevents.Ec1[]));
      map("a87101d3-38a0-4c2d-b50d-e28adf9f4ddd", typeof(Compze.Tests.Common.CQRS.TeventRefactoring.Migrations.Tevents.Ec2));
      map("8ef0c808-0e33-49fa-821f-2c42a469de8a", typeof(Compze.Tests.Common.CQRS.TeventRefactoring.Migrations.Tevents.Ec2[]));
      map("361c1132-caa7-4261-909c-d16a02dfb153", typeof(Compze.Tests.Common.CQRS.TeventRefactoring.Migrations.Tevents.Ec3));
      map("92c2eb7a-b9f2-4043-940f-863a059c8a4d", typeof(Compze.Tests.Common.CQRS.TeventRefactoring.Migrations.Tevents.Ec3[]));
      map("41ac6559-69b3-4868-abf3-64b2c2f14151", typeof(Compze.Tests.Common.CQRS.TeventRefactoring.Migrations.Tevents.EcAbstract));
      map("0ce5e6b8-4cf9-440c-9363-28104be2c08b", typeof(Compze.Tests.Common.CQRS.TeventRefactoring.Migrations.Tevents.EcAbstract[]));
      map("437c3500-ece7-46bf-bc58-3b3fcd8cac1b", typeof(Compze.Tests.Common.CQRS.TeventRefactoring.Migrations.Tevents.Ef));
      map("a3f287be-9b26-44ee-a2af-d43ce57ab01b", typeof(Compze.Tests.Common.CQRS.TeventRefactoring.Migrations.Tevents.Ef[]));
      map("9cdd62b2-e7e6-4443-a5ce-900a610ef8e3", typeof(Compze.Tests.Common.Sql.DocumentDb.Dog));
      map("4df5ea5e-ab18-4ebf-a98e-2e905354e54f", typeof(Compze.Tests.Common.Sql.DocumentDb.Dog[]));
      map("b0c1d2e3-f4a5-6789-0abc-def012345678", typeof(Compze.Tests.Common.Sql.DocumentDb.Email));
      map("b0c1d2e3-f4a5-6789-0abc-def012345679", typeof(Compze.Tests.Common.Sql.DocumentDb.Email[]));
      map("95204c89-46f6-4dac-af3e-957fb547cc3a", typeof(Compze.Tests.Common.Sql.DocumentDb.Person));
      map("d8177d7c-204b-4c97-bd58-210281f30168", typeof(Compze.Tests.Common.Sql.DocumentDb.Person[]));
      map("d40010d2-912a-4496-b7c8-2b1cec7297d2", typeof(Compze.Tests.Common.Sql.DocumentDb.User));
      map("1671048d-9bda-4259-ba6a-87d16b657eee", typeof(Compze.Tests.Common.Sql.DocumentDb.User[]));
      map("2a67391d-a52a-4821-a448-bfa3631a292b", typeof(System.Collections.Generic.HashSet<Compze.Tests.Common.Sql.DocumentDb.User>));
      map("91db1fa3-d379-4485-9904-0e8a7a21566f", typeof(Compze.Tests.Common.Tessaging.ServiceBusSpecification.Given_a_backend_endpoint_with_a_tommand_tevent_and_tuery_handler.IMyExactlyOnceTevent));
      map("a5ca7c07-fa7d-47f7-81ee-84975f671c10", typeof(Compze.Tests.Common.Tessaging.ServiceBusSpecification.Given_a_backend_endpoint_with_a_tommand_tevent_and_tuery_handler.IMyExactlyOnceTevent[]));
      map("919c31dd-596e-4b80-a5fd-13af2319ee16", typeof(Compze.Tests.Common.Tessaging.ServiceBusSpecification.Given_a_backend_endpoint_with_a_tommand_tevent_and_tuery_handler.IMyTaggregateTevent));
      map("7b4dbf40-39c6-4403-b622-482e98c73601", typeof(Compze.Tests.Common.Tessaging.ServiceBusSpecification.Given_a_backend_endpoint_with_a_tommand_tevent_and_tuery_handler.IMyTaggregateTevent.Created));
      map("a6f51fee-d54d-4a8b-a8b6-a4af184c1bac", typeof(Compze.Tests.Common.Tessaging.ServiceBusSpecification.Given_a_backend_endpoint_with_a_tommand_tevent_and_tuery_handler.IMyTaggregateTevent.Created[]));
      map("2a04991f-0cd9-4bc8-b9a4-30ed5e8f66e4", typeof(Compze.Tests.Common.Tessaging.ServiceBusSpecification.Given_a_backend_endpoint_with_a_tommand_tevent_and_tuery_handler.IMyTaggregateTevent.Updated));
      map("f3c5350a-b523-4f2c-b0d8-0f5e2dca14f4", typeof(Compze.Tests.Common.Tessaging.ServiceBusSpecification.Given_a_backend_endpoint_with_a_tommand_tevent_and_tuery_handler.IMyTaggregateTevent.Updated[]));
      map("f50947fa-7100-42e0-afd0-05d546bc6c23", typeof(Compze.Tests.Common.Tessaging.ServiceBusSpecification.Given_a_backend_endpoint_with_a_tommand_tevent_and_tuery_handler.IMyTaggregateTevent[]));
      map("bd89ee08-f00f-4969-9519-09a4029dfc67", typeof(Compze.Tests.Common.Tessaging.ServiceBusSpecification.Given_a_backend_endpoint_with_a_tommand_tevent_and_tuery_handler.IMyTaggregateTevent<Compze.Tests.Common.Tessaging.ServiceBusSpecification.Given_a_backend_endpoint_with_a_tommand_tevent_and_tuery_handler.IMyTaggregateTevent>));
      map("ff9beeb1-9ede-43a5-9f7e-64ac0dccaf16", typeof(Compze.Tests.Common.Tessaging.ServiceBusSpecification.Given_a_backend_endpoint_with_a_tommand_tevent_and_tuery_handler.MyAtMostOnceTypermediaTommandWithResult));
      map("95da28a5-87eb-4936-8953-9e7ae5bc2a66", typeof(Compze.Tests.Common.Tessaging.ServiceBusSpecification.Given_a_backend_endpoint_with_a_tommand_tevent_and_tuery_handler.MyAtMostOnceTypermediaTommandWithResult[]));
      map("cb7ce885-5300-4e63-8b72-c86ab6b61655", typeof(Compze.Tests.Common.Tessaging.ServiceBusSpecification.Given_a_backend_endpoint_with_a_tommand_tevent_and_tuery_handler.MyCreateTaggregateTommand));
      map("4a02d554-88c0-4220-ad92-f34a553beaa2", typeof(Compze.Tests.Common.Tessaging.ServiceBusSpecification.Given_a_backend_endpoint_with_a_tommand_tevent_and_tuery_handler.MyCreateTaggregateTommand[]));
      map("4f37723d-f981-4aff-9a8c-e0c3ee53b568", typeof(Compze.Tests.Common.Tessaging.ServiceBusSpecification.Given_a_backend_endpoint_with_a_tommand_tevent_and_tuery_handler.MyExactlyOnceTevent));
      map("f2354762-7ae6-4e99-9760-d994a3a2b188", typeof(Compze.Tests.Common.Tessaging.ServiceBusSpecification.Given_a_backend_endpoint_with_a_tommand_tevent_and_tuery_handler.MyExactlyOnceTevent[]));
      map("c0233a55-955f-4ec9-b0dc-376f1c8b1f9a", typeof(Compze.Tests.Common.Tessaging.ServiceBusSpecification.Given_a_backend_endpoint_with_a_tommand_tevent_and_tuery_handler.MyExactlyOnceTommand));
      map("3fa1d73f-fac2-4201-a16a-74e715e802f9", typeof(Compze.Tests.Common.Tessaging.ServiceBusSpecification.Given_a_backend_endpoint_with_a_tommand_tevent_and_tuery_handler.MyExactlyOnceTommand[]));
      map("9a19bd04-7d1e-4846-a4a3-909b889a3d44", typeof(Compze.Tests.Common.Tessaging.ServiceBusSpecification.Given_a_backend_endpoint_with_a_tommand_tevent_and_tuery_handler.MyTaggregate));
      map("a6f666cd-fbdb-4a09-972d-37ca89ff2f31", typeof(Compze.Tests.Common.Tessaging.ServiceBusSpecification.Given_a_backend_endpoint_with_a_tommand_tevent_and_tuery_handler.MyTaggregate[]));
      map("39c8432a-4481-4552-9d91-d28810e64155", typeof(Compze.Tests.Common.Tessaging.ServiceBusSpecification.Given_a_backend_endpoint_with_a_tommand_tevent_and_tuery_handler.MyTaggregateTevent));
      map("69068b48-4efd-4e3f-9f84-17c3f7881ef0", typeof(Compze.Tests.Common.Tessaging.ServiceBusSpecification.Given_a_backend_endpoint_with_a_tommand_tevent_and_tuery_handler.MyTaggregateTevent.Created));
      map("3918b82d-e2f1-43b4-b8c6-1aa343bf4dc0", typeof(Compze.Tests.Common.Tessaging.ServiceBusSpecification.Given_a_backend_endpoint_with_a_tommand_tevent_and_tuery_handler.MyTaggregateTevent.Created[]));
      map("139c9a83-92ce-4f52-9a09-02f579a9e61b", typeof(Compze.Tests.Common.Tessaging.ServiceBusSpecification.Given_a_backend_endpoint_with_a_tommand_tevent_and_tuery_handler.MyTaggregateTevent.Updated));
      map("57f956dd-de79-4bbd-92f1-7d33302a926a", typeof(Compze.Tests.Common.Tessaging.ServiceBusSpecification.Given_a_backend_endpoint_with_a_tommand_tevent_and_tuery_handler.MyTaggregateTevent.Updated[]));
      map("f38583b8-95f1-4e3b-b1e8-f6087ec583c8", typeof(Compze.Tests.Common.Tessaging.ServiceBusSpecification.Given_a_backend_endpoint_with_a_tommand_tevent_and_tuery_handler.MyTaggregateTevent[]));
      map("ca3d6ae6-5387-4dd8-8f81-7caab0ab7a81", typeof(Compze.Tests.Common.Tessaging.ServiceBusSpecification.Given_a_backend_endpoint_with_a_tommand_tevent_and_tuery_handler.MyTaggregateTevent<Compze.Tests.Common.Tessaging.ServiceBusSpecification.Given_a_backend_endpoint_with_a_tommand_tevent_and_tuery_handler.MyTaggregateTevent>));
      map("c4f84bc9-82e2-4ba5-8840-585ede693d69", typeof(Compze.Tests.Common.Tessaging.ServiceBusSpecification.Given_a_backend_endpoint_with_a_tommand_tevent_and_tuery_handler.MyTuery));
      map("860593db-2c9f-475c-9e31-c364e91356f7", typeof(Compze.Tests.Common.Tessaging.ServiceBusSpecification.Given_a_backend_endpoint_with_a_tommand_tevent_and_tuery_handler.MyTuery[]));
      map("5f82364d-820a-4bba-9dca-470c75e73ea4", typeof(Compze.Tests.Common.Tessaging.ServiceBusSpecification.Given_a_backend_endpoint_with_a_tommand_tevent_and_tuery_handler.MyUpdateTaggregateTommand));
      map("09459caf-bf0d-4476-a040-722edbd02087", typeof(Compze.Tests.Common.Tessaging.ServiceBusSpecification.Given_a_backend_endpoint_with_a_tommand_tevent_and_tuery_handler.MyUpdateTaggregateTommand[]));
   }
}
