using System;

// ReSharper disable All
namespace Compze.Tests.Common;

#pragma warning disable IDE1006,IDE0001,IDE0002,IDE0003,IDE0004,IDE0005,IDE0055,CA1050,CA1707,CA1716

/// <summary>
/// This file is automatically generated. Compze will automatically figure out most types that need to go in here, but some types you may need to add yourself.
/// Compze will tell you so in an exception thought, and you can just paste it in here.
/// Regenerate by running the application when type mappings are missing.
/// </summary>
public sealed class AutoGeneratedCurrentAssemblyTypeMapperForRefactoringSupport
{
   public void MapTypesForCurrentAssembly(Action<string, Type> map)
   {
      map("11e69911-38c6-4dd9-9798-0ac8014e52fe", typeof(Compze.Tests.Common.CQRS.TeventRefactoring.Migrations.ITestTaggregateTevent));
      map("0e1c81b3-8ae6-40cc-9397-694652682c06", typeof(Compze.Tests.Common.CQRS.TeventRefactoring.Migrations.ITestTaggregateTevent`1));
      map("858998a5-20d9-474a-9ec9-595d60cf2a3f", typeof(Compze.Tests.Common.CQRS.TeventRefactoring.Migrations.TestTaggregate));
      map("e97aa97c-3761-404f-a8b4-6689e22c9aa3", typeof(Compze.Tests.Common.CQRS.TeventRefactoring.Migrations.TestTaggregateTevent));
      map("bc8abf47-89e5-406a-83a5-0cbc4666f3e4", typeof(Compze.Tests.Common.CQRS.TeventRefactoring.Migrations.TestTaggregateTevent`1));
      map("e5e9e630-3b2c-4323-9bf2-a4d2270157aa", typeof(Compze.Tests.Common.CQRS.TeventRefactoring.Migrations.Tevents.E1));
      map("32eb31d6-e61a-41ae-8f4c-4ca275c056a6", typeof(Compze.Tests.Common.CQRS.TeventRefactoring.Migrations.Tevents.E2));
      map("fd649708-a138-4d22-abb2-15c3c38e1af4", typeof(Compze.Tests.Common.CQRS.TeventRefactoring.Migrations.Tevents.E3));
      map("bf452ac4-a6ec-417b-adb7-b6760aca1f91", typeof(Compze.Tests.Common.CQRS.TeventRefactoring.Migrations.Tevents.E4));
      map("d95c69d5-ca1a-47ba-920c-fbdc3ee673bf", typeof(Compze.Tests.Common.CQRS.TeventRefactoring.Migrations.Tevents.E5));
      map("862f902c-5e2c-4fa7-bba3-1b5853e6dbf9", typeof(Compze.Tests.Common.CQRS.TeventRefactoring.Migrations.Tevents.E6));
      map("f6ea065a-8ea5-4ef4-8d27-cf8b427d5be7", typeof(Compze.Tests.Common.CQRS.TeventRefactoring.Migrations.Tevents.E7));
      map("4df3c2de-a77f-4e3e-9c33-7bc213213bf4", typeof(Compze.Tests.Common.CQRS.TeventRefactoring.Migrations.Tevents.E8));
      map("5467fe0f-0c6f-4ca6-b0f7-3e5a154704d4", typeof(Compze.Tests.Common.CQRS.TeventRefactoring.Migrations.Tevents.E9));
      map("2d1f06a3-2a0b-42c3-8105-226bfd8f1bd8", typeof(Compze.Tests.Common.CQRS.TeventRefactoring.Migrations.Tevents.Ec1));
      map("a87101d3-38a0-4c2d-b50d-e28adf9f4ddd", typeof(Compze.Tests.Common.CQRS.TeventRefactoring.Migrations.Tevents.Ec2));
      map("361c1132-caa7-4261-909c-d16a02dfb153", typeof(Compze.Tests.Common.CQRS.TeventRefactoring.Migrations.Tevents.Ec3));
      map("41ac6559-69b3-4868-abf3-64b2c2f14151", typeof(Compze.Tests.Common.CQRS.TeventRefactoring.Migrations.Tevents.EcAbstract));
      map("437c3500-ece7-46bf-bc58-3b3fcd8cac1b", typeof(Compze.Tests.Common.CQRS.TeventRefactoring.Migrations.Tevents.Ef));
      map("9cdd62b2-e7e6-4443-a5ce-900a610ef8e3", typeof(Compze.Tests.Common.Sql.DocumentDb.Dog));
      map("95204c89-46f6-4dac-af3e-957fb547cc3a", typeof(Compze.Tests.Common.Sql.DocumentDb.Person));
      map("d40010d2-912a-4496-b7c8-2b1cec7297d2", typeof(Compze.Tests.Common.Sql.DocumentDb.User));
      map("91db1fa3-d379-4485-9904-0e8a7a21566f", typeof(Compze.Tests.Common.Tessaging.ServiceBusSpecification.Given_a_backend_endpoint_with_a_tommand_tevent_and_tuery_handler.IMyExactlyOnceTevent));
      map("919c31dd-596e-4b80-a5fd-13af2319ee16", typeof(Compze.Tests.Common.Tessaging.ServiceBusSpecification.Given_a_backend_endpoint_with_a_tommand_tevent_and_tuery_handler.IMyTaggregateTevent));
      map("7b4dbf40-39c6-4403-b622-482e98c73601", typeof(Compze.Tests.Common.Tessaging.ServiceBusSpecification.Given_a_backend_endpoint_with_a_tommand_tevent_and_tuery_handler.IMyTaggregateTevent.Created));
      map("2a04991f-0cd9-4bc8-b9a4-30ed5e8f66e4", typeof(Compze.Tests.Common.Tessaging.ServiceBusSpecification.Given_a_backend_endpoint_with_a_tommand_tevent_and_tuery_handler.IMyTaggregateTevent.Updated));
      map("d756ab14-8d39-43cb-8ed8-d7b3582857d3", typeof(Compze.Tests.Common.Tessaging.ServiceBusSpecification.Given_a_backend_endpoint_with_a_tommand_tevent_and_tuery_handler.IMyTaggregateTevent`1));
      map("ff9beeb1-9ede-43a5-9f7e-64ac0dccaf16", typeof(Compze.Tests.Common.Tessaging.ServiceBusSpecification.Given_a_backend_endpoint_with_a_tommand_tevent_and_tuery_handler.MyAtMostOnceTypermediaTommandWithResult));
      map("cb7ce885-5300-4e63-8b72-c86ab6b61655", typeof(Compze.Tests.Common.Tessaging.ServiceBusSpecification.Given_a_backend_endpoint_with_a_tommand_tevent_and_tuery_handler.MyCreateTaggregateTommand));
      map("4f37723d-f981-4aff-9a8c-e0c3ee53b568", typeof(Compze.Tests.Common.Tessaging.ServiceBusSpecification.Given_a_backend_endpoint_with_a_tommand_tevent_and_tuery_handler.MyExactlyOnceTevent));
      map("c0233a55-955f-4ec9-b0dc-376f1c8b1f9a", typeof(Compze.Tests.Common.Tessaging.ServiceBusSpecification.Given_a_backend_endpoint_with_a_tommand_tevent_and_tuery_handler.MyExactlyOnceTommand));
      map("9a19bd04-7d1e-4846-a4a3-909b889a3d44", typeof(Compze.Tests.Common.Tessaging.ServiceBusSpecification.Given_a_backend_endpoint_with_a_tommand_tevent_and_tuery_handler.MyTaggregate));
      map("39c8432a-4481-4552-9d91-d28810e64155", typeof(Compze.Tests.Common.Tessaging.ServiceBusSpecification.Given_a_backend_endpoint_with_a_tommand_tevent_and_tuery_handler.MyTaggregateTevent));
      map("69068b48-4efd-4e3f-9f84-17c3f7881ef0", typeof(Compze.Tests.Common.Tessaging.ServiceBusSpecification.Given_a_backend_endpoint_with_a_tommand_tevent_and_tuery_handler.MyTaggregateTevent.Created));
      map("139c9a83-92ce-4f52-9a09-02f579a9e61b", typeof(Compze.Tests.Common.Tessaging.ServiceBusSpecification.Given_a_backend_endpoint_with_a_tommand_tevent_and_tuery_handler.MyTaggregateTevent.Updated));
      map("1b1eb04b-9c17-474a-9500-f7bb58401668", typeof(Compze.Tests.Common.Tessaging.ServiceBusSpecification.Given_a_backend_endpoint_with_a_tommand_tevent_and_tuery_handler.MyTaggregateTevent`1));
      map("c4f84bc9-82e2-4ba5-8840-585ede693d69", typeof(Compze.Tests.Common.Tessaging.ServiceBusSpecification.Given_a_backend_endpoint_with_a_tommand_tevent_and_tuery_handler.MyTuery));
      map("5f82364d-820a-4bba-9dca-470c75e73ea4", typeof(Compze.Tests.Common.Tessaging.ServiceBusSpecification.Given_a_backend_endpoint_with_a_tommand_tevent_and_tuery_handler.MyUpdateTaggregateTommand));
   }
}
