// <auto-generated>
// This file was generated by Compze.InternalizedSourceReferences.
// Changes to this file will be overwritten.
// </auto-generated>
#nullable enable
namespace Compze.Utilities.SystemCE;

internal static class CastCE
{
   public static TTarget CastTo<TTarget>(this object me) => (TTarget)me.NotNull();
}
