// <auto-generated>
// This file was generated by Compze.InternalizedSourceReferences.
// Changes to this file will be overwritten.
// </auto-generated>
#nullable enable
using System;
using Compze.Functional;
using Compze.Utilities.SystemCE.ActionFuncHarmonization;

namespace Compze.Utilities.SystemCE;

internal class ReentrancyGuard
{
   bool _isExecuting = false;
   bool _reentryWasAttempted = false;

   public unit ExecuteIfNotReEntering(Action action) =>
      ExecuteIfNotReEntering(action.AsFunc());

   public unit ExecuteIfNotReEntering(Func<unit> action)
   {
      if(_isExecuting)
      {
         _reentryWasAttempted = true;
         return unit.Value;
      }

      using(ScopedChange.Enter(() => _isExecuting = true, () => _isExecuting = false))
      {
         return action();
      }
   }

#pragma warning disable CA1024 // Method is appropriate — has side effects (clears flag)
   public bool GetAndClearReentryWasAttempted()
#pragma warning restore CA1024
   {
      using(new Disposable(() => _reentryWasAttempted = false))
      {
         return _reentryWasAttempted;
      }
   }
}
