// <auto-generated>
// This file was generated by Compze.InternalizedSourceReferences.
// Changes to this file will be overwritten.
// </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;
using System.Linq;
using JetBrains.Annotations;
using static Compze.Utilities.Contracts.Assert;

namespace Compze.Utilities.SystemCE;

///<summary>Contains extensions on <see cref="string"/></summary>
internal static partial class StringCE
{
   public static string Join(this IEnumerable<string> @this) => string.Join("", @this.ToArray());

   ///<summary>returns true if me is null, empty or only whitespace</summary>
   [ContractAnnotation("null => true")]
   public static bool IsNullEmptyOrWhiteSpace(this string? @this) => string.IsNullOrWhiteSpace(@this);

   /// <summary>Delegates to <see cref="string.Join(string,string[])"/> </summary>
   public static string Join(this IEnumerable<string> @this, string separator)
   {
      Argument.NotNull(@this).NotNull(separator);

      return string.Join(separator, @this.ToArray());
   }

   public static string RemoveLeadingNewLines(this string @this)
   {
      while(@this.StartsWithCE(Environment.NewLine))
      {
         @this = @this[Environment.NewLine.Length..];
      }

      return @this;
   }

   public static string RemoveLinesWhere(this string @this, Func<string, bool> predicate) => @this.Split(Environment.NewLine)
                                                                                             .Where(it => !predicate(it))
                                                                                             .JoinLines();

   public static string Pluralize(this int count, string theString) => count == 1 ? theString : $"{theString}s";
}