using System;
using System.Collections.Generic;
using System.Globalization;
using System.IO;
using System.Reflection;
using System.Text;
using Compze.Utilities.SystemCE.ReflectionCE;

namespace Compze.Core.Refactoring.Naming.Internal.Implementation;

internal static class TypeMapperSourceCodeGenerator
{
   public const string MappingClassName = "AutoGeneratedCurrentAssemblyTypeMapperForRefactoringSupport";
   public const string MappingFileName = $"{MappingClassName}.cs";
   const int MaxDirectoryLevelsToSearchUp = 6;

   public static string GenerateAutoGeneratedClassCode(string? rootNamespace, ISet<Type> typesToMap, Dictionary<Type, TypeId> existingMappings)
   {
      var code = new StringBuilder();

      code.AppendLine("using System;");
      code.AppendLine();
      code.AppendLine(CultureInfo.InvariantCulture, $"// ReSharper disable All");
      code.AppendLine(CultureInfo.InvariantCulture, $"namespace {rootNamespace};");
      code.AppendLine();
      code.AppendLine(CultureInfo.InvariantCulture, $"#pragma warning disable IDE1006,IDE0001,IDE0002,IDE0003,IDE0004,IDE0005,IDE0055,CA1050,CA1707,CA1716");
      code.AppendLine();
      code.AppendLine(CultureInfo.InvariantCulture, $"/// <summary>");
      code.AppendLine(CultureInfo.InvariantCulture, $"/// This file is automatically generated. Compze will automatically figure out most types that need to go in here, but some types you may need to add yourself.");
      code.AppendLine(CultureInfo.InvariantCulture, $"/// Compze will tell you so in an exception thought, and you can just paste it in here.");
      code.AppendLine(CultureInfo.InvariantCulture, $"/// Regenerate by running the application when type mappings are missing.");
      code.AppendLine(CultureInfo.InvariantCulture, $"/// </summary>");
      code.AppendLine(CultureInfo.InvariantCulture, $"public sealed class {MappingClassName}");
      code.AppendLine("{");
      code.AppendLine("   public void MapTypesForCurrentAssembly(Action<string, Type> map)");
      code.AppendLine("   {");

      foreach(var type in typesToMap)
      {
         var guid = existingMappings.TryGetValue(type, out var typeId)
                       ? typeId.ToString()
                       : Guid.NewGuid().ToString();
         code.AppendLine(CultureInfo.InvariantCulture, $"      map(\"{guid}\", typeof({type.GetFullNameCompilable()}));");
      }

      code.AppendLine("   }");
      code.AppendLine("}");

      return code.ToString();
   }

   public static string? TryFindProjectFileAndCreateMapping(Assembly assembly, ISet<Type> typesToMap, Dictionary<Type, TypeId> existingMappings)
   {
      var assemblyLocation = assembly.Location;
      if(string.IsNullOrEmpty(assemblyLocation)) return null;

      var assemblyName = assembly.GetName().Name;
      if(string.IsNullOrEmpty(assemblyName)) return null;

      var assemblyDirectory = Path.GetDirectoryName(assemblyLocation);
      if(string.IsNullOrEmpty(assemblyDirectory)) return null;

      var projectFile = FindProjectFile(assemblyDirectory, assemblyName);
      if(projectFile == null) return null;

      var projectDirectory = Path.GetDirectoryName(projectFile);
      if(string.IsNullOrEmpty(projectDirectory)) return null;

      var mappingFilePath = Path.Combine(projectDirectory, MappingFileName);
      var rootNamespace = assemblyName;

      var mappingCode = GenerateAutoGeneratedClassCode(rootNamespace, typesToMap, existingMappings);
      File.WriteAllText(mappingFilePath, mappingCode);

      return mappingFilePath;
   }

   static string? FindProjectFile(string startDirectory, string assemblyName)
   {
      var projectFileName = $"{assemblyName}.csproj";
      var currentDirectory = startDirectory;

      // Walk up the directory tree up to MaxDirectoryLevelsToSearchUp levels
      for(var level = 0; level < MaxDirectoryLevelsToSearchUp; level++)
      {
         if(string.IsNullOrEmpty(currentDirectory)) break;

         var projectFilePath = Path.Combine(currentDirectory, projectFileName);
         if(File.Exists(projectFilePath)) return projectFilePath;

         var parentDirectory = Directory.GetParent(currentDirectory)?.FullName;
         if(parentDirectory == currentDirectory || parentDirectory == null) break;

         currentDirectory = parentDirectory;
      }

      // If not found after walking up, search down from the highest level reached
      if(!string.IsNullOrEmpty(currentDirectory))
      {
         var foundFile = SearchDirectoryTreeForProjectFile(currentDirectory, projectFileName);
         if(foundFile != null) return foundFile;
      }

      return null;
   }

   static string? SearchDirectoryTreeForProjectFile(string rootDirectory, string projectFileName)
   {
      var projectFilePath = Path.Combine(rootDirectory, projectFileName);
      if(File.Exists(projectFilePath)) return projectFilePath;

      foreach(var directory in Directory.GetDirectories(rootDirectory))
      {
         var foundFile = SearchDirectoryTreeForProjectFile(directory, projectFileName);
         if(foundFile != null) return foundFile;
      }

      return null;
   }
}
