using System;

namespace Compze.Tests.Performance.Internals;

// ReSharper disable All
#pragma warning disable IDE1006,IDE0001,IDE0002,IDE0003,IDE0004,IDE0005,IDE0055,CA1050,CA1707,CA1716

/// <summary>
/// This file is automatically generated. Do not edit manually.
/// Regenerate by running the application when type mappings are missing.
/// </summary>
public sealed class AutoGeneratedCurrentAssemblyTypeMapperForRefactoringSupport
{
      public void MapTypesForCurrentAssembly(Action<Guid, Type> map)
   {
      map(new Guid("74da5216-4cb5-42f7-a16d-d7337b707ef1"), typeof(Compze.Tests.Performance.Internals.Tessaging.Hypermedia.PerformanceTestBase.MyLocalStrictlyLocalQuery));
      map(new Guid("08b3962d-3af1-40be-8485-063bb68bad12"), typeof(Compze.Tests.Performance.Internals.Tessaging.Hypermedia.PerformanceTestBase.MyLocalStrictlyLocalQuery[]));
      map(new Guid("329c5f2f-e887-4265-aeba-c54036a7f6b5"), typeof(Compze.Tests.Performance.Internals.Tessaging.Hypermedia.PerformanceTestBase.MyRemoteQuery));
      map(new Guid("50e93c64-7525-468f-89b8-904badcb0b8b"), typeof(Compze.Tests.Performance.Internals.Tessaging.Hypermedia.PerformanceTestBase.MyRemoteQuery[]));
   }
}
