using System;
using Compze.Abstractions.Internal.Refactoring.Naming;

namespace Compze.Tests.Performance.Internals;

// ReSharper disable All
#pragma warning disable IDE1006,IDE0001,IDE0002,IDE0003,IDE0004,IDE0005,IDE0055,CA1050,CA1707,CA1716

/// <summary>
/// This file is automatically generated. Do not edit manually.
/// Regenerate by running the application when type mappings are missing.
/// </summary>
public sealed class AutoGeneratedCurrentAssemblyTypeMapperForRefactoringSupport : IMapCurrentAssemblyTypesForRefactoringSupport
{
   public void MapTypesForCurrentAssembly(ITypeMappingRegistrar registrar)
   {
      registrar
        .Map<Compze.Tests.Performance.Internals.Tessaging.Hypermedia.PerformanceTestBase.MyLocalStrictlyLocalQuery>("74da5216-4cb5-42f7-a16d-d7337b707ef1")
        .Map<Compze.Tests.Performance.Internals.Tessaging.Hypermedia.PerformanceTestBase.MyRemoteQuery>("329c5f2f-e887-4265-aeba-c54036a7f6b5")
        ;
   }
}
