// <auto-generated>
// This file was generated by CircularLibraryDependencySourceRewriter.
// Changes to this file will be overwritten.
// </auto-generated>
#nullable enable
using System;

namespace Compze.Utilities.Logging;

internal static class ExceptionLogger
{
   public static TResult ExceptionsAndRethrow<TResult>(this ILogger log, Func<TResult> func)
   {
      try
      {
         return func();
      }
      catch(Exception e)
      {
         log.Error(e);
         throw;
      }
   }
}