// <auto-generated>
// This file was generated by CircularLibraryDependencySourceRewriter.
// Changes to this file will be overwritten.
// </auto-generated>
using Compze.Utilities.Functional;

namespace Compze.Utilities.Logging;

// ReSharper disable UnusedMember.Global : These functions are very useful for debugging but only used occasionally. Let's keep them around for now.
// ReSharper disable UnusedType.Global

internal interface ILevelLogger
{
   unit Log(string message);
}

internal abstract class LevelLogger(ILogger logger) : ILevelLogger
{
   protected ILogger Logger { get; } = logger;
   public abstract unit Log(string message);
}

internal class DebugLogger(ILogger logger) : LevelLogger(logger)
{
   public override unit Log(string message) => Logger.Debug(message);
}

internal class InfoLogger(ILogger logger) : LevelLogger(logger)
{
   public override unit Log(string message) => Logger.Info(message);
}

internal class WarningLogger(ILogger logger) : LevelLogger(logger)
{
   public override unit Log(string message) => Logger.Warning(message);
}

internal static class LevelLoggerILoggerExtensions
{
   public static ILevelLogger Debug(this ILogger @this) => new DebugLogger(@this);
   public static ILevelLogger Info(this ILogger @this) => new InfoLogger(@this);
   public static ILevelLogger Warning(this ILogger @this) => new WarningLogger(@this);
}
