// <auto-generated>
// This file was generated by CircularLibraryDependencySourceRewriter.
// Changes to this file will be overwritten.
// </auto-generated>
#nullable enable
using Compze.Utilities.Functional;
using Compze.Utilities.SystemCE.LinqCE;
using System.IO;

namespace Compze.Utilities.SystemCE.IOCE;

internal static class PathCE
{
   public static string ReplaceInvalidCharactersWith(string path, char replacement) =>
      path.mutate(it => Path.GetInvalidFileNameChars()
                            .ForEach(invalidChar => it = it.Replace(invalidChar, replacement)));


}
