// <auto-generated>
// This file was generated by Compze.InternalizedSourceReferences.
// Changes to this file will be overwritten.
// </auto-generated>
#nullable enable
using System;

namespace Compze.Utilities.SystemCE.ThreadingCE;

internal class ComponentUsedByMultipleTransactionsException(Type componentType) :
   InvalidOperationException($"Using a {componentType.FullName} in multiple transactions is not safe. It makes you vulnerable to hard to debug concurrency issues and is therefore not allowed.");
