// <auto-generated>
// This file was generated by Compze.InternalizedSourceReferences.
// Changes to this file will be overwritten.
// </auto-generated>
#nullable enable
using System;
using Compze.Utilities.Functional;

namespace Compze.Utilities.SystemCE.ThreadingCE;

internal static class Throw<TException> where TException : Exception, new()
{
   public static unit If(bool condition) => unit.From(() =>
   {
      if(condition) throw new TException();
   });
}
