// <auto-generated>
// This file was generated by CircularLibraryDependencySourceRewriter.
// Changes to this file will be overwritten.
// </auto-generated>
using System;

namespace Compze.Utilities.SystemCE.ThreadingCE.Testing;

internal class GatedCodeSection : IGatedCodeSection
{
   public IThreadGate EntranceGate { get; }
   public IThreadGate ExitGate { get; }

   public static IGatedCodeSection WithTimeout(TimeSpan timeout) => new GatedCodeSection(timeout);

   GatedCodeSection(TimeSpan timeout)
   {
      EntranceGate = ThreadGate.CreateClosedWithTimeout(timeout);
      ExitGate = ThreadGate.CreateClosedWithTimeout(timeout);
   }

   public IDisposable Enter()
   {
      EntranceGate.AwaitPassThrough();
      return new Disposable(() => ExitGate.AwaitPassThrough());
   }
}
