// <auto-generated>
// This file was generated by CircularLibraryDependencySourceRewriter.
// Changes to this file will be overwritten.
// </auto-generated>
using System;
using System.Transactions;

namespace Compze.Utilities.SystemCE.ThreadingCE.Testing;

internal class TransactionSnapshot(Transaction transaction)
{
   internal class TransactionInformationSnapshot(TransactionInformation information)
   {
      public string LocalIdentifier { get; } = information.LocalIdentifier;
      public Guid DistributedIdentifier { get; } = information.DistributedIdentifier;
      public TransactionStatus Status { get; } = information.Status;
   }

   public IsolationLevel IsolationLevel { get; } = transaction.IsolationLevel;

   public TransactionInformationSnapshot TransactionInformation { get; } = new(transaction.TransactionInformation);

   public static TransactionSnapshot? TakeSnapshot()
   {
      var currentTransaction = Transaction.Current;
      return currentTransaction == null ? null : new TransactionSnapshot(currentTransaction);
   }
}
