// <auto-generated>
// This file was generated by Compze.InternalizedSourceReferences.
// Changes to this file will be overwritten.
// </auto-generated>
#nullable enable
using System;
using System.Threading;
using static Compze.Utilities.Contracts.Assert;

namespace Compze.Utilities.SystemCE.ThreadingCE;

///<summary>Thrown if the <see cref="SingleThreadUseGuard"/> detects a thread change.</summary>
internal class MultiThreadedUseException : InvalidOperationException
{
   ///<summary>Constructs an instance using the supplied arguments to create an informative queuedTessageInformation.</summary>
   public MultiThreadedUseException(object guarded, Thread owningThread, Thread currentThread)
      : base($"Attempt to use {guarded} from thread Id:{currentThread.ManagedThreadId}, Name: {currentThread.Name} when owning thread was Id: {owningThread.ManagedThreadId} Name: {owningThread.Name}") =>
      Argument.NotNull(guarded).NotNull(owningThread).NotNull(currentThread);
}
