// <auto-generated>
// This file was generated by Compze.InternalizedSourceReferences.
// Changes to this file will be overwritten.
// </auto-generated>
#nullable enable
using System;
using System.Threading.Tasks;
using Compze.Utilities.SystemCE.ThreadingCE;
using Compze.Utilities.SystemCE.ThreadingCE.TasksCE;

namespace Compze.Utilities.SystemCE;

///<summary>Simple utility class that calls the supplied action when the instance is disposed. Gets rid of the need to create a ton of small classes to do cleanup.</summary>
internal sealed class AsyncDisposable : IAsyncDisposable
{
   readonly Func<Task> _dispose;

   public AsyncDisposable(Action dispose) => _dispose = dispose.AsAsync();

   public AsyncDisposable(Func<Task> dispose) => _dispose = dispose;

   public AsyncDisposable(Func<ValueTask> dispose) => _dispose = () => dispose().AsTask();

   public async ValueTask DisposeAsync() => await _dispose().caf();

   public static readonly IAsyncDisposable NullOp = new AsyncDisposable(ActionCE.NullOp);
}