// <auto-generated>
// This file was generated by Compze.InternalizedSourceReferences.
// Changes to this file will be overwritten.
// </auto-generated>
#nullable enable
using System;
using Compze.Utilities.Functional;

namespace Compze.Utilities.SystemCE;

internal static class Throw<TException> where TException : Exception, new()
{
   public static unit If(bool condition) => condition ? throw new TException() : unit.Value;
}
