// <auto-generated>
// This file was generated by Compze.InternalizedSourceReferences.
// Changes to this file will be overwritten.
// </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;
using System.Linq;
using Compze.Utilities.Functional;
using Compze.Utilities.SystemCE.ThreadingCE.ResourceAccess;

namespace Compze.Utilities.SystemCE;

internal static class UncatchableExceptionsGatherer
{
   static List<Exception> _exceptions = [];
   static readonly IMonitorCE MonitorCE = IMonitorCE.WithTimeouts(1.Seconds());

   ///<summary>If writing tests to ensure uncatchable exceptions are registered, you need to prevent others from running similar tests at the same time. Use this monitor for that</summary>
   public static readonly IMonitorCE TestingMonitor = IMonitorCE.WithTimeouts(1.Seconds());

   public static unit Register(Exception exception) => MonitorCE.Update(() => _exceptions.Add(exception));

   public static IReadOnlyList<Exception> Exceptions => _exceptions.ToList();

   public static unit ConsumeAndThrowAnyExceptionsGathered() => MonitorCE.Update(() =>
   {
      var exceptions = _exceptions;
      _exceptions = [];
      if(exceptions.Any())
         throw new AggregateException(exceptions);
   });

   public static unit ForceFullGcAllGenerationsAndWaitForFinalizersConsumeAndThrowAnyGatheredExceptions()
   {
      GCCE.ForceFullGcAllGenerationsAndWaitForFinalizers();
      return ConsumeAndThrowAnyExceptionsGathered();
   }
}
