using System;

// ReSharper disable All
namespace Compze.Tests.Unit.Internals;

#pragma warning disable IDE1006,IDE0001,IDE0002,IDE0003,IDE0004,IDE0005,IDE0055,CA1050,CA1707,CA1716

/// <summary>
/// This file is automatically generated. Compze will automatically figure out most types that need to go in here, but some types you may need to add yourself.
/// Compze will tell you so in an exception thought, and you can just paste it in here.
/// Regenerate by running the application when type mappings are missing.
/// </summary>
public sealed class AutoGeneratedCurrentAssemblyTypeMapperForRefactoringSupport
{
   public void MapTypesForCurrentAssembly(Action<Guid, Type> map)
   {
      map(new Guid("e9ff5eda-777b-4749-97cb-79e42b08c937"), typeof(Compze.Tests.Unit.Internals.Serialization.NewtonSoftEventStoreEventSerializerTests.TestEvent));
      map(new Guid("4ab91604-676e-4e13-aac4-b79efb4d9d53"), typeof(Compze.Tests.Unit.Internals.Serialization.NewtonSoftEventStoreEventSerializerTests.TestEvent[]));
      map(new Guid("e7ce8970-ba31-4156-9eed-7979c4fc9c1c"), typeof(Compze.Tests.Unit.Internals.Tessaging.MessageTypeInspector_throws_MessageTypeDesignViolationException_if_.Inspecting_type_for_sending_and_.AtMostOnceCommandSettingMessageIdInDefaultConstructor));
      map(new Guid("2eb18c82-706b-413c-8daf-13a2653d5c79"), typeof(Compze.Tests.Unit.Internals.Tessaging.MessageTypeInspector_throws_MessageTypeDesignViolationException_if_.Inspecting_type_for_sending_and_.AtMostOnceCommandSettingMessageIdInDefaultConstructor[]));
   }
}
