using System;
using Compze.Abstractions.Public;

// ReSharper disable RedundantNameQualifier
// ReSharper disable UnusedTypeParameter
// ReSharper disable MemberHidesStaticFromOuterClass

namespace Compze.Abstractions.Tessaging.Public;

public static class TessageTypes
{
   public static class StrictlyLocal
   {
      public static class Queries
      {
#pragma warning disable CA1724 //Class name conflicts with namespace name.
         public abstract class StrictlyLocalTuery<TTuery, TResult> : IStrictlyLocalTuery<TTuery, TResult> where TTuery : StrictlyLocalTuery<TTuery, TResult>;
#pragma warning restore CA1724 //

         public sealed class EntityLink<TResult>(Guid entityId) : StrictlyLocal.Queries.StrictlyLocalTuery<EntityLink<TResult>, TResult>
            where TResult : IHasPersistentIdentity<Guid>
         {
            public Guid EntityId { get; private set; } = entityId;
         }
      }

      public static class Tommands
      {
         public abstract class StrictlyLocalTommand : IStrictlyLocalTommand;

         public abstract class StrictlyLocalTommand<TResult> : IStrictlyLocalTommand<TResult>;
      }
   }

   public static class Remotable
   {
      public static class AtMostOnce
      {
         //Todo: How can we prtevent UI's from just defaulting to using a constructor that creates a new guid?
         public class AtMostOnceHypermediaTommand : IAtMostOnceHypermediaTommand
         {
            ///<summary>How and when a <see cref="AtMostOnceHypermediaTommand.TessageId"/> is generated is vital to correctly maintain the At most once delivery guarantee. When creating the tommand in the backend service we must generate a new <see cref="AtMostOnceHypermediaTommand.TessageId"/>. When binding the tommand in a UI we must reuse the <see cref="AtMostOnceHypermediaTommand.TessageId"/> generated by the backend. This enum helps make that important distinction explicit in your code.</summary>
            protected enum DeduplicationIdHandling
            {
               ///<summary>When creating the tommand within the owning handler endpoint a new <see cref="AtMostOnceHypermediaTommand.TessageId"/> must be generated. </summary>
               Create,
               ///<summary>When binding the tommand in a UI or when deserializing it is very important to NOT create a new <see cref="AtMostOnceHypermediaTommand.TessageId"/> as this would break the At most once delivery guarantee.</summary>
               Reuse
            }

            ///<summary>How and when a <see cref="TessageId"/> is generated is vital to correctly maintain the At most once delivery guarantee. When creating the tommand in the backend service we must generate a new <see cref="TessageId"/>. When binding the tommand in a UI we must reuse the <see cref="TessageId"/> generated by the backend.</summary>
            protected AtMostOnceHypermediaTommand(DeduplicationIdHandling scenario) => _deduplicationId = scenario == DeduplicationIdHandling.Create ? Guid.CreateVersion7() : Guid.Empty;

            Guid _deduplicationId;

            public Guid TessageId
            {
               get => _deduplicationId;
               set
               {
                  if(_deduplicationId != Guid.Empty)
                  {
                     throw new InvalidOperationException($"Once {nameof(TessageId)} has been set it cannot be changed. It is only settable at all because many UI technologies require it to be.");
                  }

                  _deduplicationId = value;
               }
            }

            ///<summary>Allows for replacing the <see cref="TessageId"/> in the rare cases when that is actually helpful. One example is when a tommand failed to execute due to backend business logic rules and you wish to reuse the entered values in the UI that the tommand is bound to. If you do not change the <see cref="TessageId"/> when doing that the bus will keep returning the response from the first time you sent the tommand.</summary>
            public void ReplaceDeduplicationId() => _deduplicationId = Guid.CreateVersion7();
         }

         public class AtMostOnceTommand<TResult> : AtMostOnceHypermediaTommand, IAtMostOnceTommand<TResult>
         {
            ///<summary>It is important not to set a default value if we are binding values in a UI. That would make it very easy to accidentally break the At most once guarantee. That is why you must pass the enum value here so that we can know what is happening.</summary>
            protected AtMostOnceTommand(DeduplicationIdHandling scenario) : base(scenario) {}
         }
      }

      public static class NonTransactional
      {
         public static class Queries
         {
#pragma warning disable CA1724 //Class name conflicts with namespace name.
            public abstract class Tuery<TResult> : IRemotableTuery<TResult>;
#pragma warning restore CA1724 //Class name conflicts with namespace name.

            public class EntityLink<TResult> : Remotable.NonTransactional.Queries.Tuery<TResult> where TResult : IHasPersistentIdentity<Guid>
            {
               public EntityLink() {}
               public EntityLink(Guid entityId) => EntityId = entityId;
               public EntityLink<TResult> WithId(Guid id) => new(id);
               public Guid EntityId { get; private set; }
            }

            ///<summary>Implement <see cref="IRemotableCreateMyOwnResultTuery{TResult}"/> by passing a func to this base class.</summary>
            public abstract class FuncResultTuery<TResult>(Func<TResult> factory) : Tuery<TResult>, IRemotableCreateMyOwnResultTuery<TResult>
            {
               readonly Func<TResult> _factory = factory;
               public TResult CreateResult() => _factory();
            }

            /// <summary>Implements <see cref="IRemotableCreateMyOwnResultTuery{TResult}"/> by calling the default constructor on <typeparamref name="TResult"/></summary>
            public class NewableResultLink<TResult> : Tuery<TResult>, IRemotableCreateMyOwnResultTuery<TResult>
            {
               static readonly Func<TResult> Constructor = Utilities.SystemCE.ReflectionCE.Constructor.For<TResult>.DefaultConstructor.Instance;
               public TResult CreateResult() => Constructor();
            }
         }
      }

      public static class ExactlyOnce
      {
         public class Tommand : IExactlyOnceTommand
         {
            public Guid TessageId { get; private set; }

            protected Tommand()
               : this(Guid.CreateVersion7()) {}

            Tommand(Guid id) => TessageId = id;
         }
      }
   }
}