using System;
using Compze.Core.Public;

// ReSharper disable RedundantNameQualifier
// ReSharper disable UnusedTypeParameter
// ReSharper disable MemberHidesStaticFromOuterClass

namespace Compze.Core.Tessaging.Public;

public static class TessageTypes
{
   public static class StrictlyLocal
   {
      public static class Tueries
      {
#pragma warning disable CA1724 //Class name conflicts with namespace name.
         public abstract class StrictlyLocalTuery<TTuery, TResult> : IStrictlyLocalTuery<TTuery, TResult> where TTuery : StrictlyLocalTuery<TTuery, TResult>;
#pragma warning restore CA1724 //

         public sealed class EntityLink<TResult>(Guid entityId) : StrictlyLocal.Tueries.StrictlyLocalTuery<EntityLink<TResult>, TResult>
            where TResult : IHasPersistentIdentity<Guid>
         {
            public Guid EntityId { get; private set; } = entityId;
         }
      }

      public static class Tommands
      {
         public abstract class StrictlyLocalTommand : IStrictlyLocalTommand;

         public abstract class StrictlyLocalTommand<TResult> : IStrictlyLocalTommand<TResult>;
      }
   }

   public static class Remotable
   {
      public static class AtMostOnce
      {
         //Todo: How can we prevent UI's from just defaulting to using a constructor that creates a new guid?
         public class AtMostOnceTypermediaTommand : IAtMostOnceTypermediaTommand
         {

            ///<summary>How and when a <see cref="Id"/> is generated is vital to correctly maintain the At most once delivery guarantee. When creating the tommand in the backend service we must generate a new <see cref="Id"/>. When binding the tommand in a UI we must reuse the <see cref="Id"/> generated by the backend.</summary>
            protected AtMostOnceTypermediaTommand() : this(Guid.CreateVersion7()) {}

            protected AtMostOnceTypermediaTommand(Guid id) => Id = new TessageId(id);

            public TessageId Id { get; protected set; }
         }

         public class AtMostOnceTypermediaTommand<TResult> : AtMostOnceTypermediaTommand, IAtMostOnceTommand<TResult>
         {
            protected AtMostOnceTypermediaTommand() : base() {}
            protected AtMostOnceTypermediaTommand(Guid id) : base(id) {}
         }
      }

      public static class NonTransactional
      {
         public static class Tueries
         {
#pragma warning disable CA1724 //Class name conflicts with namespace name.
            public abstract class Tuery<TResult> : IRemotableTuery<TResult>;
#pragma warning restore CA1724 //Class name conflicts with namespace name.

            public class EntityLink<TResult> : Remotable.NonTransactional.Tueries.Tuery<TResult> where TResult : IHasPersistentIdentity<Guid>
            {
               public EntityLink() {}
               public EntityLink(Guid entityId) => EntityId = entityId;
               public EntityLink<TResult> WithId(Guid id) => new(id);
               public Guid EntityId { get; private set; }
            }

            ///<summary>Implement <see cref="IRemotableCreateMyOwnResultTuery{TResult}"/> by passing a func to this base class.</summary>
            public abstract class FuncResultTuery<TResult>(Func<TResult> factory) : Tuery<TResult>, IRemotableCreateMyOwnResultTuery<TResult>
            {
               readonly Func<TResult> _factory = factory;
               public TResult CreateResult() => _factory();
            }

            /// <summary>Implements <see cref="IRemotableCreateMyOwnResultTuery{TResult}"/> by calling the default constructor on <typeparamref name="TResult"/></summary>
            public class NewableResultLink<TResult> : Tuery<TResult>, IRemotableCreateMyOwnResultTuery<TResult>
            {
               static readonly Func<TResult> Constructor = Utilities.SystemCE.ReflectionCE.Constructor.For<TResult>.DefaultConstructor.Instance;
               public TResult CreateResult() => Constructor();
            }
         }
      }

      public static class ExactlyOnce
      {
         public class Tommand : IExactlyOnceTommand
         {
            public TessageId Id { get; private set; }

            protected Tommand()
               : this(Guid.CreateVersion7()) {}

            Tommand(Guid id) => Id = new TessageId(id);
         }
      }
   }
}