// <auto-generated>
// This file was generated by CircularLibraryDependencySourceRewriter.
// Changes to this file will be overwritten.
// </auto-generated>
using System;

namespace Compze.Utilities.SystemCE.ReactiveCE;

internal static class ObservableCE
{
   public static IDisposable Subscribe<TTevent>(this IObservable<TTevent> @this, Action<TTevent> onNext) => @this.Subscribe( new SimpleObserver<TTevent>(onNext: onNext));
}