using System;
using System.Collections.Generic;
using System.Diagnostics.CodeAnalysis;
using System.Globalization;
using System.Linq;
using System.Reflection;
using System.Text;
using Compze.Abstractions.Internal;
using Compze.Abstractions.Internal.Refactoring.Naming;
using Compze.Tessaging.Abstractions;
using Compze.Utilities.SystemCE.ReflectionCE;
using Compze.Utilities.Threading.ResourceAccess;

namespace Compze.Common.Refactoring.Naming;

class TypeMapper : ITypeMapper
{
   private TypeMapper(){}
   internal static ITypeMapper Instance = new TypeMapper();
   static readonly IThreadShared<MappingState> State = ThreadShared.WithDefaultTimeout<MappingState>();

   static TypeMapper()
   {
      EnsureAllCurrentlyLoadedAssembliesHaveBeenCheckedForRequiredMappings();
      AppDomain.CurrentDomain.AssemblyLoad += (a, b) => EnsureAllCurrentlyLoadedAssembliesHaveBeenCheckedForRequiredMappings();
   }

   public TypeId GetId(Type type)
   {
      return State.Read(state =>
      {
         if(state.TypeToTypeIdMap.TryGetValue(type, out var typeId))
         {
            return typeId;
         }

         // Check if we have a stored message for this assembly
         if(state.AssemblyMappingUpdateMessages.TryGetValue(type.Assembly, out var message))
         {
            throw new Exception($"Failed to find TypeId for type: {type.FullName}{Environment.NewLine}{message}");
         }

         throw BuildExceptionDescribingHowToAddMissingMappings([type]);
      });
   }

   public Type GetType(TypeId typeId)
   {
      return State.Read(state =>
      {
         if(state.TypeIdToTypeMap.TryGetValue(typeId, out var type))
         {
            return type;
         }

         throw new Exception($"Could not find type for {nameof(TypeId)}: {typeId}");
      });
   }

   public bool TryGetType(TypeId typeId, [NotNullWhen(true)] out Type? type)
   {
      type = State.Read(state => state.TypeIdToTypeMap.GetValueOrDefault(typeId));
      return type != null;
   }

   public IEnumerable<TypeId> GetIdForTypesAssignableTo(Type type)
   {
      return State.Read(state =>
      {
         var found = state
                    .TypeToTypeIdMap
                    .Keys
                    .Where(type.IsAssignableFrom)
                    .Select(matchingType => state.TypeToTypeIdMap[matchingType])
                    .ToArray();

         if(!found.Any())
         {
            // Check if we have a stored message for this assembly
            if(state.AssemblyMappingUpdateMessages.TryGetValue(type.Assembly, out var message))
            {
               throw new Exception($"Failed to find TypeIds for types assignable to: {type.FullName}{Environment.NewLine}{message}");
            }

            throw BuildExceptionDescribingHowToAddMissingMappings([type]);
         }

         return found;
      });
   }

   public void AssertMappingsExistFor(IEnumerable<Type> typesThatRequireMappings) => State.Update(state =>
   {
      var missing = typesThatRequireMappings.Where(type => !state.TypeToTypeIdMap.ContainsKey(type)).ToList();
      if(missing.Any()) throw BuildExceptionDescribingHowToAddMissingMappings(missing);
   });

   static void AssertTypeValidForMapping(Type type)
   {
      if(type.IsAbstract)
      {
         if(!typeof(IRemotableEvent).IsAssignableFrom(type))
         {
            throw new Exception($"Type: {type.FullName} is abstract and is not a {typeof(IRemotableEvent).FullName}. For other types you should only map concrete types.");
         }
      }
   }

   static void EnsureAllCurrentlyLoadedAssembliesHaveBeenCheckedForRequiredMappings() => State.Update(state =>
   {
      var unHandledAssemblies = AppDomain.CurrentDomain.GetAssemblies().Except(state.CheckedAssemblies);

      foreach(var assembly in unHandledAssemblies)
      {
         {
            if(state.CheckedAssemblies.Contains(assembly))
            {
               return;
            }

            try
            {
               CheckAssemblyForRequiredMappings(assembly, state);
               state.CheckedAssemblies.Add(assembly);
            }
            finally
            {
               state.CheckedAssemblies.Add(assembly);
            }
         }
      }
   });

   static void CheckAssemblyForRequiredMappings(Assembly assembly, MappingState state)
   {
      var typesRequiringMapping = TypeMapperTypeDiscovery.GetTypesRequiringMapping(assembly);
      if(!typesRequiringMapping.Any()) return;
      var assemblyName = assembly.GetName().Name;
      var rootNamespace = assemblyName;
      var autoGeneratedTypeName = $"{rootNamespace}.{TypeMapperSourceCodeGenerator.MappingClassName}";

      var autoGeneratedType = assembly.GetType(autoGeneratedTypeName);

      if(autoGeneratedType == null)
      {
         // Store the message for later use if type mapping fails
         var message = BuildMessageDescribingHowToAddMissingMappings(assembly);
         state.AssemblyMappingUpdateMessages[assembly] = message;
         return;
      }

      var instance = Activator.CreateInstance(autoGeneratedType);
      var method = autoGeneratedType.GetMethod("MapTypesForCurrentAssembly", BindingFlags.Public | BindingFlags.Instance);

      if(method != null && instance != null)
      {
         void MapAction(Guid guid, Type type) => state.Map(type, new TypeId(guid));
         method.Invoke(instance, [(Action<Guid, Type>)MapAction]);
      }

      var typesWithMissingMappings = typesRequiringMapping.Where(type => !state.TypeToTypeIdMap.ContainsKey(type)).ToList();
      if(typesWithMissingMappings.Any())
      {
         // Store the message for later use if type mapping fails
         var message = BuildMessageDescribingHowToAddMissingMappings(assembly);
         state.AssemblyMappingUpdateMessages[assembly] = message;
      }
   }



   static string BuildMessageDescribingHowToAddMissingMappings(Assembly assembly)
   {
      var assemblyName = assembly.GetName().Name;
      var rootNamespace = assemblyName;

      var allTypesRequiringMapping = TypeMapperTypeDiscovery.GetTypesRequiringMapping(assembly);

      // Get existing mappings for types in this assembly from the current TypeMapper state
      var existingMappings = State.Read(state => allTypesRequiringMapping
                                                .Where(type => state.TypeToTypeIdMap.ContainsKey(type))
                                                .ToDictionary(type => type, type => state.TypeToTypeIdMap[type]));

      var generatedCode = TypeMapperSourceCodeGenerator.GenerateAutoGeneratedClassCode(rootNamespace, allTypesRequiringMapping, existingMappings);

      // Try to automatically find the project file and create the mapping
      var createdFilePath = TypeMapperSourceCodeGenerator.TryFindProjectFileAndCreateMapping(assembly, allTypesRequiringMapping, existingMappings);

      var fixMessage = new StringBuilder();

      if(createdFilePath != null)
      {
         // File was auto-generated, but might be in wrong location (e.g., NCrunch temp folder)
         fixMessage.AppendLine(CultureInfo.InvariantCulture,
                               $"""

                                Type mappings were automatically generated for assembly: {assemblyName}
                                File location: {createdFilePath}

                                Please rebuild the project and try again.

                                IMPORTANT: If you are using a test runner like NCrunch that builds in a temporary location,
                                the generated file may not be in your source tree. In that case, please manually create
                                or update the file '{TypeMapperSourceCodeGenerator.MappingFileName}' in the root folder of the project '{assemblyName}'
                                with the following content:

                                """);
      } else
      {
         // Auto-generation failed, provide manual instructions
         fixMessage.AppendLine(CultureInfo.InvariantCulture,
                               $"""

                                In order to allow you to freely rename and move your types without breaking your persisted data you are required to map your types to Guid values that are used in place of your type names in the persisted data.
                                Some such required type mappings are missing for assembly: {assemblyName}

                                Please create a file named '{TypeMapperSourceCodeGenerator.MappingFileName}' in the root folder of the project '{assemblyName}' with the following content:

                                """);
      }

      fixMessage.AppendLine(generatedCode);

      return fixMessage.ToString();
   }

   static Exception BuildExceptionDescribingHowToAddMissingMappings(Assembly assembly)
   {
      return new Exception(BuildMessageDescribingHowToAddMissingMappings(assembly));
   }

   static Exception BuildExceptionDescribingHowToAddMissingMappings(IReadOnlyList<Type> missingTypes)
   {
      var fixMessage = new StringBuilder();

      var firstType = missingTypes[0];
      var missingInTheSameAssembly = missingTypes.TakeWhile(it => it.Assembly == firstType.Assembly).ToList();

      fixMessage.AppendLine(CultureInfo.InvariantCulture,
                            $"""

                             In order to allow you to freely rename and move your types without breaking your persisted data you are required to map your types to Guid values that are used in place of your type names in the persisted data.
                             Some such required type mappings are missing. For convenience you can simply paste in the code below into the file {TypeMapperSourceCodeGenerator.MappingFileName} in the root of the project defining the type:
                             """);

      foreach(var missingType in missingInTheSameAssembly)
      {
         fixMessage.Append(CultureInfo.InvariantCulture, $"{Environment.NewLine}      map(new Guid(\"{Guid.NewGuid()}\"), typeof({missingType.GetFullNameCompilable()}));");
      }

      fixMessage.Append(Environment.NewLine).AppendLine();

      return new Exception(fixMessage.ToString());
   }

   class MappingState
   {
      public readonly Dictionary<Type, TypeId> TypeToTypeIdMap = new();
      public readonly Dictionary<TypeId, Type> TypeIdToTypeMap = new();
      public readonly HashSet<Assembly> CheckedAssemblies = [];
      public readonly Dictionary<Assembly, string> AssemblyMappingUpdateMessages = new();

      internal void Map(Type type, TypeId typeId)
      {
         if(TypeToTypeIdMap.TryGetValue(type, out var existingTypeId))
         {
            if(existingTypeId == typeId) return;
            throw new Exception($"Attempted to map Type:{type.FullName} to: {typeId}, but it is already mapped to: TypeId: {existingTypeId}");
         }

         if(TypeIdToTypeMap.TryGetValue(typeId, out var existingType))
         {
            if(existingType == type) return;
            throw new Exception($"Attempted to map TypeId:{typeId.GuidValue} to: {type.FullName}, but it is already mapped to Type: {existingType.FullName}");
         }

         AssertTypeValidForMapping(type);

         TypeIdToTypeMap.Add(typeId, type);
         TypeToTypeIdMap.Add(type, typeId);
      }
   }
}
