using System;
using System.Collections.Generic;
using System.Diagnostics.CodeAnalysis;
using System.Globalization;
using System.Linq;
using System.Reflection;
using System.Text;
using Compze.Abstractions;
using Compze.Abstractions.Internal;
using Compze.Abstractions.Internal.Refactoring.Naming;
using Compze.Tessaging.Abstractions;
using Compze.Utilities.SystemCE.ReflectionCE;
using Compze.Utilities.SystemCE.ThreadingCE.ResourceAccess;

namespace Compze.Common.Refactoring.Naming;

class TypeMapper : ITypeMapper, ITypeMappingRegistrar
{
   readonly IThreadShared<State> _state = ThreadShared.WithDefaultTimeout<State>();
   readonly HashSet<Assembly> _checkedAssemblies = [];

   public TypeId GetId(Type type)
   {
      EnsureAllCurrentlyLoadedAssembliesHaveBeenCheckedForRequiredMappings();

      return _state.Read(state =>
      {
         if(state.TypeToTypeIdMap.TryGetValue(type, out var typeId))
         {
            return typeId;
         }

         throw BuildExceptionDescribingHowToAddMissingMappings(type);
      });
   }

   public Type GetType(TypeId typeId)
   {
      EnsureAllCurrentlyLoadedAssembliesHaveBeenCheckedForRequiredMappings();

      return _state.Read(state =>
      {
         if(state.TypeIdToTypeMap.TryGetValue(typeId, out var type))
         {
            return type;
         }

         throw new Exception($"Could not find type for {nameof(TypeId)}: {typeId}");
      });
   }

   public bool TryGetType(TypeId typeId, [NotNullWhen(true)] out Type? type)
   {
      EnsureAllCurrentlyLoadedAssembliesHaveBeenCheckedForRequiredMappings();
      type = _state.Read(state => state.TypeIdToTypeMap.TryGetValue(typeId, out var innerType) ? innerType : null);
      return type != null;
   }

   public IEnumerable<TypeId> GetIdForTypesAssignableTo(Type type)
   {
      EnsureAllCurrentlyLoadedAssembliesHaveBeenCheckedForRequiredMappings();

      var found = _state.Read(state => state
                                      .TypeToTypeIdMap
                                      .Keys
                                      .Where(type.IsAssignableFrom)
                                      .Select(matchingType => state.TypeToTypeIdMap[matchingType])
                                      .ToArray());
      if(!found.Any()) throw BuildExceptionDescribingHowToAddMissingMappings(type);
      return found;
   }

   public void AssertMappingsExistFor(IEnumerable<Type> typesThatRequireMappings)
   {
      EnsureAllCurrentlyLoadedAssembliesHaveBeenCheckedForRequiredMappings();
   }

   public ITypeMappingRegistrar Map<TType>(Guid typeIdGuid)
   {
      _state.Update(state => state.Map(typeof(TType), new TypeId(typeIdGuid)));
      return this;
   }

   public ITypeMappingRegistrar Map<TType>(string typeGuid) => Map<TType>(Guid.Parse(typeGuid));

   static void AssertTypeValidForMapping(Type type)
   {
      if(type.IsAbstract)
      {
         if(!typeof(IRemotableEvent).IsAssignableFrom(type))
         {
            throw new Exception($"Type: {type.FullName} is abstract and is not a {typeof(IRemotableEvent).FullName}. For other types you should only map concrete types.");
         }
      }
   }

   void EnsureAllCurrentlyLoadedAssembliesHaveBeenCheckedForRequiredMappings()
   {
      var missingCurrentlyLoadedAssemblies = AppDomain.CurrentDomain.GetAssemblies().Except(_checkedAssemblies);

      foreach(var assembly in missingCurrentlyLoadedAssemblies)
      {
         lock(_checkedAssemblies)
         {
            if(_checkedAssemblies.Contains(assembly))
            {
               continue;
            }

            try
            {
               CheckAssemblyForRequiredMappings(assembly);
               _checkedAssemblies.Add(assembly);
            }
            finally
            {
               _checkedAssemblies.Add(assembly);
            }
         }
      }
   }

   void CheckAssemblyForRequiredMappings(Assembly assembly)
   {
      var typesRequiringMapping = GetTypesRequiringMapping(assembly);
      if(!typesRequiringMapping.Any()) return;
      var assemblyName = assembly.GetName().Name;
      var rootNamespace = assemblyName;
      var autoGeneratedTypeName = $"{rootNamespace}.AutoGeneratedCurrentAssemblyTypeMapperForRefactoringSupport";

      var autoGeneratedType = assembly.GetType(autoGeneratedTypeName);

      if(autoGeneratedType == null) throw BuildExceptionDescribingHowToAddMissingMappings(assembly);

      var instance = Activator.CreateInstance(autoGeneratedType);
      var method = autoGeneratedType.GetMethod("MapTypesForCurrentAssembly", BindingFlags.Public | BindingFlags.Instance);
      
      if(method != null && instance != null)
      {
         Action<Guid, Type> mapAction = (guid, type) => _state.Update(state => state.Map(type, new TypeId(guid)));
         method.Invoke(instance, [mapAction]);
      }

      var typesWithMissingMappings = typesRequiringMapping.Where(type => !_state.Read(state => state.TypeToTypeIdMap.ContainsKey(type))).ToList();
      if(typesWithMissingMappings.Any()) throw BuildExceptionDescribingHowToAddMissingMappings(assembly);
   }

   static bool IsAssemblyWeShouldExamine(Assembly assembly)
   {
      if(assembly.IsDynamic || assembly.FullName == null) return false;

      const string compzeAssemblyNamesStart = "Compze.";

      if(assembly.FullName.StartsWith(compzeAssemblyNamesStart, StringComparison.Ordinal))
         return true;

      if(assembly.GetReferencedAssemblies().Any(name => name.Name != null && name.Name.StartsWith(compzeAssemblyNamesStart, StringComparison.Ordinal)))
         return true;

      return false;
   }

   static ISet<Type> GetTypesRequiringMapping(Assembly assembly)
   {
      if(!IsAssemblyWeShouldExamine(assembly)) return new HashSet<Type>();
      var types = new HashSet<Type>();

      // Get all types defined in the assembly
      var definedTypes = assembly.GetTypes()
                                 .Where(type => !type.IsGenericParameter)
                                 .Where(it => !it.IsOpenGenericType())
                                 .ToList();

      // Add non-generic types and generic type definitions that need mapping
      foreach(var type in definedTypes)
      {
         if(ShouldMapType(type))
         {
            types.Add(type);
            // Also add the array type for each mapped type
            types.Add(type.MakeArrayType());
         }
      }

      // Find all closed generic type instantiations used in this assembly
      foreach(var definedType in definedTypes)
      {
         // Check properties
         foreach(var property in definedType.GetProperties(BindingFlags.Public | BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.Static))
         {
            CollectClosedGenericTypes(property.PropertyType, assembly, types);
         }

         // Check fields
         foreach(var field in definedType.GetFields(BindingFlags.Public | BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.Static))
         {
            CollectClosedGenericTypes(field.FieldType, assembly, types);
         }

         // Check methods (parameters and return types)
         foreach(var method in definedType.GetMethods(BindingFlags.Public | BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.Static))
         {
            CollectClosedGenericTypes(method.ReturnType, assembly, types);
            foreach(var parameter in method.GetParameters())
            {
               CollectClosedGenericTypes(parameter.ParameterType, assembly, types);
            }
         }

         // Check base type
         if(definedType.BaseType != null)
         {
            CollectClosedGenericTypes(definedType.BaseType, assembly, types);
         }

         // Check interfaces
         foreach(var interfaceType in definedType.GetInterfaces())
         {
            CollectClosedGenericTypes(interfaceType, assembly, types);
         }
      }

      return types.OrderBy(type => type.GetFullNameCompilable()).ToHashSet();
   }

   static void CollectClosedGenericTypes(Type type, Assembly targetAssembly, HashSet<Type> collectedTypes)
   {
      // If this is a closed generic type (generic but not a generic type definition)
      if(type.IsGenericType && !type.IsGenericTypeDefinition)
      {
         // Check if any of the type arguments are defined in the target assembly
         var typeArguments = type.GetGenericArguments();
         var hasTypeArgumentFromTargetAssembly = typeArguments.Any(arg =>
                                                                      !arg.IsGenericParameter && arg.Assembly == targetAssembly);

         if(hasTypeArgumentFromTargetAssembly && ShouldMapType(type))
         {
            collectedTypes.Add(type);
         }

         // Recursively check type arguments for nested generics
         foreach(var typeArg in typeArguments)
         {
            if(!typeArg.IsGenericParameter)
            {
               CollectClosedGenericTypes(typeArg, targetAssembly, collectedTypes);
            }
         }
      }

      // Check if the type itself is generic and recurse
      if(type.IsArray)
      {
         CollectClosedGenericTypes(type.GetElementType()!, targetAssembly, collectedTypes);
      }
   }

   static bool ShouldMapType(Type type)
   {
      // Don't map open generic type definitions or generic parameters
      if(type.IsGenericTypeDefinition || type.IsGenericParameter)
      {
         return false;
      }

      // Only map non-abstract types, or abstract types that are IRemotableEvent
      if(type.IsAbstract && !typeof(IRemotableEvent).IsAssignableFrom(type))
      {
         return false;
      }

      // Map if it's an IMessage or implements IHasPersistentIdentity<>
      return typeof(IMessage).IsAssignableFrom(type) ||
             type.GetInterfaces().Any(i => i.IsGenericType && i.GetGenericTypeDefinition() == typeof(IHasPersistentIdentity<>));
   }

   const string MappingClassName = "AutoGeneratedCurrentAssemblyTypeMapperForRefactoringSupport";
   const string MappingFileName = $"{MappingClassName}.cs";

   Exception BuildExceptionDescribingHowToAddMissingMappings(Assembly assembly)
   {
      var assemblyName = assembly.GetName().Name;
      var rootNamespace = assemblyName;

      var allTypesRequiringMapping = GetTypesRequiringMapping(assembly);

      // Get existing mappings for types in this assembly from the current TypeMapper state
      var existingMappings = _state.Read(state => allTypesRequiringMapping
                                                 .Where(type => state.TypeToTypeIdMap.ContainsKey(type))
                                                 .ToDictionary(type => type, type => state.TypeToTypeIdMap[type]));

      var fixMessage = new StringBuilder();

      fixMessage.AppendLine(CultureInfo.InvariantCulture,
                            $"""

                             In order to allow you to freely rename and move your types without breaking your persisted data you are required to map your types to Guid values that are used in place of your type names in the persisted data.
                             Some such required type mappings are missing for assembly: {assemblyName}

                             Please create a file named '{MappingFileName}' in the root folder of the project '{assemblyName}' with the following content:

                             """);

      fixMessage.AppendLine(GenerateAutoGeneratedClassCode(rootNamespace, allTypesRequiringMapping, existingMappings));

      return new Exception(fixMessage.ToString());
   }

   static string GenerateAutoGeneratedClassCode(string? rootNamespace, ISet<Type> typesToMap, Dictionary<Type, TypeId> existingMappings)
   {
      var code = new StringBuilder();

      code.AppendLine("using System;");
      code.AppendLine();
      code.AppendLine(CultureInfo.InvariantCulture, $"namespace {rootNamespace};");
      code.AppendLine();
      code.AppendLine(CultureInfo.InvariantCulture, $"// ReSharper disable All");
      code.AppendLine(CultureInfo.InvariantCulture, $"#pragma warning disable IDE1006,IDE0001,IDE0002,IDE0003,IDE0004,IDE0005,IDE0055,CA1050,CA1707,CA1716");
      code.AppendLine();
      code.AppendLine(CultureInfo.InvariantCulture, $"/// <summary>");
      code.AppendLine(CultureInfo.InvariantCulture, $"/// This file is automatically generated. Do not edit manually.");
      code.AppendLine(CultureInfo.InvariantCulture, $"/// Regenerate by running the application when type mappings are missing.");
      code.AppendLine(CultureInfo.InvariantCulture, $"/// </summary>");
      code.AppendLine(CultureInfo.InvariantCulture, $"public sealed class {MappingClassName}");
      code.AppendLine("{");
      code.AppendLine("   public void MapTypesForCurrentAssembly(Action<Guid, Type> map)");
      code.AppendLine("   {");

      foreach(var type in typesToMap)
      {
         var guid = existingMappings.TryGetValue(type, out var typeId)
                       ? typeId.GuidValue.ToString()
                       : Guid.NewGuid().ToString();
         code.AppendLine(CultureInfo.InvariantCulture, $"      map(new Guid(\"{guid}\"), typeof({type.GetFullNameCompilable()}));");
      }

      code.AppendLine("   }");
      code.AppendLine("}");

      return code.ToString();
   }

   static Exception BuildExceptionDescribingHowToAddMissingMappings(Type missingType)
   {
      var fixMessage = new StringBuilder();

      fixMessage.AppendLine(CultureInfo.InvariantCulture,
                            $"""

                             In order to allow you to freely rename and move your types without breaking your persisted data you are required to map your types to Guid values that are used in place of your type names in the persisted data.
                             Some such required type mappings are missing. For convenience you can simply paste in the code below into the file {MappingFileName} in the root of the defining the type:
                             """);

      fixMessage.Append(CultureInfo.InvariantCulture, $"{Environment.NewLine}      map(new Guid(\"{Guid.NewGuid()}\"), typeof({missingType.GetFullNameCompilable()}));");

      fixMessage.Append(Environment.NewLine).AppendLine();

      return new Exception(fixMessage.ToString());
   }

   class State
   {
      public readonly Dictionary<Type, TypeId> TypeToTypeIdMap = new();
      public readonly Dictionary<TypeId, Type> TypeIdToTypeMap = new();

      internal void Map(Type type, TypeId typeId)
      {
         if(TypeToTypeIdMap.TryGetValue(type, out var existingTypeId))
         {
            if(existingTypeId == typeId) return;
            throw new Exception($"Attempted to map Type:{type.FullName} to: {typeId}, but it is already mapped to: TypeId: {existingTypeId}");
         }

         if(TypeIdToTypeMap.TryGetValue(typeId, out var existingType))
         {
            if(existingType == type) return;
            throw new Exception($"Attempted to map TypeId:{typeId.GuidValue} to: {type.FullName}, but it is already mapped to Type: {existingType.FullName}");
         }

         AssertTypeValidForMapping(type);

         TypeIdToTypeMap.Add(typeId, type);
         TypeToTypeIdMap.Add(type, typeId);
      }
   }
}
