using System.Text.RegularExpressions;

namespace CircularLibraryDependencySourceRewriter;

public static partial class SourceRewriter
{
   public const string AutoGeneratedHeader =
      """
      // <auto-generated>
      // This file was generated by CircularLibraryDependencySourceRewriter.
      // Changes to this file will be overwritten.
      // </auto-generated>

      """;

   static readonly Regex PublicTypeDeclarationPattern = PublicTypeDeclarationRegex();

   public static string MakeTypesInternal(string source)
   {
      var rewritten = PublicTypeDeclarationPattern.Replace(source, match =>
      {
         var whitespace = match.Groups[1].Value;
         var modifiers = match.Groups[2].Value;
         var typeKeyword = match.Groups[3].Value;
         return $"internal{whitespace}{modifiers}{typeKeyword}";
      });

      return AutoGeneratedHeader + rewritten;
   }

   static readonly string[] ExcludedDirectories = ["bin", "obj", "InternalizedSource"];

   public static void RewriteDirectory(string inputDirectory, string outputDirectory)
   {
      if(Directory.Exists(outputDirectory))
         Directory.Delete(outputDirectory, recursive: true);

      foreach(var inputFile in Directory.EnumerateFiles(inputDirectory, "*.cs", SearchOption.AllDirectories))
      {
         var relativePath = Path.GetRelativePath(inputDirectory, inputFile);

         if(IsInExcludedDirectory(relativePath))
            continue;

         var outputFile = Path.Combine(outputDirectory, relativePath);

         Directory.CreateDirectory(Path.GetDirectoryName(outputFile)!);

         var source = File.ReadAllText(inputFile);
         var rewritten = MakeTypesInternal(source);
         File.WriteAllText(outputFile, rewritten);
      }
   }

   [GeneratedRegex(
      @"public(\s+)((?:(?:static|abstract|sealed|partial|unsafe|readonly|ref|file|new)\s+)*)(\bclass\b|\binterface\b|\bstruct\b|\benum\b|\brecord\b|\bdelegate\b)",
      RegexOptions.Compiled)]
   private static partial Regex PublicTypeDeclarationRegex();

   static bool IsInExcludedDirectory(string relativePath)
   {
      var firstSegment = relativePath.Split(Path.DirectorySeparatorChar, Path.AltDirectorySeparatorChar)[0];
      return ExcludedDirectories.Contains(firstSegment, StringComparer.OrdinalIgnoreCase);
   }
}
