using System.Text.RegularExpressions;

namespace CircularLibraryDependencySourceRewriter;

public static partial class SourceRewriter
{
   public const string AutoGeneratedHeader =
      """
      // <auto-generated>
      // This file was generated by CircularLibraryDependencySourceRewriter.
      // Changes to this file will be overwritten.
      // </auto-generated>

      """;

   static readonly Regex PublicTypeDeclarationPattern = PublicTypeDeclarationRegex();

   public static string MakeTypesInternal(string source)
   {
      var rewritten = PublicTypeDeclarationPattern.Replace(source, match =>
      {
         var whitespace = match.Groups[1].Value;
         var modifiers = match.Groups[2].Value;
         var typeKeyword = match.Groups[3].Value;
         return $"internal{whitespace}{modifiers}{typeKeyword}";
      });

      return AutoGeneratedHeader + rewritten;
   }

   [GeneratedRegex(
      @"public(\s+)((?:(?:static|abstract|sealed|partial|unsafe|readonly|ref|file|new)\s+)*)(\bclass\b|\binterface\b|\bstruct\b|\benum\b|\brecord\b|\bdelegate\b)",
      RegexOptions.Compiled)]
   private static partial Regex PublicTypeDeclarationRegex();
}
