using System;

// ReSharper disable All
namespace AccountManagement;

#pragma warning disable IDE1006,IDE0001,IDE0002,IDE0003,IDE0004,IDE0005,IDE0055,CA1050,CA1707,CA1716

/// <summary>
/// This file is automatically generated. Compze will automatically figure out most types that need to go in here, but some types you may need to add yourself.
/// Compze will tell you so in an exception thought, and you can just paste it in here.
/// Regenerate by running the application when type mappings are missing.
/// </summary>
public sealed class AutoGeneratedCurrentAssemblyTypeMapperForRefactoringSupport
{
   public void MapTypesForCurrentAssembly(Action<string, Type> map)
   {
      map("337af6fe-e645-49c7-9da1-b00dbc19cfa6", typeof(AccountManagement.API.AccountResource.Tommand.ChangeEmail));
      map("d4b3f27c-4287-4bbd-bd11-52ed1d3e7738", typeof(AccountManagement.API.AccountResource.Tommand.ChangeEmail[]));
      map("80f95aa8-e751-4446-86cf-b94b603c95db", typeof(AccountManagement.API.AccountResource.Tommand.ChangePassword));
      map("2369e35f-4965-4fc0-ad1e-145ee23d4394", typeof(AccountManagement.API.AccountResource.Tommand.ChangePassword[]));
      map("6603f035-4f35-462d-8bca-152391cadd2e", typeof(AccountManagement.API.AccountResource.Tommand.LogIn));
      map("a835ded6-f1fc-4f56-97d8-d3f3de5aab43", typeof(AccountManagement.API.AccountResource.Tommand.LogIn[]));
      map("099173a3-0d5e-4c26-8566-b33dbf6a5a5a", typeof(AccountManagement.API.AccountResource.Tommand.Register));
      map("a0128d94-8164-44fd-ae43-ade7c5aebe7b", typeof(AccountManagement.API.AccountResource.Tommand.Register[]));
      map("66fc8c2d-aa91-4ef8-ad74-37071359cb53", typeof(Compze.Core.Tessaging.Public.TessageTypes.Remotable.AtMostOnce.AtMostOnceTypermediaTommand<AccountManagement.API.AccountResource.Tommand.LogIn.LoginAttemptResult>));
      map("774d1fb7-5087-40c9-884c-c63a3ddacaae", typeof(Compze.Core.Tessaging.Public.TessageTypes.Remotable.AtMostOnce.AtMostOnceTypermediaTommand<AccountManagement.API.AccountResource.Tommand.Register.RegistrationAttemptResult>));
      map("63dc7b9c-0231-4836-8d62-5c31112d988f", typeof(Compze.Core.Tessaging.Public.TessageTypes.Remotable.NonTransactional.Tueries.NewableResultLink<AccountManagement.API.StartResource>));
      map("af65ba88-4c74-46ad-b293-a9a9feabb1a6", typeof(Compze.Core.Tessaging.Public.TessageTypes.Remotable.NonTransactional.Tueries.TaggregateLink<AccountManagement.API.AccountResource>));
      map("fa6daaec-f8b9-4050-8e7f-a2d3a55cb148", typeof(AccountManagement.Domain.AccountId));
   }
}
