using System;

// ReSharper disable All
namespace AccountManagement.API;

#pragma warning disable IDE1006,IDE0001,IDE0002,IDE0003,IDE0004,IDE0005,IDE0055,CA1050,CA1707,CA1716

/// <summary>
/// This file is automatically generated. Compze will automatically figure out most types that need to go in here, but some types you may need to add yourself.
/// Compze will tell you so in an exception thought, and you can just paste it in here.
/// Regenerate by running the application when type mappings are missing.
/// </summary>
public sealed class AutoGeneratedCurrentAssemblyTypeMapperForRefactoringSupport
{
   public void MapTypesForCurrentAssembly(Action<string, Type> map)
   {
      map("84c1bfcd-a5dd-41e2-ade0-e25bbe0337c3", typeof(AccountManagement.API.AccountResource));
      map("337af6fe-e645-49c7-9da1-b00dbc19cfa6", typeof(AccountManagement.API.AccountResource.Tommand.ChangeEmail));
      map("80f95aa8-e751-4446-86cf-b94b603c95db", typeof(AccountManagement.API.AccountResource.Tommand.ChangePassword));
      map("6603f035-4f35-462d-8bca-152391cadd2e", typeof(AccountManagement.API.AccountResource.Tommand.LogIn));
      map("3822959a-a558-41e6-bdc7-2be7c42e44d9", typeof(AccountManagement.API.AccountResource.Tommand.LogIn.LoginAttemptResult));
      map("099173a3-0d5e-4c26-8566-b33dbf6a5a5a", typeof(AccountManagement.API.AccountResource.Tommand.Register));
      map("ec7a836e-62c8-4946-8433-6f46106f84b0", typeof(AccountManagement.API.AccountResource.Tommand.Register.RegistrationAttemptResult));
      map("bf9b7eb2-98cb-473f-9b58-e07743a3eeb3", typeof(AccountManagement.API.StartResource));
      map("fa6daaec-f8b9-4050-8e7f-a2d3a55cb148", typeof(AccountManagement.Domain.AccountId));
   }
}
