using System;
using Compze.Abstractions.Internal.Refactoring.Naming;

namespace Compze.Tessaging.Teventive.EventStore;

// ReSharper disable All
#pragma warning disable IDE1006,IDE0001,IDE0002,IDE0003,IDE0004,IDE0005,IDE0055,CA1050,CA1707,CA1716

/// <summary>
/// This file is automatically generated. Do not edit manually.
/// Regenerate by running the application when type mappings are missing.
/// </summary>
public sealed class AutoGeneratedCurrentAssemblyTypeMapperForRefactoringSupport : IMapCurrentAssemblyTypesForRefactoringSupport
{
   public void MapTypesForCurrentAssembly(ITypeMappingRegistrar registrar)
   {
      registrar
        .Map<Compze.Tessaging.Teventive.EventStore.Refactoring.Migrations.EndOfAggregateHistoryEventPlaceHolder>("cadeaf59-416a-489e-909d-47d5d1288e00")
        .Map<Compze.Tessaging.Teventive.EventStore.Refactoring.Migrations.EndOfAggregateHistoryEventPlaceHolder[]>("5e81e082-f15c-4bef-9561-5ed6600c23e2")
         ;
   }
}
