using System.Runtime.CompilerServices;

[assembly: InternalsVisibleTo("Compze")]
[assembly: InternalsVisibleTo("Compze.Testing")]
[assembly: InternalsVisibleTo("Compze.Messaging")]
[assembly: InternalsVisibleTo("Compze.DependencyInjection")]
[assembly: InternalsVisibleTo("Compze.Serialization")]
[assembly: InternalsVisibleTo("Compze.Logging")]
[assembly: InternalsVisibleTo("Compze.DocumentDb")]
[assembly: InternalsVisibleTo("Compze.EventStore")]
[assembly: InternalsVisibleTo("Compze.ExternalDependencies")]
[assembly: InternalsVisibleTo("Compze.Tests.Integration.Internals")]
[assembly: InternalsVisibleTo("Compze.Tests.Unit.Internals")]
[assembly: InternalsVisibleTo("Compze.Tests.Performance.Internals")]
[assembly: InternalsVisibleTo("Compze.DependencyInjection.SimpleInjector")]
[assembly: InternalsVisibleTo("Compze.DependencyInjection.Microsoft")]
[assembly: InternalsVisibleTo("Compze.Logging.Serilog")]
[assembly: InternalsVisibleTo("ScratchPad.Internals")]

[assembly: InternalsVisibleTo("Compze.Tests.Unit")]