// <auto-generated>
// This file was generated by CircularLibraryDependencySourceRewriter.
// Changes to this file will be overwritten.
// </auto-generated>
using System;

namespace Compze.Utilities.Contracts;

internal class InvariantViolatedException(string message) : Exception(message);
internal class InvalidResultException(string message) : Exception(message);
