using System;
using Compze.Abstractions.Internal.Refactoring.Naming;

namespace AccountManagement.Server;

// ReSharper disable All
#pragma warning disable IDE1006,IDE0001,IDE0002,IDE0003,IDE0004,IDE0005,IDE0055,CA1050,CA1707,CA1716

/// <summary>
/// This file is automatically generated. Do not edit manually.
/// Regenerate by running the application when type mappings are missing.
/// </summary>
public sealed class AutoGeneratedCurrentAssemblyTypeMapperForRefactoringSupport : IMapCurrentAssemblyTypesForRefactoringSupport
{
   public void MapTypesForCurrentAssembly(ITypeMappingRegistrar registrar)
   {
      registrar
        .Map<AccountManagement.Domain.Account>("0a590232-e973-4267-8e2c-0fdc5026d527")
        .Map<AccountManagement.Domain.Account[]>("f9d41dbe-2bde-4e1b-9bdf-2636a8e9bdf2")
        .Map<AccountManagement.InternalApi.Query.TryGetByEmailQuery>("909e2041-97a8-4f07-a79c-f0b125f85ec4")
        .Map<AccountManagement.InternalApi.Query.TryGetByEmailQuery[]>("2f4a995a-cf18-4815-aede-4abb8e84857f")
        .Map<AccountManagement.UI.QueryModels.AccountQueryModel>("f466a2b1-87e9-43b0-9a6c-2fa457fa4506")
        .Map<AccountManagement.UI.QueryModels.AccountQueryModel[]>("69f5f5d7-4d4c-4393-b1df-ca0566fb134d")
        .Map<AccountManagement.UI.QueryModels.AccountStatistics.SingletonStatisticsQueryModel>("d30959dc-6927-459a-8fc3-50a750fb58dd")
        .Map<AccountManagement.UI.QueryModels.AccountStatistics.SingletonStatisticsQueryModel[]>("26f6bb6d-b755-4cb0-94e7-a810625ae63f")
        .Map<Compze.Tessaging.Abstractions.MessageTypes.StrictlyLocal.Queries.EntityLink<AccountManagement.UI.QueryModels.AccountQueryModel>>("46291871-af0e-4dca-ab8a-af63d21095e7")
        .Map<Compze.Tessaging.Persistence.EventStore.EventStoreApi.CommandApi.SaveAggregate<AccountManagement.Domain.Account>>("f600e211-0681-4358-8c89-ffbc24851d13")
        .Map<Compze.Tessaging.Persistence.EventStore.EventStoreApi.QueryApi.AggregateLink<AccountManagement.Domain.Account>>("88dff393-775f-4944-8892-5c8a7d23ad0f")
        .Map<Compze.Tessaging.Persistence.EventStore.EventStoreApi.QueryApi.GetReadonlyCopyOfAggregate<AccountManagement.Domain.Account>>("e18bf51b-50a5-4eb3-8a99-2a675c6a899c")
        .Map<Compze.Tessaging.Persistence.EventStore.EventStoreApi.QueryApi.GetReadonlyCopyOfAggregateVersion<AccountManagement.Domain.Account>>("ffc26826-ddde-40d2-bc31-ecda9e3e4b98")
        .Map<Compze.Tessaging.Teventive.Aggregate<AccountManagement.Domain.Account,AccountManagement.Domain.Events.AccountEvent.Root,AccountManagement.Domain.Events.AccountEvent.Implementation.Root>>("c883677c-b945-4bc3-add8-624eb3a36676")
        ;
   }
}