// ReSharper disable All

using System;

namespace AccountManagement.Server;

#pragma warning disable IDE1006,IDE0001,IDE0002,IDE0003,IDE0004,IDE0005,IDE0055,CA1050,CA1707,CA1716

/// <summary>
/// This file is automatically generated. Do not edit manually.
/// Regenerate by running the application when type mappings are missing.
/// </summary>
public sealed class AutoGeneratedCurrentAssemblyTypeMapperForRefactoringSupport
{
   public void MapTypesForCurrentAssembly(Action<Guid, Type> map)
   {
      map(new Guid("0a590232-e973-4267-8e2c-0fdc5026d527"), typeof(AccountManagement.Domain.Account));
      map(new Guid("f9d41dbe-2bde-4e1b-9bdf-2636a8e9bdf2"), typeof(AccountManagement.Domain.Account[]));
      map(new Guid("f466a2b1-87e9-43b0-9a6c-2fa457fa4506"), typeof(AccountManagement.UI.QueryModels.AccountQueryModel));
      map(new Guid("69f5f5d7-4d4c-4393-b1df-ca0566fb134d"), typeof(AccountManagement.UI.QueryModels.AccountQueryModel[]));
      map(new Guid("d30959dc-6927-459a-8fc3-50a750fb58dd"), typeof(AccountManagement.UI.QueryModels.AccountStatistics.SingletonStatisticsQueryModel));
      map(new Guid("480ea55d-d44c-4855-a282-eedd8245094b"), typeof(AccountManagement.UI.QueryModels.AccountStatistics.SingletonStatisticsQueryModel[]));
      map(new Guid("81105aea-53a7-4a21-9aaf-3a58a462f5bd"), typeof(Compze.Tessaging.Persistence.EventStore.EventStoreApi.QueryApi.AggregateLink<AccountManagement.Domain.Account>));
      map(new Guid("fe6cbf46-d8af-43e8-be7c-5669d376d7aa"), typeof(Compze.Tessaging.Teventive.Aggregate<AccountManagement.Domain.Account, AccountManagement.Domain.Events.AccountEvent.Root, AccountManagement.Domain.Events.AccountEvent.Implementation.Root>));
   }
}
