using System;
using System.Threading.Tasks;
using Compze.Core.Public;
using Compze.Core.Tessaging.Teventive.Public.Taggregates.BaseClasses.Public;
using Compze.Core.Tessaging.Teventive.Public.Taggregates.Tevents.Public;
using Compze.Core.Tessaging.Teventive.TeventStore.Public;
using Compze.Core.Tessaging.Teventive.TeventStore.QueryModels;
using Compze.Core.Tessaging.Teventive.TeventStore.QueryModels.Generators.Public;
using Compze.Tessaging.Hosting.Testing;
using Compze.Tessaging.Hosting.Testing.Wiring;
using Compze.Tessaging.Teventive.TeventStore.QueryModels.Generators;
using Compze.Tessaging.Teventive.TeventStore.Wiring;
using Compze.Tests.Infrastructure;
using Compze.Tests.Infrastructure.XUnit;
using Compze.Tests.Integration.CQRS.QueryModels.AutoGenerated.Domain;
using Compze.Tests.Integration.CQRS.QueryModels.AutoGenerated.Domain.UI.QueryModels;
using Compze.Utilities.DependencyInjection;
using Compze.Utilities.DependencyInjection.Abstractions;
using Compze.Utilities.SystemCE.TransactionsCE;
using FluentAssertions;
using JetBrains.Annotations;

// ReSharper disable ImplicitlyCapturedClosure

namespace Compze.Tests.Integration.CQRS.QueryModels.AutoGenerated
{
   public class QueryModelGeneratingQueryModelReaderTests : UniversalTestBase
   {
      readonly IServiceLocator _serviceLocator;

      public  QueryModelGeneratingQueryModelReaderTests()
      {
         _serviceLocator = TestEnv.DIContainer.CreateServiceLocatorForTesting(register =>
         {
            register.TeventStore("nonsense");
            register.Register(
               Scoped.For<IQueryModelReader, IVersioningQueryModelReader>().CreatedBy((AccountQueryModelGenerator queryModelGenerator) => new QueryModelGeneratingQueryModelReader([queryModelGenerator])),
               Scoped.For<AccountQueryModelGenerator>().CreatedBy((ITeventStoreReader teventStoreReader) => new AccountQueryModelGenerator(teventStoreReader))
            );
         });
      }

      protected override async Task DisposeAsyncInternal() => await _serviceLocator.DisposeAsync();

      [PCT]public void ThrowsExceptionIfInstanceDoesNotExist()
      {
         using(_serviceLocator.BeginScope())
         {
            var reader = _serviceLocator.Resolve<IQueryModelReader>();
            reader.Invoking(me => me.Get<MyAccountQueryModel>(new EntityId()))
                  .Should().Throw<Exception>();
         }
      }

      [PCT]public void CanFetchQueryModelAfterTaggregateHasBeenCreated()
      {
         using(_serviceLocator.BeginScope())
         {
            var taggregates = _serviceLocator.Resolve<ITeventStoreUpdater>();
            var accountId = new TaggregateId(Guid.Parse("00000000-0000-0000-0000-000000000001"));

            var registered = TransactionScopeCe.Execute(() => MyAccount.Register(taggregates, accountId, "email", "password"));

            registered.Email.Should().Be("email");
            registered.Password.Should().Be("password");

            var reader = _serviceLocator.Resolve<IQueryModelReader>();
            var loadedModel = reader.Get<MyAccountQueryModel>(registered.Id);

            loadedModel.Should().NotBe(null);
            loadedModel.Id.Should().Be(accountId);
            loadedModel.Email.Should().Be(registered.Email);
            loadedModel.Password.Should().Be(registered.Password);
         }
      }

      [PCT]public void ThrowsExceptionWhenTryingToFetchDeletedEntity()
      {
         MyAccount registered;
         using(_serviceLocator.BeginScope())
         {
            var taggregates = _serviceLocator.Resolve<ITeventStoreUpdater>();
            var accountId = new TaggregateId(Guid.Parse("00000000-0000-0000-0000-000000000001"));

            registered = TransactionScopeCe.Execute(() => MyAccount.Register(taggregates, accountId, "email", "password"));

            var reader = _serviceLocator.Resolve<IQueryModelReader>();
            reader.Get<MyAccountQueryModel>(registered.Id); //Here it exists
         }

         using(_serviceLocator.BeginScope())
         {
            TransactionScopeCe.Execute(() => _serviceLocator.Resolve<ITeventStoreUpdater>().Get<MyAccount>(new TaggregateId(registered.Id.PrimitiveValue)).Delete());
         }

         using(_serviceLocator.BeginScope())
         {
            var reader2 = _serviceLocator.Resolve<IQueryModelReader>();
            reader2.Invoking(me => me.Get<MyAccountQueryModel>(registered.Id)).Should().Throw<Exception>();
         }
      }

      [PCT]public void ReturnsUpdatedDataAfterTransactionHasCommitted()
      {
         MyAccount registered;
         using(_serviceLocator.BeginScope())
         {
            var accountId = new TaggregateId(Guid.Parse("00000000-0000-0000-0000-000000000001"));

            var taggregates = _serviceLocator.Resolve<ITeventStoreUpdater>();
            registered = TransactionScopeCe.Execute(() => MyAccount.Register(taggregates, accountId, "email", "password"));

            _serviceLocator.Resolve<IQueryModelReader>()
                           .Get<MyAccountQueryModel>(registered.Id); //Make sure we read it once so caches etc get involved.
         }

         using(_serviceLocator.BeginScope())
         {
            TransactionScopeCe.Execute(() => _serviceLocator.Resolve<ITeventStoreUpdater>().Get<MyAccount>(new TaggregateId(registered.Id.PrimitiveValue)).ChangeEmail("newEmail"));
         }

         using(_serviceLocator.BeginScope())
         {
            var loadedModel = _serviceLocator.Resolve<IQueryModelReader>()
                                             .Get<MyAccountQueryModel>(registered.Id);

            loadedModel.Should().NotBe(null);
            loadedModel.Email.Should().Be("newEmail");
         }
      }

      [PCT]public void CanReturnPreviousVersionsOfQueryModel()
      {
         MyAccount registered;

         using(_serviceLocator.BeginScope())
         {
            var accountId = new TaggregateId(Guid.Parse("00000000-0000-0000-0000-000000000001"));

            var taggregates = _serviceLocator.Resolve<ITeventStoreUpdater>();
            registered = TransactionScopeCe.Execute(() => MyAccount.Register(taggregates, accountId, "originalEmail", "password"));

            _serviceLocator.Resolve<IVersioningQueryModelReader>()
                           .GetVersion<MyAccountQueryModel>(registered.Id, registered.Version); //Make sure we read it once so caches etc get involved.
         }

         using(_serviceLocator.BeginScope())
         {
            TransactionScopeCe.Execute(() =>
            {
               registered = _serviceLocator.Resolve<ITeventStoreUpdater>().Get<MyAccount>(new TaggregateId(registered.Id.PrimitiveValue));
               registered.ChangeEmail("newEmail1");
               registered.ChangeEmail("newEmail2");
               registered.ChangeEmail("newEmail3");
            });
         }

         using(_serviceLocator.BeginScope())
         {
            var loadedModel = _serviceLocator.Resolve<IVersioningQueryModelReader>()
                                             .Get<MyAccountQueryModel>(registered.Id);

            loadedModel.Should().NotBe(null);
            loadedModel.Email.Should().Be("newEmail3");

            _serviceLocator.Resolve<IVersioningQueryModelReader>()
                           .GetVersion<MyAccountQueryModel>(registered.Id, registered.Version - 1)
                           .Email.Should().Be("newEmail2");

            _serviceLocator.Resolve<IVersioningQueryModelReader>()
                           .GetVersion<MyAccountQueryModel>(registered.Id, registered.Version - 2)
                           .Email.Should().Be("newEmail1");

            _serviceLocator.Resolve<IVersioningQueryModelReader>()
                           .GetVersion<MyAccountQueryModel>(registered.Id, registered.Version - 3)
                           .Email.Should().Be("originalEmail");
         }
      }
   }

   namespace Domain
   {
      namespace UI
      {
         namespace QueryModels
         {
            [UsedImplicitly] public class MyAccountQueryModel : ISingleTaggregateQueryModel
            {
               public EntityId<Guid> Id { get; private set; } = new EntityId();
               internal string Email { get; set; } = "";
               internal string Password { get; set; } = "";

               public void SetId(TaggregateId id) => Id = id;
            }

            public class AccountQueryModelGenerator : SingleTaggregateQueryModelGenerator<AccountQueryModelGenerator, MyAccountQueryModel, AccountTevents.IAccountTevent, ITeventStoreReader>
            {
               public AccountQueryModelGenerator(ITeventStoreReader session) : base(session)
               {
                  RegisterHandlers()
                    .For<AccountTevents.PropertyUpdated.IEmail>(e => Model!.Email = e.Email)
                    .For<AccountTevents.PropertyUpdated.IPassword>(e => Model!.Password = e.Password);
               }
            }
         }
      }

      class MyAccount : Taggregate<MyAccount, AccountTevents.IAccountTevent, AccountTevents.AccountTevent>
      {
         MyAccount()
         {
            RegisterTeventAppliers()
              .For<AccountTevents.PropertyUpdated.IEmail>(e => Email = e.Email)
              .For<AccountTevents.PropertyUpdated.IPassword>(e => Password = e.Password)
              .For<AccountTevents.IAccountDeletedTevent>(_ => {});
         }

         public string Email { get; private set; } = "";
         public string Password { get; private set; } = "";

         public void ChangeEmail(string newEmail) => Publish(new AccountTevents.Implementation.EmailChangedTevent(newEmail));

         public static MyAccount Register(ITeventStoreUpdater taggregates, TaggregateId accountId, string email, string password)
         {
            var registered = new MyAccount();
            registered.Publish(new AccountTevents.Implementation.AccountRegisteredTevent(accountId, email, password));
            taggregates.Save(registered);
            return registered;
         }

         public void Delete() => Publish(new AccountTevents.Implementation.AccountDeletedTevent());
      }

      public static class AccountTevents
      {
         public interface IAccountTevent : ITaggregateTevent;

         internal abstract class AccountTevent : TaggregateTevent, IAccountTevent
         {
            protected AccountTevent() {}
            protected AccountTevent(TaggregateId taggregateId) : base(taggregateId) {}
         }

         internal interface IAccountRegisteredTevent : ITaggregateCreatedTevent,
                                                      PropertyUpdated.IEmail,
                                                      PropertyUpdated.IPassword;

         internal interface IEmailChangedTevent : PropertyUpdated.IEmail;

         internal interface IAccountDeletedTevent : IAccountTevent,
                                                   ITaggregateDeletedTevent;

         internal static class PropertyUpdated
         {
            public interface IEmail : IAccountTevent
            {
               string Email { get; }
            }

            public interface IPassword : IAccountTevent
            {
               string Password { get; }
            }
         }

         internal static class Implementation
         {
            public class AccountRegisteredTevent(TaggregateId accountId, string email, string password) : AccountTevent(accountId), IAccountRegisteredTevent
            {
               public string Email { get; private set; } = email;
               public string Password { get; private set; } = password;
            }

            public class EmailChangedTevent(string newEmail) : AccountTevent, IEmailChangedTevent
            {
               public string Email { get; private set; } = newEmail;
            }

            public class AccountDeletedTevent : AccountTevent, IAccountDeletedTevent;
         }
      }
   }
}
