using System;
using Compze.Tessaging.TyperMediaApi.TeventStore;

// ReSharper disable All
namespace AccountManagement;

#pragma warning disable IDE1006,IDE0001,IDE0002,IDE0003,IDE0004,IDE0005,IDE0055,CA1050,CA1707,CA1716

/// <summary>
/// This file is automatically generated. Compze will automatically figure out most types that need to go in here, but some types you may need to add yourself.
/// Compze will tell you so in an exception thought, and you can just paste it in here.
/// Regenerate by running the application when type mappings are missing.
/// </summary>
public sealed class AutoGeneratedCurrentAssemblyTypeMapperForRefactoringSupport
{
   public void MapTypesForCurrentAssembly(Action<Guid, Type> map)
   {
      map(new Guid("57fc716d-d8ca-4224-9f78-4d3b5a7f9ebd"), typeof(AccountManagement.Domain.Account));
      map(new Guid("d0ec9e73-9b87-46e7-b829-3a63f977ff44"), typeof(AccountManagement.Domain.Account[]));
      map(new Guid("aee890be-6bb0-4301-90d5-492b0b42a4a8"), typeof(AccountManagement.UI.QueryModels.AccountQueryModel));
      map(new Guid("862d2fb9-b7a3-46b6-9474-10e11548ee66"), typeof(TeventStoreApi.TueryApi.AggregateLink<AccountManagement.Domain.Account>));
      map(new Guid("423d7914-27fd-42ee-9168-03cb5a078eb3"), typeof(AccountManagement.UI.QueryModels.AccountQueryModel[]));
      map(new Guid("fd494342-f588-4337-b9de-4222da24169e"), typeof(AccountManagement.UI.QueryModels.AccountStatistics.SingletonStatisticsQueryModel));
      map(new Guid("4a780985-00c4-408d-932e-9e4bf6e63c8e"), typeof(AccountManagement.UI.QueryModels.AccountStatistics.SingletonStatisticsQueryModel[]));
      map(new Guid("fe77ba6d-dd23-4dfd-b4f4-9c2759f55bf2"), typeof(Compze.Tessaging.Teventive.Aggregate<AccountManagement.Domain.Account, AccountManagement.Domain.Tevents.AccountTevent.Root, AccountManagement.Domain.Tevents.AccountTevent.Implementation.Root>));
   }
}
