

// ReSharper disable All
namespace Compze.Tessaging;

#pragma warning disable IDE1006,IDE0001,IDE0002,IDE0003,IDE0004,IDE0005,IDE0055,CA1050,CA1707,CA1716

/// <summary>
/// This file is automatically generated. Compze will automatically figure out most types that need to go in here, but some types you may need to add yourself.
/// Compze will tell you so in an exception thought, and you can just paste it in here.
/// Regenerate by running the application when type mappings are missing.
/// </summary>
public sealed class AutoGeneratedCurrentAssemblyTypeMapperForRefactoringSupport
{
   public void MapTypesForCurrentAssembly(Action<string, Type> map)
   {
      map("b1272a58-558d-4f55-a4f1-e74e70fc9ae7", typeof(System.Collections.Generic.List<Compze.Core.Tessaging.Transport.Internal.EndPointAddress>));
      map("e441c4e2-cc09-4331-9dd9-c9790e72987a", typeof(Compze.Tessaging.Implementation.Abstractions.TessageTypesInternal.EndpointInformationQuery));
      map("4b82345e-2cab-4eeb-b55c-46c45ac5fd00", typeof(Compze.Tessaging.Implementation.Abstractions.TessageTypesInternal.EndpointInformationQuery[]));
      map("6fbadb13-f036-4fcb-8a9c-101d74bb76d4", typeof(Compze.Tessaging.Implementation.Abstractions.TessageTypesInternal.NetworkTopologyQuery));
      map("7ce03af4-41e5-4b0b-8fb2-e3c3bbcb7122", typeof(Compze.Tessaging.Implementation.Abstractions.TessageTypesInternal.NetworkTopologyQuery[]));
   }
}
