using System;

// ReSharper disable All
namespace Compze.Tessaging.Abstractions;

#pragma warning disable IDE1006,IDE0001,IDE0002,IDE0003,IDE0004,IDE0005,IDE0055,CA1050,CA1707,CA1716

/// <summary>
/// This file is automatically generated. Compze will automatically figure out most types that need to go in here, but some types you may need to add yourself.
/// Compze will tell you so in an exception thought, and you can just paste it in here.
/// Regenerate by running the application when type mappings are missing.
/// </summary>
public sealed class AutoGeneratedCurrentAssemblyTypeMapperForRefactoringSupport
{
   public void MapTypesForCurrentAssembly(Action<Guid, Type> map)
   {
      map(new Guid("0d68a831-87c0-4d05-8e52-bf063d51b56d"), typeof(Compze.Tessaging.Abstractions.IExactlyOnceEvent));
      map(new Guid("f0bf0312-1300-4ba9-8f0d-eaf460b52337"), typeof(Compze.Tessaging.Abstractions.IExactlyOnceEvent[]));
      map(new Guid("887aad71-52f3-46f8-a26a-e2886941758d"), typeof(Compze.Tessaging.Abstractions.IRemotableEvent));
      map(new Guid("c55a6157-dcc8-4928-a48c-28b2c6f8bd49"), typeof(Compze.Tessaging.Abstractions.IRemotableEvent[]));
      map(new Guid("f1581159-4ff1-4df5-b10b-0680552111b1"), typeof(Compze.Tessaging.Abstractions.MessageTypes.Remotable.AtMostOnce.AtMostOnceHypermediaCommand));
      map(new Guid("ea3be0f8-dbae-4353-87cf-6b4f0294fb5f"), typeof(Compze.Tessaging.Abstractions.MessageTypes.Remotable.AtMostOnce.AtMostOnceHypermediaCommand[]));
      map(new Guid("fcf83cc4-de51-4b17-ab44-741c2d34feb2"), typeof(Compze.Tessaging.Abstractions.MessageTypes.Remotable.ExactlyOnce.Command));
      map(new Guid("308ca648-8424-4c81-adf1-ad90123c9240"), typeof(Compze.Tessaging.Abstractions.MessageTypes.Remotable.ExactlyOnce.Command[]));
   }
}
