using System;
using Compze.Abstractions.Internal.Refactoring.Naming;

namespace Compze.Tessaging.Abstractions;

// ReSharper disable All
#pragma warning disable IDE1006,IDE0001,IDE0002,IDE0003,IDE0004,IDE0005,IDE0055,CA1050,CA1707,CA1716

/// <summary>
/// This file is automatically generated. Do not edit manually.
/// Regenerate by running the application when type mappings are missing.
/// </summary>
public sealed class AutoGeneratedCurrentAssemblyTypeMapperForRefactoringSupport : IMapCurrentAssemblyTypesForRefactoringSupport
{
   public void MapTypesForCurrentAssembly(ITypeMappingRegistrar registrar)
   {
      registrar
        .Map<Compze.Tessaging.Abstractions.IExactlyOnceEvent>("ef6a4b67-86c7-4700-871a-2c02594bc2d5")
        .Map<Compze.Tessaging.Abstractions.IExactlyOnceEvent[]>("213f5fbb-7888-4eec-9601-110a4905fde4")
        .Map<Compze.Tessaging.Abstractions.IRemotableEvent>("15b56aba-13a0-46ea-a416-a5a2d464476d")
        .Map<Compze.Tessaging.Abstractions.IRemotableEvent[]>("9927a08d-b4ea-40b9-ae89-3fa5a183aeb9")
        .Map<Compze.Tessaging.Abstractions.MessageTypes.Remotable.AtMostOnce.AtMostOnceHypermediaCommand>("7ff63737-bf98-416a-844e-11feed56e7cd")
        .Map<Compze.Tessaging.Abstractions.MessageTypes.Remotable.AtMostOnce.AtMostOnceHypermediaCommand[]>("353b6747-86c9-4145-8129-ccb96b9a81a6")
        .Map<Compze.Tessaging.Abstractions.MessageTypes.Remotable.ExactlyOnce.Command>("cd21f148-203a-4097-babc-e25ff51f8d9d")
        .Map<Compze.Tessaging.Abstractions.MessageTypes.Remotable.ExactlyOnce.Command[]>("463f40cb-26f7-46ef-bf19-d79e15afa583")
         ;
   }
}
