using System;

namespace Compze.Tessaging.Abstractions;

// ReSharper disable All
#pragma warning disable IDE1006,IDE0001,IDE0002,IDE0003,IDE0004,IDE0005,IDE0055,CA1050,CA1707,CA1716

/// <summary>
/// This file is automatically generated. Do not edit manually.
/// Regenerate by running the application when type mappings are missing.
/// </summary>
public sealed class AutoGeneratedCurrentAssemblyTypeMapperForRefactoringSupport
{
      public void MapTypesForCurrentAssembly(Action<Guid, Type> map)
   {
      map(new Guid("ef6a4b67-86c7-4700-871a-2c02594bc2d5"), typeof(Compze.Tessaging.Abstractions.IExactlyOnceEvent));
      map(new Guid("213f5fbb-7888-4eec-9601-110a4905fde4"), typeof(Compze.Tessaging.Abstractions.IExactlyOnceEvent[]));
      map(new Guid("15b56aba-13a0-46ea-a416-a5a2d464476d"), typeof(Compze.Tessaging.Abstractions.IRemotableEvent));
      map(new Guid("9927a08d-b4ea-40b9-ae89-3fa5a183aeb9"), typeof(Compze.Tessaging.Abstractions.IRemotableEvent[]));
      map(new Guid("7ff63737-bf98-416a-844e-11feed56e7cd"), typeof(Compze.Tessaging.Abstractions.MessageTypes.Remotable.AtMostOnce.AtMostOnceHypermediaCommand));
      map(new Guid("353b6747-86c9-4145-8129-ccb96b9a81a6"), typeof(Compze.Tessaging.Abstractions.MessageTypes.Remotable.AtMostOnce.AtMostOnceHypermediaCommand[]));
      map(new Guid("cd21f148-203a-4097-babc-e25ff51f8d9d"), typeof(Compze.Tessaging.Abstractions.MessageTypes.Remotable.ExactlyOnce.Command));
      map(new Guid("463f40cb-26f7-46ef-bf19-d79e15afa583"), typeof(Compze.Tessaging.Abstractions.MessageTypes.Remotable.ExactlyOnce.Command[]));
   }
}
