using System.Reflection;
using Compze.Internals.SystemCE.ReflectionCE;

namespace Compze.Abstractions.Refactoring.Naming.Internal.Implementation;

/// <summary>Reads existing TypeId assignments from an assembly's
/// <c>AutoGeneratedCurrentAssemblyTypeMapperForRefactoringSupport</c> class.</summary>
static class AssemblyMappingReader
{
   internal static IReadOnlyDictionary<Type, TypeId> ReadMappings(Assembly assembly)
   {
      var mapperTypes = assembly.GetTypes()
                                .Where(it => it.Name == TypeMapperSourceCodeGenerator.MappingClassName)
                                .ToList();

      if(mapperTypes.Count > 1)
         throw new Exception($"""
                              Found multiple type mappers for assembly:{assembly.FullName}
                              {mapperTypes.Select(it => it.FullName!).Join(Environment.NewLine).Indent()}
                              """);

      var mapperType = mapperTypes.SingleOrDefault();
      if(mapperType == null) return new Dictionary<Type, TypeId>();

      var instance = Activator.CreateInstance(mapperType);
      if(instance == null)
      {
         throw new Exception($"Could not instantiate {mapperType.GetFullNameCompilable()}");
      }

      var method = mapperType.GetMethod(TypeMapperSourceCodeGenerator.MappingMethodName, BindingFlags.Public | BindingFlags.Instance);
      if(method == null)
      {
         throw new Exception($"{mapperType.GetFullNameCompilable()} has no usable {TypeMapperSourceCodeGenerator.MappingMethodName} method");
      }

      var mappings = new Dictionary<Type, TypeId>();
      void MapAction(string guidString, Type type) => mappings[type] = new TypeId(new Guid(guidString));
      method.Invoke(instance, [(Action<string, Type>)MapAction]);
      return mappings;
   }
}
