using System.Globalization;
using System.Reflection;
using System.Text;
using Compze.Internals.SystemCE.ReflectionCE;

namespace Compze.Abstractions.Refactoring.Naming.Internal.Implementation;

/// <summary>Generates human-readable error messages describing missing TypeId mappings
/// and optionally triggers auto-generation of mapping files.</summary>
static class MissingMappingReporter
{
   internal static string BuildAssemblyMappingMessage(Assembly assembly, IReadOnlyDictionary<Type, TypeId> allResolvedMappings)
   {
      var assemblyName = assembly.GetName().Name;
      var rootNamespace = assemblyName;

      var scannedTypes = TypeMapperAssemblyScanner.Scan(assembly);

      var allExplicitTypesForAssembly = scannedTypes.ExplicitlyMappedTypes.ToHashSet();

      // Also include types already mapped from this assembly that weren't found by scanning
      // (manually-added entries the user put in the mapping file)
      var existingAssemblyMappings = allResolvedMappings
                                    .Where(kvp => kvp.Key.Assembly == assembly
                                               && !kvp.Key.IsArray
                                               && (!kvp.Key.IsGenericType || kvp.Key.IsGenericTypeDefinition))
                                    .ToDictionary(kvp => kvp.Key, kvp => kvp.Value);

      foreach(var type in existingAssemblyMappings.Keys)
         allExplicitTypesForAssembly.Add(type);

      var generatedCode = TypeMapperSourceCodeGenerator.GenerateAutoGeneratedClassCode(rootNamespace, allExplicitTypesForAssembly, existingAssemblyMappings);

      var createdFilePath = TypeMapperSourceCodeGenerator.TryFindProjectFileAndCreateMapping(assembly, allExplicitTypesForAssembly, existingAssemblyMappings);

      var fixMessage = new StringBuilder();

      if(createdFilePath != null)
      {
         fixMessage.AppendLine(CultureInfo.InvariantCulture,
                               $"""

                                Type mappings were automatically generated for assembly: {assemblyName}
                                File location: {createdFilePath}

                                Please rebuild the project and try again.

                                IMPORTANT: If you are using a test runner like NCrunch that builds in a temporary location,
                                the generated file may not be in your source tree. In that case, please manually create
                                or update the file '{TypeMapperSourceCodeGenerator.MappingFileName}' in the root folder of the project '{assemblyName}'
                                with the following content:

                                """);
      } else
      {
         fixMessage.AppendLine(CultureInfo.InvariantCulture,
                               $"""

                                In order to allow you to freely rename and move your types without breaking your persisted data you are required to map your types to Guid values that are used in place of your type names in the persisted data.
                                Some such required type mappings are missing for assembly: {assemblyName}

                                Please create a file named '{TypeMapperSourceCodeGenerator.MappingFileName}' in the root folder of the project '{assemblyName}' with the following content:

                                """);
      }

      fixMessage.AppendLine(generatedCode);
      return fixMessage.ToString();
   }

   internal static Exception BuildMissingTypesException(IReadOnlyList<Type> missingTypes)
   {
      var fixMessage = new StringBuilder();

      var firstType = missingTypes[0];
      var missingInTheSameAssembly = missingTypes.TakeWhile(it => it.Assembly == firstType.Assembly).ToList();

      fixMessage.AppendLine(CultureInfo.InvariantCulture,
                            $"""

                             In order to allow you to freely rename and move your types without breaking your persisted data you are required to map your types to Guid values that are used in place of your type names in the persisted data.
                             Some such required type mappings are missing. For convenience you can simply paste in the code below into the file {TypeMapperSourceCodeGenerator.MappingFileName} in the root of the project defining the type:
                             """);

      foreach(var missingType in missingInTheSameAssembly)
         fixMessage.Append(CultureInfo.InvariantCulture, $"{Environment.NewLine}      map(\"{Guid.NewGuid()}\", typeof({missingType.GetFullNameCompilable()}));");

      fixMessage.Append(Environment.NewLine).AppendLine();

      return new Exception(fixMessage.ToString());
   }
}
