// ReSharper disable All
namespace Compze.Typermedia.Client;

#pragma warning disable IDE1006,IDE0001,IDE0002,IDE0003,IDE0004,IDE0005,IDE0055,CA1050,CA1707,CA1716

public sealed class AutoGeneratedCurrentAssemblyTypeMapperForRefactoringSupport
{
   public void MapTypesForCurrentAssembly(Action<string, Type> map)
   {
      map("9c3286ba-6a33-4448-aec0-b33b3d59300a", typeof(TypermediaEndpointInformationQuery));
      map("23d82352-7274-4389-b145-09d70c305147", typeof(TypermediaEndpointInformation));
   }
}
