// <auto-generated>
// This file was generated by CircularLibraryDependencySourceRewriter.
// Changes to this file will be overwritten.
// </auto-generated>
#nullable enable
using System;
using Compze.Utilities.Contracts;

namespace Compze.Utilities.SystemCE;

///<summary>Simple utility class that calls the supplied action when the instance is disposed. Gets rid of the need to create a ton of small classes to do cleanup.</summary>
internal class Disposable : IDisposable
{
   readonly Action _action;

   ///<summary>Constructs an instance that will call <param name="action"> when disposed.</param></summary>
   public Disposable(Action action)
   {
      Assert.Argument.NotNull(action);
      _action = action;
   }

   ///<summary>Invokes the action passed to the constructor.</summary>
   public void Dispose() => _action();

   ///<summary>Constructs an object that will call <param name="action"> when disposed.</param></summary>
   public static IDisposable Create(Action action) => new Disposable(action);

   public static readonly IDisposable NullOp = new Disposable(ActionCE.NullOp);
}