// <auto-generated>
// This file was generated by CircularLibraryDependencySourceRewriter.
// Changes to this file will be overwritten.
// </auto-generated>
#nullable enable
using System;
using Compze.Utilities.SystemCE.ThreadingCE.ResourceAccess;

namespace Compze.Utilities.SystemCE;

internal class LazyCE<TValue>(Func<TValue> factory)
   where TValue : class
{
   readonly IMonitorCE _monitor = IMonitorCE.WithDefaultTimeout();
   TValue? _value;
   readonly Func<TValue> _factory = factory;

   public TValue Value => _monitor.DoubleCheckedLocking(() => _value, () => _value = _factory());

   public TValue? ValueIfInitialized() => _value;

   public void Reset() => _value = null;
}
