// <auto-generated>
// This file was generated by CircularLibraryDependencySourceRewriter.
// Changes to this file will be overwritten.
// </auto-generated>
#nullable enable
namespace Compze.Utilities.SystemCE;

internal static class ObjectCE
{
   ///<summary>Returns string.Empty if ToString() returns null.</summary>
   public static string ToStringCE(this object @this) => @this.ToString() ?? string.Empty;
}
