// <auto-generated>
// This file was generated by CircularLibraryDependencySourceRewriter.
// Changes to this file will be overwritten.
// </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;
using System.Linq;

namespace Compze.Utilities.SystemCE;

///<summary>Contains extensions on <see cref="string"/></summary>
internal static class StringIndenter
{
   public static string IndentToDepth(this string it, string indent, int depth) => it.Split(Environment.NewLine).Select(line => Enumerable.Repeat(indent, depth).Join(string.Empty) + line).Join(Environment.NewLine);
   public static string IndentTab(this string it) => it.IndentToDepth("\t", 1);
   public static string IndentSpaces(this string it, int count = 3) => it.IndentToDepth(" ", count);
   public static string Indent(this string it) => it.IndentSpaces();
   public static string JoinLines(this IEnumerable<string> it) => it.Join(Environment.NewLine);
}
