using System;
using Compze.Abstractions.Internal.Refactoring.Naming;

namespace Compze.Tessaging;

// ReSharper disable All
#pragma warning disable IDE1006,IDE0001,IDE0002,IDE0003,IDE0004,IDE0005,IDE0055,CA1050,CA1707,CA1716

/// <summary>
/// This file is automatically generated. Do not edit manually.
/// Regenerate by running the application when type mappings are missing.
/// </summary>
public sealed class AutoGeneratedCurrentAssemblyTypeMapperForRefactoringSupport : IMapCurrentAssemblyTypesForRefactoringSupport
{
   public void MapTypesForCurrentAssembly(ITypeMappingRegistrar registrar)
   {
      registrar
        .Map<Compze.Tessaging.MessageTypesInternal.EndpointInformationQuery>("39a91062-51b1-4272-bef3-b2d7243dbdfd")
        ;
   }
}
