using System;

// ReSharper disable All
namespace Compze.Tessaging.Teventive.TeventStore;

#pragma warning disable IDE1006,IDE0001,IDE0002,IDE0003,IDE0004,IDE0005,IDE0055,CA1050,CA1707,CA1716

/// <summary>
/// This file is automatically generated. Compze will automatically figure out most types that need to go in here, but some types you may need to add yourself.
/// Compze will tell you so in an exception thought, and you can just paste it in here.
/// Regenerate by running the application when type mappings are missing.
/// </summary>
public sealed class AutoGeneratedCurrentAssemblyTypeMapperForRefactoringSupport
{
   public void MapTypesForCurrentAssembly(Action<string, Type> map)
   {
      map("fa4197d0-747c-4c60-afbc-f978d7ce2487", typeof(Compze.Tessaging.Teventive.TeventStore.Refactoring.Migrations.EndOfTaggregateHistoryTeventPlaceHolder));
      map("3d0fc8a1-7613-4be0-aae3-b089f6a46572", typeof(Compze.Tessaging.Teventive.TeventStore.Refactoring.Migrations.EndOfTaggregateHistoryTeventPlaceHolder[]));
   }
}
