// <auto-generated>
// This file was generated by Compze.InternalizedSourceReferences.
// Changes to this file will be overwritten.
// </auto-generated>
#nullable enable
namespace Compze.Utilities.Logging;

internal enum LogLevel
{
   Error = 0,
   Warning = 1,
   Info = 2,
   Debug = 3
}
