using System;

// ReSharper disable All
namespace Compze.Tests.Integration;

#pragma warning disable IDE1006,IDE0001,IDE0002,IDE0003,IDE0004,IDE0005,IDE0055,CA1050,CA1707,CA1716

/// <summary>
/// This file is automatically generated. Compze will automatically figure out most types that need to go in here, but some types you may need to add yourself.
/// Compze will tell you so in an exception thought, and you can just paste it in here.
/// Regenerate by running the application when type mappings are missing.
/// </summary>
public sealed class AutoGeneratedCurrentAssemblyTypeMapperForRefactoringSupport
{
   public void MapTypesForCurrentAssembly(Action<string, Type> map)
   {
      map("e66484a5-a33b-4ca8-b597-aaec93fd088e", typeof(Compze.Abstractions.Tessaging.Public.TessageTypes.Remotable.AtMostOnce.AtMostOnceTypermediaTommand<Compze.Tests.Integration.Tessaging.ServiceBusSpecification.Given_a_backend_endpoint_with_a_tommand_tevent_and_tuery_handler.Experiment_with_unifying_tevents_and_tommands_test.RegisterUserResult>));
      map("5e156cb3-945e-4995-b9a9-5cee99682388", typeof(Compze.Abstractions.Tessaging.Public.TessageTypes.Remotable.AtMostOnce.AtMostOnceTypermediaTommand<Compze.Tests.Integration.Tessaging.ServiceBusSpecification.Navigator_specification.UserRegisteredConfirmationResource>));
      map("fc463e54-f53d-4704-b964-c50a26aa54bb", typeof(Compze.Core.Tessaging.Teventive.Public.Taggregates.BaseClasses.Public.Taggregate<Compze.Tests.Integration.CQRS.QueryModels.AutoGenerated.Domain.MyAccount,Compze.Tests.Integration.CQRS.QueryModels.AutoGenerated.Domain.IAccountTevent,Compze.Tests.Integration.CQRS.QueryModels.AutoGenerated.Domain.AccountTevent,Compze.Tests.Integration.CQRS.QueryModels.AutoGenerated.Domain.IAccountTevent<Compze.Tests.Integration.CQRS.QueryModels.AutoGenerated.Domain.IAccountTevent>,Compze.Tests.Integration.CQRS.QueryModels.AutoGenerated.Domain.AccountTevent<Compze.Tests.Integration.CQRS.QueryModels.AutoGenerated.Domain.AccountTevent>>));
      map("e78a83aa-848e-48a1-a861-929cf0f5392e", typeof(Compze.Core.Tessaging.Teventive.Public.Taggregates.BaseClasses.Public.Taggregate<Compze.Tests.Integration.CQRS.User,Compze.Tests.Integration.CQRS.IUserTevent,Compze.Tests.Integration.CQRS.UserTevent,Compze.Tests.Integration.CQRS.IUserTevent<Compze.Tests.Integration.CQRS.IUserTevent>,Compze.Tests.Integration.CQRS.UserTevent<Compze.Tests.Integration.CQRS.UserTevent>>));
      map("2858d773-4074-4d57-96df-f1103708d2f8", typeof(Compze.Core.Tessaging.Teventive.Public.Taggregates.BaseClasses.Public.Taggregate<Compze.Tests.Integration.Tessaging.ServiceBusSpecification.Given_a_backend_endpoint_with_a_tommand_tevent_and_tuery_handler.Experiment_with_unifying_tevents_and_tommands_test.UserRegistrarTaggregate,Compze.Tests.Integration.Tessaging.ServiceBusSpecification.Given_a_backend_endpoint_with_a_tommand_tevent_and_tuery_handler.Experiment_with_unifying_tevents_and_tommands_test.IUserRegistrarTevent,Compze.Tests.Integration.Tessaging.ServiceBusSpecification.Given_a_backend_endpoint_with_a_tommand_tevent_and_tuery_handler.Experiment_with_unifying_tevents_and_tommands_test.UserRegistrarTevent,Compze.Tests.Integration.Tessaging.ServiceBusSpecification.Given_a_backend_endpoint_with_a_tommand_tevent_and_tuery_handler.Experiment_with_unifying_tevents_and_tommands_test.IUserRegistrarTevent<Compze.Tests.Integration.Tessaging.ServiceBusSpecification.Given_a_backend_endpoint_with_a_tommand_tevent_and_tuery_handler.Experiment_with_unifying_tevents_and_tommands_test.IUserRegistrarTevent>,Compze.Tests.Integration.Tessaging.ServiceBusSpecification.Given_a_backend_endpoint_with_a_tommand_tevent_and_tuery_handler.Experiment_with_unifying_tevents_and_tommands_test.UserRegistrarTevent<Compze.Tests.Integration.Tessaging.ServiceBusSpecification.Given_a_backend_endpoint_with_a_tommand_tevent_and_tuery_handler.Experiment_with_unifying_tevents_and_tommands_test.UserRegistrarTevent>>));
      map("c73e3979-fb2e-4683-a771-6df7f80dcbe3", typeof(Compze.Core.Tessaging.Teventive.Public.Taggregates.BaseClasses.Public.Taggregate<Compze.Tests.Integration.Tessaging.ServiceBusSpecification.Given_a_backend_endpoint_with_a_tommand_tevent_and_tuery_handler.Experiment_with_unifying_tevents_and_tommands_test.UserTaggregate,Compze.Tests.Integration.Tessaging.ServiceBusSpecification.Given_a_backend_endpoint_with_a_tommand_tevent_and_tuery_handler.Experiment_with_unifying_tevents_and_tommands_test.IUserTevent,Compze.Tests.Integration.Tessaging.ServiceBusSpecification.Given_a_backend_endpoint_with_a_tommand_tevent_and_tuery_handler.Experiment_with_unifying_tevents_and_tommands_test.UserTevent,Compze.Tests.Integration.Tessaging.ServiceBusSpecification.Given_a_backend_endpoint_with_a_tommand_tevent_and_tuery_handler.Experiment_with_unifying_tevents_and_tommands_test.IUserTevent<Compze.Tests.Integration.Tessaging.ServiceBusSpecification.Given_a_backend_endpoint_with_a_tommand_tevent_and_tuery_handler.Experiment_with_unifying_tevents_and_tommands_test.IUserTevent>,Compze.Tests.Integration.Tessaging.ServiceBusSpecification.Given_a_backend_endpoint_with_a_tommand_tevent_and_tuery_handler.Experiment_with_unifying_tevents_and_tommands_test.UserTevent<Compze.Tests.Integration.Tessaging.ServiceBusSpecification.Given_a_backend_endpoint_with_a_tommand_tevent_and_tuery_handler.Experiment_with_unifying_tevents_and_tommands_test.UserTevent>>));
      map("99302c63-3bfc-4e81-a678-16e73ff982c5", typeof(Compze.Tests.Integration.CQRS.IMigratedAfterUserChangedEmailTevent));
      map("496229f0-2eec-45cb-86db-3a5a80e60397", typeof(Compze.Tests.Integration.CQRS.IMigratedAfterUserChangedEmailTevent[]));
      map("3cd859f1-a710-46a6-b3e2-e6b251db6467", typeof(Compze.Tests.Integration.CQRS.IMigratedBeforeUserRegisteredTevent));
      map("d5af48e4-26e9-46de-ac6f-a772b1f3fa63", typeof(Compze.Tests.Integration.CQRS.IMigratedBeforeUserRegisteredTevent[]));
      map("e2a8b2fb-c6b1-455b-a79b-e94b80b44604", typeof(Compze.Tests.Integration.CQRS.IMigratedReplaceUserChangedPasswordTevent));
      map("fbfab85d-a5a5-41ce-93c0-c60cce978d9c", typeof(Compze.Tests.Integration.CQRS.IMigratedReplaceUserChangedPasswordTevent[]));
      map("30e74877-d75a-430c-b466-a50f0dd928b3", typeof(Compze.Tests.Integration.CQRS.ISomeTevent));
      map("dae68483-1782-4ab4-948f-c007cf58c94e", typeof(Compze.Tests.Integration.CQRS.ISomeTevent[]));
      map("3996caab-5f71-4dd5-878f-83a0100f354e", typeof(Compze.Tests.Integration.CQRS.IUserChangedEmail));
      map("0cbf5ec8-250f-4514-b2c8-99a456c54623", typeof(Compze.Tests.Integration.CQRS.IUserChangedEmail[]));
      map("190ee130-3c7c-4369-af3c-3a5d96ec2e2b", typeof(Compze.Tests.Integration.CQRS.IUserChangedPassword));
      map("e04140e9-b9f4-43f4-be26-644ed7eea961", typeof(Compze.Tests.Integration.CQRS.IUserChangedPassword[]));
      map("156f8363-0bd9-4553-b4b9-33a7c2825d02", typeof(Compze.Tests.Integration.CQRS.IUserRegistered));
      map("4b2a4692-01ba-4f3c-a464-23bf943bf7dd", typeof(Compze.Tests.Integration.CQRS.IUserRegistered[]));
      map("2e2ec47b-e609-4f62-8ba6-1d322936e2c8", typeof(Compze.Tests.Integration.CQRS.IUserTevent));
      map("f1873a0f-a867-4ebd-ae9e-59b4def8d9b3", typeof(Compze.Tests.Integration.CQRS.IUserTevent[]));
      map("f63f065e-3aef-4151-898c-36fdb42c5ffc", typeof(Compze.Tests.Integration.CQRS.IUserTevent<Compze.Tests.Integration.CQRS.IUserTevent>));
      map("b88c60c5-1142-4e6d-aca5-abb80f13496d", typeof(Compze.Tests.Integration.CQRS.MigratedAfterUserChangedEmailTevent));
      map("d90e88f3-9cb3-466d-a6e4-ccd9b9dfe087", typeof(Compze.Tests.Integration.CQRS.MigratedAfterUserChangedEmailTevent[]));
      map("4909cca8-2391-4541-8bb3-5b73e5d8fa3c", typeof(Compze.Tests.Integration.CQRS.MigratedBeforeUserRegisteredTevent));
      map("df6ef628-6e3e-4109-b451-cf2300a764a5", typeof(Compze.Tests.Integration.CQRS.MigratedBeforeUserRegisteredTevent[]));
      map("17b3dd26-0633-4525-824c-4f695435975a", typeof(Compze.Tests.Integration.CQRS.MigratedReplaceUserChangedPasswordTevent));
      map("141a5cb0-0ac6-4b37-a333-e5b75e0cf7fa", typeof(Compze.Tests.Integration.CQRS.MigratedReplaceUserChangedPasswordTevent[]));
      map("3d805028-547b-4c63-bbab-1c9b7a2f69b0", typeof(Compze.Tests.Integration.CQRS.QueryModels.AutoGenerated.Domain.AccountTevent));
      map("960522ba-08a4-45d1-9df0-f37fc35c3100", typeof(Compze.Tests.Integration.CQRS.QueryModels.AutoGenerated.Domain.AccountTevent.AccountRegisteredTevent));
      map("5bf79ee5-6b43-4ad8-8406-20f5743cbf0c", typeof(Compze.Tests.Integration.CQRS.QueryModels.AutoGenerated.Domain.AccountTevent.AccountRegisteredTevent[]));
      map("ecb9b22e-814e-4432-af83-42db5943f146", typeof(Compze.Tests.Integration.CQRS.QueryModels.AutoGenerated.Domain.AccountTevent.Deleted));
      map("206e94a2-3352-4f6a-b3ed-e3d4db3e74e2", typeof(Compze.Tests.Integration.CQRS.QueryModels.AutoGenerated.Domain.AccountTevent.Deleted[]));
      map("b2b9587a-9efa-42b7-8242-4099439599a8", typeof(Compze.Tests.Integration.CQRS.QueryModels.AutoGenerated.Domain.AccountTevent.EmailChanged));
      map("adf0d27f-aae1-4cbf-a00a-ba41d259e4d1", typeof(Compze.Tests.Integration.CQRS.QueryModels.AutoGenerated.Domain.AccountTevent.EmailChanged[]));
      map("ae560039-8fc1-4013-8e89-124ccb717255", typeof(Compze.Tests.Integration.CQRS.QueryModels.AutoGenerated.Domain.AccountTevent[]));
      map("aaca8850-b2c8-4258-a354-c2c3516a76b1", typeof(Compze.Tests.Integration.CQRS.QueryModels.AutoGenerated.Domain.AccountTevent<Compze.Tests.Integration.CQRS.QueryModels.AutoGenerated.Domain.AccountTevent>));
      map("5332e68a-ea2a-4a48-b044-0f6e03ddd113", typeof(Compze.Tests.Integration.CQRS.QueryModels.AutoGenerated.Domain.IAccountTevent));
      map("86ed29e7-f686-4537-aa82-87c7a0101043", typeof(Compze.Tests.Integration.CQRS.QueryModels.AutoGenerated.Domain.IAccountTevent.Deleted));
      map("3c5c82aa-11fe-40ff-b75f-7b66fe349ade", typeof(Compze.Tests.Integration.CQRS.QueryModels.AutoGenerated.Domain.IAccountTevent.Deleted[]));
      map("5c729264-90f2-44f3-87fd-087d112b0e75", typeof(Compze.Tests.Integration.CQRS.QueryModels.AutoGenerated.Domain.IAccountTevent.IAccountRegisteredTevent));
      map("e20233a5-ef02-4cce-bf31-fcda85b9d21e", typeof(Compze.Tests.Integration.CQRS.QueryModels.AutoGenerated.Domain.IAccountTevent.IAccountRegisteredTevent[]));
      map("224b5fe4-4c91-4c7a-9765-ceee9514a8d2", typeof(Compze.Tests.Integration.CQRS.QueryModels.AutoGenerated.Domain.IAccountTevent.IEmailChanged));
      map("2c4092fb-37c9-4fe9-8ab0-f3f2f797c50e", typeof(Compze.Tests.Integration.CQRS.QueryModels.AutoGenerated.Domain.IAccountTevent.IEmailChanged[]));
      map("c301b17e-3fc6-43f5-ac77-2b78c90fb3be", typeof(Compze.Tests.Integration.CQRS.QueryModels.AutoGenerated.Domain.IAccountTevent.PropertyUpdated.Email));
      map("e79108ce-1f42-42e6-8d74-5db3e2601bc8", typeof(Compze.Tests.Integration.CQRS.QueryModels.AutoGenerated.Domain.IAccountTevent.PropertyUpdated.Email[]));
      map("3c567c7c-db63-4834-9623-5c846138e1d3", typeof(Compze.Tests.Integration.CQRS.QueryModels.AutoGenerated.Domain.IAccountTevent.PropertyUpdated.Password));
      map("0a1873bf-7a71-4a90-a9e2-c7d756994603", typeof(Compze.Tests.Integration.CQRS.QueryModels.AutoGenerated.Domain.IAccountTevent.PropertyUpdated.Password[]));
      map("f07e895d-5aa2-493d-9b32-e5ab22bf349c", typeof(Compze.Tests.Integration.CQRS.QueryModels.AutoGenerated.Domain.IAccountTevent[]));
      map("96ff0613-6566-4c01-a406-2573875b312a", typeof(Compze.Tests.Integration.CQRS.QueryModels.AutoGenerated.Domain.IAccountTevent<Compze.Tests.Integration.CQRS.QueryModels.AutoGenerated.Domain.IAccountTevent>));
      map("e687cbda-629a-4b9b-a5ec-1a3964ee6e59", typeof(Compze.Tests.Integration.CQRS.QueryModels.AutoGenerated.Domain.MyAccount));
      map("f3a9b887-f2e9-40d6-8072-4ce0319f3170", typeof(Compze.Tests.Integration.CQRS.QueryModels.AutoGenerated.Domain.MyAccount[]));
      map("9ca59132-20b5-4f68-bfa0-ba79c993f873", typeof(Compze.Tests.Integration.CQRS.QueryModels.AutoGenerated.Domain.UI.QueryModels.MyAccountQueryModel));
      map("5e9c32c8-010c-4a58-a4e4-66606d9641c8", typeof(Compze.Tests.Integration.CQRS.QueryModels.AutoGenerated.Domain.UI.QueryModels.MyAccountQueryModel[]));
      map("b5f31ed2-fdc1-4342-927c-60cb524b462b", typeof(Compze.Tests.Integration.CQRS.SomeTevent));
      map("e4013006-9ff2-4815-8df6-9533e281ac5e", typeof(Compze.Tests.Integration.CQRS.SomeTevent[]));
      map("b07901c6-2b5d-4348-8894-4603773ce698", typeof(Compze.Tests.Integration.CQRS.User));
      map("d19a5f38-6c3e-4efe-8bd5-831d4a33de96", typeof(Compze.Tests.Integration.CQRS.User[]));
      map("00ef87d3-3a51-431d-9e63-ca230725e241", typeof(Compze.Tests.Integration.CQRS.UserChangedEmail));
      map("d26b748a-21fb-4a42-9e58-92c07910a88f", typeof(Compze.Tests.Integration.CQRS.UserChangedEmail[]));
      map("ca16af4b-f792-434d-87ec-9e879b6ac079", typeof(Compze.Tests.Integration.CQRS.UserChangedPassword));
      map("da5406a6-06d9-451c-8d27-0d2a9d688e43", typeof(Compze.Tests.Integration.CQRS.UserChangedPassword[]));
      map("2cd960ed-51aa-4a15-a620-685dad7b0566", typeof(Compze.Tests.Integration.CQRS.UserRegistered));
      map("d5b33278-9a6e-4446-9678-97be02258954", typeof(Compze.Tests.Integration.CQRS.UserRegistered[]));
      map("1db99ec2-c861-4fb9-b40e-aba68d827a39", typeof(Compze.Tests.Integration.CQRS.UserTevent));
      map("822bf0d4-fb54-4c28-af3d-d7b2a58010fa", typeof(Compze.Tests.Integration.CQRS.UserTevent[]));
      map("dd1f8fb2-0e22-4cc2-aac8-a987834c564e", typeof(Compze.Tests.Integration.CQRS.UserTevent<Compze.Tests.Integration.CQRS.UserTevent>));
      map("c99427b6-af20-4cac-8170-927f22f8850b", typeof(Compze.Tests.Integration.Tessaging.ServiceBusSpecification.Given_a_backend_endpoint_with_a_tommand_tevent_and_tuery_handler.Experiment_with_unifying_tevents_and_tommands_test.GetUserTuery));
      map("f49babde-c596-42cf-b91f-1b6b193a2348", typeof(Compze.Tests.Integration.Tessaging.ServiceBusSpecification.Given_a_backend_endpoint_with_a_tommand_tevent_and_tuery_handler.Experiment_with_unifying_tevents_and_tommands_test.GetUserTuery[]));
      map("84e7eb50-da79-44a4-aab8-ac8332874732", typeof(Compze.Tests.Integration.Tessaging.ServiceBusSpecification.Given_a_backend_endpoint_with_a_tommand_tevent_and_tuery_handler.Experiment_with_unifying_tevents_and_tommands_test.IUserRegistrarTevent));
      map("8644214b-5f5d-4859-9992-d2025eacca0e", typeof(Compze.Tests.Integration.Tessaging.ServiceBusSpecification.Given_a_backend_endpoint_with_a_tommand_tevent_and_tuery_handler.Experiment_with_unifying_tevents_and_tommands_test.IUserRegistrarTevent[]));
      map("4248883d-c2aa-42d5-aae9-8a7f45dc868f", typeof(Compze.Tests.Integration.Tessaging.ServiceBusSpecification.Given_a_backend_endpoint_with_a_tommand_tevent_and_tuery_handler.Experiment_with_unifying_tevents_and_tommands_test.IUserRegistrarTevent<Compze.Tests.Integration.Tessaging.ServiceBusSpecification.Given_a_backend_endpoint_with_a_tommand_tevent_and_tuery_handler.Experiment_with_unifying_tevents_and_tommands_test.IUserRegistrarTevent>));
      map("683a13a6-7d2b-40b9-b1ce-c45c7cafc960", typeof(Compze.Tests.Integration.Tessaging.ServiceBusSpecification.Given_a_backend_endpoint_with_a_tommand_tevent_and_tuery_handler.Experiment_with_unifying_tevents_and_tommands_test.IUserTevent));
      map("e5a8d8da-5c2c-4ba0-ac28-cb7e1b02134f", typeof(Compze.Tests.Integration.Tessaging.ServiceBusSpecification.Given_a_backend_endpoint_with_a_tommand_tevent_and_tuery_handler.Experiment_with_unifying_tevents_and_tommands_test.IUserTevent.UserRegistered));
      map("1ee66257-c6cb-4b65-8e87-48c80d74dd0a", typeof(Compze.Tests.Integration.Tessaging.ServiceBusSpecification.Given_a_backend_endpoint_with_a_tommand_tevent_and_tuery_handler.Experiment_with_unifying_tevents_and_tommands_test.IUserTevent.UserRegistered[]));
      map("5e8919bd-0471-4980-9b90-630b3cdd2b59", typeof(Compze.Tests.Integration.Tessaging.ServiceBusSpecification.Given_a_backend_endpoint_with_a_tommand_tevent_and_tuery_handler.Experiment_with_unifying_tevents_and_tommands_test.IUserTevent[]));
      map("fef64e41-34d5-492a-b7f4-cc6bbd73e262", typeof(Compze.Tests.Integration.Tessaging.ServiceBusSpecification.Given_a_backend_endpoint_with_a_tommand_tevent_and_tuery_handler.Experiment_with_unifying_tevents_and_tommands_test.IUserTevent<Compze.Tests.Integration.Tessaging.ServiceBusSpecification.Given_a_backend_endpoint_with_a_tommand_tevent_and_tuery_handler.Experiment_with_unifying_tevents_and_tommands_test.IUserTevent>));
      map("91ea880a-606b-43aa-b586-f56038262578", typeof(Compze.Tests.Integration.Tessaging.ServiceBusSpecification.Given_a_backend_endpoint_with_a_tommand_tevent_and_tuery_handler.Experiment_with_unifying_tevents_and_tommands_test.UserRegistrarTaggregate));
      map("cb6351c8-7cb0-4ac5-b426-56b4b2c0c6b1", typeof(Compze.Tests.Integration.Tessaging.ServiceBusSpecification.Given_a_backend_endpoint_with_a_tommand_tevent_and_tuery_handler.Experiment_with_unifying_tevents_and_tommands_test.UserRegistrarTaggregate[]));
      map("e106e812-9ab4-4256-aad5-1f9ef8602a94", typeof(Compze.Tests.Integration.Tessaging.ServiceBusSpecification.Given_a_backend_endpoint_with_a_tommand_tevent_and_tuery_handler.Experiment_with_unifying_tevents_and_tommands_test.UserRegistrarTevent));
      map("eebf0412-f759-49d1-bd7e-cc764dffae99", typeof(Compze.Tests.Integration.Tessaging.ServiceBusSpecification.Given_a_backend_endpoint_with_a_tommand_tevent_and_tuery_handler.Experiment_with_unifying_tevents_and_tommands_test.UserRegistrarTevent.Created));
      map("fac7e889-c4ce-4743-9902-171d35abeddd", typeof(Compze.Tests.Integration.Tessaging.ServiceBusSpecification.Given_a_backend_endpoint_with_a_tommand_tevent_and_tuery_handler.Experiment_with_unifying_tevents_and_tommands_test.UserRegistrarTevent.Created[]));
      map("bcf05226-f517-4f94-bd7e-cea6b2c7e6ff", typeof(Compze.Tests.Integration.Tessaging.ServiceBusSpecification.Given_a_backend_endpoint_with_a_tommand_tevent_and_tuery_handler.Experiment_with_unifying_tevents_and_tommands_test.UserRegistrarTevent[]));
      map("d45e67b4-a9ee-41bd-95d2-a5123efea643", typeof(Compze.Tests.Integration.Tessaging.ServiceBusSpecification.Given_a_backend_endpoint_with_a_tommand_tevent_and_tuery_handler.Experiment_with_unifying_tevents_and_tommands_test.UserRegistrarTevent<Compze.Tests.Integration.Tessaging.ServiceBusSpecification.Given_a_backend_endpoint_with_a_tommand_tevent_and_tuery_handler.Experiment_with_unifying_tevents_and_tommands_test.UserRegistrarTevent>));
      map("3893e38f-eea6-412d-bde0-0b2e7c10f5e2", typeof(Compze.Tests.Integration.Tessaging.ServiceBusSpecification.Given_a_backend_endpoint_with_a_tommand_tevent_and_tuery_handler.Experiment_with_unifying_tevents_and_tommands_test.UserRegistrarTommand.RegisterUserTypermediaTommand));
      map("0770a032-5982-486b-8021-356454152458", typeof(Compze.Tests.Integration.Tessaging.ServiceBusSpecification.Given_a_backend_endpoint_with_a_tommand_tevent_and_tuery_handler.Experiment_with_unifying_tevents_and_tommands_test.UserRegistrarTommand.RegisterUserTypermediaTommand[]));
      map("c2ce6605-fbf7-499d-ae26-e3451cb1be0b", typeof(Compze.Tests.Integration.Tessaging.ServiceBusSpecification.Given_a_backend_endpoint_with_a_tommand_tevent_and_tuery_handler.Experiment_with_unifying_tevents_and_tommands_test.UserTaggregate));
      map("98fbf516-9a8e-48c2-aec3-5c9a42204912", typeof(Compze.Tests.Integration.Tessaging.ServiceBusSpecification.Given_a_backend_endpoint_with_a_tommand_tevent_and_tuery_handler.Experiment_with_unifying_tevents_and_tommands_test.UserTaggregate[]));
      map("ac02b095-ede5-4092-8ff1-62b2f42ebfc3", typeof(Compze.Tests.Integration.Tessaging.ServiceBusSpecification.Given_a_backend_endpoint_with_a_tommand_tevent_and_tuery_handler.Experiment_with_unifying_tevents_and_tommands_test.UserTevent));
      map("8db983bd-7921-4211-8541-a3cafc828e3e", typeof(Compze.Tests.Integration.Tessaging.ServiceBusSpecification.Given_a_backend_endpoint_with_a_tommand_tevent_and_tuery_handler.Experiment_with_unifying_tevents_and_tommands_test.UserTevent.UserRegisteredTevent));
      map("4ddd5719-bea7-4e02-8de8-f106564ab1f0", typeof(Compze.Tests.Integration.Tessaging.ServiceBusSpecification.Given_a_backend_endpoint_with_a_tommand_tevent_and_tuery_handler.Experiment_with_unifying_tevents_and_tommands_test.UserTevent.UserRegisteredTevent[]));
      map("4e4d8319-d45d-4a09-81ac-e55544344057", typeof(Compze.Tests.Integration.Tessaging.ServiceBusSpecification.Given_a_backend_endpoint_with_a_tommand_tevent_and_tuery_handler.Experiment_with_unifying_tevents_and_tommands_test.UserTevent[]));
      map("063b0933-982a-44b2-82a7-f07aa000df55", typeof(Compze.Tests.Integration.Tessaging.ServiceBusSpecification.Given_a_backend_endpoint_with_a_tommand_tevent_and_tuery_handler.Experiment_with_unifying_tevents_and_tommands_test.UserTevent<Compze.Tests.Integration.Tessaging.ServiceBusSpecification.Given_a_backend_endpoint_with_a_tommand_tevent_and_tuery_handler.Experiment_with_unifying_tevents_and_tommands_test.UserTevent>));
      map("dec2aa55-eb86-4b37-ac6a-e7cd4987ff4b", typeof(Compze.Tests.Integration.Tessaging.ServiceBusSpecification.Navigator_specification.GetUserTuery));
      map("367dfd85-b5bc-4a4d-8627-8f9b5e96c4a0", typeof(Compze.Tests.Integration.Tessaging.ServiceBusSpecification.Navigator_specification.GetUserTuery[]));
      map("0a6eb5a4-13b9-419c-a145-d6cd3df5c420", typeof(Compze.Tests.Integration.Tessaging.ServiceBusSpecification.Navigator_specification.RegisterUserTypermediaTommand));
      map("e84dd406-2f15-4cb7-8fb2-41f57958f83c", typeof(Compze.Tests.Integration.Tessaging.ServiceBusSpecification.Navigator_specification.RegisterUserTypermediaTommand[]));
      map("c270b8eb-b4e1-4bd8-b0de-dae0e2eb14ce", typeof(Compze.Tests.Integration.Tessaging.ServiceBusSpecification.Navigator_specification.UserApiStartPageTuery));
      map("2b126b66-59f3-4cc9-a93b-04fc6c80961b", typeof(Compze.Tests.Integration.Tessaging.ServiceBusSpecification.Navigator_specification.UserApiStartPageTuery[]));
      map("108a37b8-953d-4cd2-af25-b7c853056e8b", typeof(Compze.Tests.Integration.Tessaging.ServiceBusSpecification.When_scheduling_tommands_to_be_sent_in_the_future.ScheduledTommand));
      map("06931a64-e7df-4f39-9394-f998b04c78e4", typeof(Compze.Tests.Integration.Tessaging.ServiceBusSpecification.When_scheduling_tommands_to_be_sent_in_the_future.ScheduledTommand[]));
   }
}
