using System;

// ReSharper disable All
namespace Compze.Tests.Integration;

#pragma warning disable IDE1006,IDE0001,IDE0002,IDE0003,IDE0004,IDE0005,IDE0055,CA1050,CA1707,CA1716

/// <summary>
/// This file is automatically generated. Compze will automatically figure out most types that need to go in here, but some types you may need to add yourself.
/// Compze will tell you so in an exception thought, and you can just paste it in here.
/// Regenerate by running the application when type mappings are missing.
/// </summary>
public sealed class AutoGeneratedCurrentAssemblyTypeMapperForRefactoringSupport
{
   public void MapTypesForCurrentAssembly(Action<string, Type> map)
   {
      map("99302c63-3bfc-4e81-a678-16e73ff982c5", typeof(Compze.Tests.Integration.CQRS.IMigratedAfterUserChangedEmailTevent));
      map("3cd859f1-a710-46a6-b3e2-e6b251db6467", typeof(Compze.Tests.Integration.CQRS.IMigratedBeforeUserRegisteredTevent));
      map("e2a8b2fb-c6b1-455b-a79b-e94b80b44604", typeof(Compze.Tests.Integration.CQRS.IMigratedReplaceUserChangedPasswordTevent));
      map("30e74877-d75a-430c-b466-a50f0dd928b3", typeof(Compze.Tests.Integration.CQRS.ISomeTevent));
      map("3996caab-5f71-4dd5-878f-83a0100f354e", typeof(Compze.Tests.Integration.CQRS.IUserChangedEmail));
      map("190ee130-3c7c-4369-af3c-3a5d96ec2e2b", typeof(Compze.Tests.Integration.CQRS.IUserChangedPassword));
      map("156f8363-0bd9-4553-b4b9-33a7c2825d02", typeof(Compze.Tests.Integration.CQRS.IUserRegistered));
      map("2e2ec47b-e609-4f62-8ba6-1d322936e2c8", typeof(Compze.Tests.Integration.CQRS.IUserTevent));
      map("3acc8557-fbd0-4b4b-ab4e-21e04a291b3e", typeof(Compze.Tests.Integration.CQRS.IUserTevent`1));
      map("b88c60c5-1142-4e6d-aca5-abb80f13496d", typeof(Compze.Tests.Integration.CQRS.MigratedAfterUserChangedEmailTevent));
      map("4909cca8-2391-4541-8bb3-5b73e5d8fa3c", typeof(Compze.Tests.Integration.CQRS.MigratedBeforeUserRegisteredTevent));
      map("17b3dd26-0633-4525-824c-4f695435975a", typeof(Compze.Tests.Integration.CQRS.MigratedReplaceUserChangedPasswordTevent));
      map("3d805028-547b-4c63-bbab-1c9b7a2f69b0", typeof(Compze.Tests.Integration.CQRS.QueryModels.AutoGenerated.Domain.AccountTevent));
      map("960522ba-08a4-45d1-9df0-f37fc35c3100", typeof(Compze.Tests.Integration.CQRS.QueryModels.AutoGenerated.Domain.AccountTevent.AccountRegisteredTevent));
      map("ecb9b22e-814e-4432-af83-42db5943f146", typeof(Compze.Tests.Integration.CQRS.QueryModels.AutoGenerated.Domain.AccountTevent.Deleted));
      map("b2b9587a-9efa-42b7-8242-4099439599a8", typeof(Compze.Tests.Integration.CQRS.QueryModels.AutoGenerated.Domain.AccountTevent.EmailChanged));
      map("612c3244-1c33-4083-b56a-6bb5108295b5", typeof(Compze.Tests.Integration.CQRS.QueryModels.AutoGenerated.Domain.AccountTevent`1));
      map("5332e68a-ea2a-4a48-b044-0f6e03ddd113", typeof(Compze.Tests.Integration.CQRS.QueryModels.AutoGenerated.Domain.IAccountTevent));
      map("86ed29e7-f686-4537-aa82-87c7a0101043", typeof(Compze.Tests.Integration.CQRS.QueryModels.AutoGenerated.Domain.IAccountTevent.Deleted));
      map("5c729264-90f2-44f3-87fd-087d112b0e75", typeof(Compze.Tests.Integration.CQRS.QueryModels.AutoGenerated.Domain.IAccountTevent.IAccountRegisteredTevent));
      map("224b5fe4-4c91-4c7a-9765-ceee9514a8d2", typeof(Compze.Tests.Integration.CQRS.QueryModels.AutoGenerated.Domain.IAccountTevent.IEmailChanged));
      map("c301b17e-3fc6-43f5-ac77-2b78c90fb3be", typeof(Compze.Tests.Integration.CQRS.QueryModels.AutoGenerated.Domain.IAccountTevent.PropertyUpdated.Email));
      map("3c567c7c-db63-4834-9623-5c846138e1d3", typeof(Compze.Tests.Integration.CQRS.QueryModels.AutoGenerated.Domain.IAccountTevent.PropertyUpdated.Password));
      map("56b6d2e7-ffae-42a6-8bfe-24108de50963", typeof(Compze.Tests.Integration.CQRS.QueryModels.AutoGenerated.Domain.IAccountTevent`1));
      map("e687cbda-629a-4b9b-a5ec-1a3964ee6e59", typeof(Compze.Tests.Integration.CQRS.QueryModels.AutoGenerated.Domain.MyAccount));
      map("9ca59132-20b5-4f68-bfa0-ba79c993f873", typeof(Compze.Tests.Integration.CQRS.QueryModels.AutoGenerated.Domain.UI.QueryModels.MyAccountQueryModel));
      map("b5f31ed2-fdc1-4342-927c-60cb524b462b", typeof(Compze.Tests.Integration.CQRS.SomeTevent));
      map("b07901c6-2b5d-4348-8894-4603773ce698", typeof(Compze.Tests.Integration.CQRS.User));
      map("00ef87d3-3a51-431d-9e63-ca230725e241", typeof(Compze.Tests.Integration.CQRS.UserChangedEmail));
      map("ca16af4b-f792-434d-87ec-9e879b6ac079", typeof(Compze.Tests.Integration.CQRS.UserChangedPassword));
      map("2cd960ed-51aa-4a15-a620-685dad7b0566", typeof(Compze.Tests.Integration.CQRS.UserRegistered));
      map("1db99ec2-c861-4fb9-b40e-aba68d827a39", typeof(Compze.Tests.Integration.CQRS.UserTevent));
      map("49ff7985-9906-4d6f-bb31-0dced35ca3dc", typeof(Compze.Tests.Integration.CQRS.UserTevent`1));
      map("c99427b6-af20-4cac-8170-927f22f8850b", typeof(Compze.Tests.Integration.Tessaging.ServiceBusSpecification.Given_a_backend_endpoint_with_a_tommand_tevent_and_tuery_handler.Experiment_with_unifying_tevents_and_tommands_test.GetUserTuery));
      map("84e7eb50-da79-44a4-aab8-ac8332874732", typeof(Compze.Tests.Integration.Tessaging.ServiceBusSpecification.Given_a_backend_endpoint_with_a_tommand_tevent_and_tuery_handler.Experiment_with_unifying_tevents_and_tommands_test.IUserRegistrarTevent));
      map("321afa6c-93d4-4310-b67b-ef5d40d9f457", typeof(Compze.Tests.Integration.Tessaging.ServiceBusSpecification.Given_a_backend_endpoint_with_a_tommand_tevent_and_tuery_handler.Experiment_with_unifying_tevents_and_tommands_test.IUserRegistrarTevent`1));
      map("683a13a6-7d2b-40b9-b1ce-c45c7cafc960", typeof(Compze.Tests.Integration.Tessaging.ServiceBusSpecification.Given_a_backend_endpoint_with_a_tommand_tevent_and_tuery_handler.Experiment_with_unifying_tevents_and_tommands_test.IUserTevent));
      map("e5a8d8da-5c2c-4ba0-ac28-cb7e1b02134f", typeof(Compze.Tests.Integration.Tessaging.ServiceBusSpecification.Given_a_backend_endpoint_with_a_tommand_tevent_and_tuery_handler.Experiment_with_unifying_tevents_and_tommands_test.IUserTevent.UserRegistered));
      map("4f62c0f9-e155-43de-9454-f683b0a8ceb4", typeof(Compze.Tests.Integration.Tessaging.ServiceBusSpecification.Given_a_backend_endpoint_with_a_tommand_tevent_and_tuery_handler.Experiment_with_unifying_tevents_and_tommands_test.IUserTevent`1));
      map("91ea880a-606b-43aa-b586-f56038262578", typeof(Compze.Tests.Integration.Tessaging.ServiceBusSpecification.Given_a_backend_endpoint_with_a_tommand_tevent_and_tuery_handler.Experiment_with_unifying_tevents_and_tommands_test.UserRegistrarTaggregate));
      map("e106e812-9ab4-4256-aad5-1f9ef8602a94", typeof(Compze.Tests.Integration.Tessaging.ServiceBusSpecification.Given_a_backend_endpoint_with_a_tommand_tevent_and_tuery_handler.Experiment_with_unifying_tevents_and_tommands_test.UserRegistrarTevent));
      map("eebf0412-f759-49d1-bd7e-cc764dffae99", typeof(Compze.Tests.Integration.Tessaging.ServiceBusSpecification.Given_a_backend_endpoint_with_a_tommand_tevent_and_tuery_handler.Experiment_with_unifying_tevents_and_tommands_test.UserRegistrarTevent.Created));
      map("422972f6-1db5-43f2-905f-7b8dbe265c96", typeof(Compze.Tests.Integration.Tessaging.ServiceBusSpecification.Given_a_backend_endpoint_with_a_tommand_tevent_and_tuery_handler.Experiment_with_unifying_tevents_and_tommands_test.UserRegistrarTevent`1));
      map("3893e38f-eea6-412d-bde0-0b2e7c10f5e2", typeof(Compze.Tests.Integration.Tessaging.ServiceBusSpecification.Given_a_backend_endpoint_with_a_tommand_tevent_and_tuery_handler.Experiment_with_unifying_tevents_and_tommands_test.UserRegistrarTommand.RegisterUserTypermediaTommand));
      map("c2ce6605-fbf7-499d-ae26-e3451cb1be0b", typeof(Compze.Tests.Integration.Tessaging.ServiceBusSpecification.Given_a_backend_endpoint_with_a_tommand_tevent_and_tuery_handler.Experiment_with_unifying_tevents_and_tommands_test.UserTaggregate));
      map("ac02b095-ede5-4092-8ff1-62b2f42ebfc3", typeof(Compze.Tests.Integration.Tessaging.ServiceBusSpecification.Given_a_backend_endpoint_with_a_tommand_tevent_and_tuery_handler.Experiment_with_unifying_tevents_and_tommands_test.UserTevent));
      map("8db983bd-7921-4211-8541-a3cafc828e3e", typeof(Compze.Tests.Integration.Tessaging.ServiceBusSpecification.Given_a_backend_endpoint_with_a_tommand_tevent_and_tuery_handler.Experiment_with_unifying_tevents_and_tommands_test.UserTevent.UserRegisteredTevent));
      map("d836b756-c8f4-4ae7-990c-0e30eea57c0d", typeof(Compze.Tests.Integration.Tessaging.ServiceBusSpecification.Given_a_backend_endpoint_with_a_tommand_tevent_and_tuery_handler.Experiment_with_unifying_tevents_and_tommands_test.UserTevent`1));
      map("dec2aa55-eb86-4b37-ac6a-e7cd4987ff4b", typeof(Compze.Tests.Integration.Tessaging.ServiceBusSpecification.Navigator_specification.GetUserTuery));
      map("0a6eb5a4-13b9-419c-a145-d6cd3df5c420", typeof(Compze.Tests.Integration.Tessaging.ServiceBusSpecification.Navigator_specification.RegisterUserTypermediaTommand));
      map("c270b8eb-b4e1-4bd8-b0de-dae0e2eb14ce", typeof(Compze.Tests.Integration.Tessaging.ServiceBusSpecification.Navigator_specification.UserApiStartPageTuery));
      map("108a37b8-953d-4cd2-af25-b7c853056e8b", typeof(Compze.Tests.Integration.Tessaging.ServiceBusSpecification.When_scheduling_tommands_to_be_sent_in_the_future.ScheduledTommand));
   }
}
