using Compze.Abstractions.Refactoring.Naming;
using Compze.Tests.Common.Sql.DocumentDb;

[assembly: TypeMappings(typeof(Compze.Tests.Integration.TypeMappingDeclarations))]

namespace Compze.Tests.Integration;

class TypeMappingDeclarations : ITypeMappingDeclaration
{
   public void DeclareMappings(ITypeMappingRegistrar map)
   {
      map.Map<CQRS.IMigratedAfterUserChangedEmailTevent>("99302c63-3bfc-4e81-a678-16e73ff982c5")
         .Map<CQRS.IMigratedBeforeUserRegisteredTevent>("3cd859f1-a710-46a6-b3e2-e6b251db6467")
         .Map<CQRS.IMigratedReplaceUserChangedPasswordTevent>("e2a8b2fb-c6b1-455b-a79b-e94b80b44604")
         .Map<CQRS.ISomeTevent>("30e74877-d75a-430c-b466-a50f0dd928b3")
         .Map<CQRS.IUserChangedEmail>("3996caab-5f71-4dd5-878f-83a0100f354e")
         .Map<CQRS.IUserChangedPassword>("190ee130-3c7c-4369-af3c-3a5d96ec2e2b")
         .Map<CQRS.IUserRegistered>("156f8363-0bd9-4553-b4b9-33a7c2825d02")
         .Map<CQRS.IUserTevent>("2e2ec47b-e609-4f62-8ba6-1d322936e2c8")
         .Map<CQRS.MigratedAfterUserChangedEmailTevent>("b88c60c5-1142-4e6d-aca5-abb80f13496d")
         .Map<CQRS.MigratedBeforeUserRegisteredTevent>("4909cca8-2391-4541-8bb3-5b73e5d8fa3c")
         .Map<CQRS.MigratedReplaceUserChangedPasswordTevent>("17b3dd26-0633-4525-824c-4f695435975a")
         .Map<CQRS.QueryModels.AutoGenerated.Domain.AccountTevent>("3d805028-547b-4c63-bbab-1c9b7a2f69b0")
         .Map<CQRS.QueryModels.AutoGenerated.Domain.AccountTevent.AccountRegisteredTevent>("960522ba-08a4-45d1-9df0-f37fc35c3100")
         .Map<CQRS.QueryModels.AutoGenerated.Domain.AccountTevent.Deleted>("ecb9b22e-814e-4432-af83-42db5943f146")
         .Map<CQRS.QueryModels.AutoGenerated.Domain.AccountTevent.EmailChanged>("b2b9587a-9efa-42b7-8242-4099439599a8")
         .Map<CQRS.QueryModels.AutoGenerated.Domain.IAccountTevent>("5332e68a-ea2a-4a48-b044-0f6e03ddd113")
         .Map<CQRS.QueryModels.AutoGenerated.Domain.IAccountTevent.Deleted>("86ed29e7-f686-4537-aa82-87c7a0101043")
         .Map<CQRS.QueryModels.AutoGenerated.Domain.IAccountTevent.IAccountRegisteredTevent>("5c729264-90f2-44f3-87fd-087d112b0e75")
         .Map<CQRS.QueryModels.AutoGenerated.Domain.IAccountTevent.IEmailChanged>("224b5fe4-4c91-4c7a-9765-ceee9514a8d2")
         .Map<CQRS.QueryModels.AutoGenerated.Domain.IAccountTevent.PropertyUpdated.Email>("c301b17e-3fc6-43f5-ac77-2b78c90fb3be")
         .Map<CQRS.QueryModels.AutoGenerated.Domain.IAccountTevent.PropertyUpdated.Password>("3c567c7c-db63-4834-9623-5c846138e1d3")
         .Map<CQRS.QueryModels.AutoGenerated.Domain.MyAccount>("e687cbda-629a-4b9b-a5ec-1a3964ee6e59")
         .Map<CQRS.QueryModels.AutoGenerated.Domain.UI.QueryModels.MyAccountQueryModel>("9ca59132-20b5-4f68-bfa0-ba79c993f873")
         .Map<CQRS.SomeTevent>("b5f31ed2-fdc1-4342-927c-60cb524b462b")
         .Map<CQRS.User>("b07901c6-2b5d-4348-8894-4603773ce698")
         .Map<CQRS.UserChangedEmail>("00ef87d3-3a51-431d-9e63-ca230725e241")
         .Map<CQRS.UserChangedPassword>("ca16af4b-f792-434d-87ec-9e879b6ac079")
         .Map<CQRS.UserRegistered>("2cd960ed-51aa-4a15-a620-685dad7b0566")
         .Map<CQRS.UserTevent>("1db99ec2-c861-4fb9-b40e-aba68d827a39")
         .Map<Tessaging.ServiceBusSpecification.Given_a_backend_endpoint_with_a_tommand_tevent_and_tuery_handler.Experiment_with_unifying_tevents_and_tommands_test.GetUserTuery>("c99427b6-af20-4cac-8170-927f22f8850b")
         .Map<Tessaging.ServiceBusSpecification.Given_a_backend_endpoint_with_a_tommand_tevent_and_tuery_handler.Experiment_with_unifying_tevents_and_tommands_test.IUserRegistrarTevent>("84e7eb50-da79-44a4-aab8-ac8332874732")
         .Map<Tessaging.ServiceBusSpecification.Given_a_backend_endpoint_with_a_tommand_tevent_and_tuery_handler.Experiment_with_unifying_tevents_and_tommands_test.IUserTevent>("683a13a6-7d2b-40b9-b1ce-c45c7cafc960")
         .Map<Tessaging.ServiceBusSpecification.Given_a_backend_endpoint_with_a_tommand_tevent_and_tuery_handler.Experiment_with_unifying_tevents_and_tommands_test.IUserTevent.UserRegistered>("e5a8d8da-5c2c-4ba0-ac28-cb7e1b02134f")
         .Map<Tessaging.ServiceBusSpecification.Given_a_backend_endpoint_with_a_tommand_tevent_and_tuery_handler.Experiment_with_unifying_tevents_and_tommands_test.RegisterUserResult>("d316b5fd-1960-4129-831f-580d231f8fb7")
         .Map<Tessaging.ServiceBusSpecification.Given_a_backend_endpoint_with_a_tommand_tevent_and_tuery_handler.Experiment_with_unifying_tevents_and_tommands_test.UserRegistrarTaggregate>("91ea880a-606b-43aa-b586-f56038262578")
         .Map<Tessaging.ServiceBusSpecification.Given_a_backend_endpoint_with_a_tommand_tevent_and_tuery_handler.Experiment_with_unifying_tevents_and_tommands_test.UserRegistrarTevent>("e106e812-9ab4-4256-aad5-1f9ef8602a94")
         .Map<Tessaging.ServiceBusSpecification.Given_a_backend_endpoint_with_a_tommand_tevent_and_tuery_handler.Experiment_with_unifying_tevents_and_tommands_test.UserRegistrarTevent.Created>("eebf0412-f759-49d1-bd7e-cc764dffae99")
         .Map<Tessaging.ServiceBusSpecification.Given_a_backend_endpoint_with_a_tommand_tevent_and_tuery_handler.Experiment_with_unifying_tevents_and_tommands_test.UserRegistrarTommand.RegisterUserTypermediaTommand>("3893e38f-eea6-412d-bde0-0b2e7c10f5e2")
         .Map<Tessaging.ServiceBusSpecification.Given_a_backend_endpoint_with_a_tommand_tevent_and_tuery_handler.Experiment_with_unifying_tevents_and_tommands_test.UserTaggregate>("c2ce6605-fbf7-499d-ae26-e3451cb1be0b")
         .Map<Tessaging.ServiceBusSpecification.Given_a_backend_endpoint_with_a_tommand_tevent_and_tuery_handler.Experiment_with_unifying_tevents_and_tommands_test.UserTevent>("ac02b095-ede5-4092-8ff1-62b2f42ebfc3")
         .Map<Tessaging.ServiceBusSpecification.Given_a_backend_endpoint_with_a_tommand_tevent_and_tuery_handler.Experiment_with_unifying_tevents_and_tommands_test.UserTevent.UserRegisteredTevent>("8db983bd-7921-4211-8541-a3cafc828e3e")
         .Map<Tessaging.ServiceBusSpecification.Navigator_specification.GetUserTuery>("dec2aa55-eb86-4b37-ac6a-e7cd4987ff4b")
         .Map<Tessaging.ServiceBusSpecification.Navigator_specification.RegisterUserTypermediaTommand>("0a6eb5a4-13b9-419c-a145-d6cd3df5c420")
         .Map<Tessaging.ServiceBusSpecification.Navigator_specification.UserApiStartPageTuery>("c270b8eb-b4e1-4bd8-b0de-dae0e2eb14ce")
         .Map<Tessaging.ServiceBusSpecification.Navigator_specification.UserRegisteredConfirmationResource>("4ac96e70-aff6-45d4-9240-c1f556e7bb47")
         .Map<Tessaging.ServiceBusSpecification.When_scheduling_tommands_to_be_sent_in_the_future.ScheduledTommand>("108a37b8-953d-4cd2-af25-b7c853056e8b");
   }
}
