name: CI

on:
  push:
    # branches: [ develop, main, master ]
  pull_request:
  workflow_dispatch:

permissions:
  contents: read

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        persistence: [SqliteMemory, Sqlite, PgSql, MySql, MsSql]
        di: [Microsoft, SimpleInjector, Autofac]
        serializer: [Newtonsoft]
        transport: [AspNetCore]

    name: "Test (${{ matrix.persistence }}:${{ matrix.di }}:${{ matrix.serializer }}:${{ matrix.transport }})"

    services:
      postgres:
        image: ${{ matrix.persistence == 'PgSql' && 'postgres:17' || '' }}
        env:
          POSTGRES_PASSWORD: "Development!1"
        ports:
          - 5432:5432
        options: >-
          --health-cmd "pg_isready -U postgres"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
      mysql:
        image: ${{ matrix.persistence == 'MySql' && 'mysql:8' || '' }}
        env:
          MYSQL_ROOT_PASSWORD: "Development!1"
        ports:
          - 3306:3306
        options: >-
          --health-cmd "mysqladmin ping -h localhost"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
      mssql:
        image: ${{ matrix.persistence == 'MsSql' && 'mcr.microsoft.com/mssql/server:2022-latest' || '' }}
        env:
          ACCEPT_EULA: "Y"
          MSSQL_SA_PASSWORD: "Development!1"
        ports:
          - 1433:1433
        options: >-
          --health-cmd "/opt/mssql-tools18/bin/sqlcmd -S localhost -U sa -P 'Development!1' -C -Q 'SELECT 1' || /opt/mssql-tools/bin/sqlcmd -S localhost -U sa -P 'Development!1' -Q 'SELECT 1'"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 10

    env:
      COMPOSABLE_MACHINE_SLOWNESS: "5.0"
      DOTNET_CLI_TELEMETRY_OPTOUT: "1"
      DOTNET_NOLOGO: "true"
      COMPOSABLE_MSSQL_DATABASE_POOL_MASTER_CONNECTIONSTRING: ${{ matrix.persistence == 'MsSql' && 'Data Source=localhost;Initial Catalog=master;User Id=sa;Password=Development!1;TrustServerCertificate=True;' || '' }}

    steps:
      - uses: actions/checkout@v4

      - name: Build and Test
        uses: ./.github/actions/build-and-test
        with:
          configuration: Debug
          pluggable-components: "${{ matrix.persistence }}:${{ matrix.di }}:${{ matrix.serializer }}:${{ matrix.transport }}"
